### PR TITLE
Hotreload save

### PR DESCRIPTION
**Pull request by kianzarrin**
- hot reloading saved data can fail because binary serializer tries to get data types from the wrong TMPE assembly.
This PR applies a patch that forces all data types to use latest TMPE assembly.
- Also if LOM is active asset data is hotreloaded.

First commit: introduce Preload Patch phase
Second commit: hot reload

EDIT: summary from discord talk:
- the patch here is only applied when hotreloading
- the patch only makes a difference when data was saved with a version of TMPE that resides in App Domain.
- I don't see any drawback to the patch except for the time it takes to process string (which I suspect is insignificant).
- LOM is required for asset data to persist because LOM stores asset custom data when loading. after load asset custom data is lost outside of LOM.

### CODE REVIEW

**Comment by krzychu124** [comment]
This feature shouldn't be available on public/release version

**Comment by kianzarrin** [comment]
> This feature shouldn't be available on public/release version

@krzychu124 its only available when hot-reloading. otherwise the code is not executed.

**Comment by krzychu124** [comment]
> > This feature shouldn't be available on public/release version
> 
> @krzychu124 its only available when hot-reloading. otherwise the code is not executed.

I understand, but I don't think normal users should be able to use hot-reloading feature. We have features like `ExtCitizen` data holding `ParkingAI` state which will desync and cause flying citizens all over the map. It's very minor issue if you develop or test things but very annoying when you actually play normally.

One more thing, I see that asset data reload will work only if LOM is available, right?

**Comment by kianzarrin** [comment]
>  I don't think normal users should be able to use hot-reloading
OK I make it DEBUG only. CS should probably turn off file observers too. but that can be done with LOM patch as well.

> I see that asset data reload will work only if LOM is available, right?

Yes. LOM holds the data that needs to be transferred.

**Comment by krzychu124** [comment]
Q: What will happen if I hot-reload different mod after hot-reloading TM:PE (patch is still active)?

**Review by krzychu124 — APPROVED** [review]

**Review by chameleon-tbn — APPROVED** [review]
Lgtm

**Pull request merged**
