### PR TITLE
New countries for speed limit designs

### LINKED ISSUE #1251: Localised "give way" (yield) and "priority" signs for `gb`
### Language name or ISO code

* `gb` (or `en`?) - England
* `cy` - Wales (Cymru)

### Localization file

SVG's in attached zips. They aren't 200x200 px - I'm not sure how you want to resize/export them for best quality.

* [gb.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7759636/gb.zip)
* [cy.zip](https://github.com/CitiesSkylinesMods/TMPE/files/7759635/cy.zip)

Contents:

* Give Way (yield)
* Priority over oncoming traffic (priority - or closest thing we have to it) - identical for `gb` and `cy`

The existing Stop sign icon is practically identical to those used in UK.

### Notes or questions?

The files are both from UK government agency under Open Government License 1.0:

* Give way (TSRGDNO 602) - author: TSRGD - license: OGL 1.0 - source https://commons.wikimedia.org/wiki/File:UK_traffic_sign_602.svg
* Priority over oncoming traffic (TSRGDNO 811) - author TSRGD - license: OGL 1.0 - source https://commons.wikimedia.org/wiki/File:UK_traffic_sign_811.svg

I've also added a page to the wiki (and linked from the various other localisation pages) for priority sign themes: https://github.com/CitiesSkylinesMods/TMPE/wiki/Priority-Signs-Icon-Themes

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #1251

* New speed limit themes for multiple countries
* Priority signs and parking signs also included in the theme

I have checked Steam popularity per country, skipped countries which are very similar to German and existing British road signs,  and figured out we can add 5 new country themes:
* [x] Sweden 🇸🇪  (because i live here alright, and because Paradox Interactive and community managers for C:S operate from here it might please them too 😀 ) 
bild

* [x] Brazil 🇧🇷 
bild

* [x] France 🇫🇷 
bild
bild

* [x] Indonesia 🇮🇩 
bild

* [x] South Korea 🇰🇷 (similar to German but more square font) 
bild

* [x] Japan 
bild

## New priority and parking signs for existing themes:

* Canada 
bild

* Germany 
bild
* UK
bild

* USA 
bild

### CODE REVIEW

**Comment by aubergine10** [comment]
These look great!

I think the only other notable one would be Japan which has blue text on the speed limit signs.

**Comment by aubergine10** [comment]
The icons are embedded in the .dll file? If so, they're all still getting loaded in to RAM along with the .dll?

**Comment by kvakvs** [comment]
> The icons are embedded in the .dll file? If so, they're all still getting loaded in to RAM along with the .dll?

Yes I did not change the way textures are delivered into the resulting DLL, they are embedded but as compressed PNG, that's about 20kb per file. They are loaded on demand though.

**Comment by kvakvs** [comment]
Plus something tells me Windows loads DLL files using mmap. Should doublecheck if actual real memory is used.

**Comment by krzychu124** [comment]
I would be more concern if we instantiate textures -> they will eat VRAM, RAM is not really a problem

> The icons are embedded in the .dll file? If so, they're all still getting loaded in to RAM along with the .dll?

Textures created from those images are worse, since they eat VRAM which you can't really extend without huge performance drop. I think we should compare `master` with this PR in terms of RAM difference (e.g. in noWorkshop mode), because now we can only guess. TMPE already takes probably somewhere ~200MB when loaded in game (dll of master has +- 6.5MB right now), so 10-15MB more won't make much of a difference.

**Comment by aubergine10** [comment]
The new speed limits UI only has one set of textures for speed signs and overwrites those textures should user choose different speed sign icon theme (hence lag when switching between themes). At least that's what the code says, I've not tested to see if Unity is doing some weirdness under the hood.

**Comment by aubergine10** [comment]
Found another one that might be worthy to add due to it's extremely unusual colours - SACU (South African Customs Union) - SVGs of most of their signs available at link below:

https://commons.wikimedia.org/wiki/Category:SVG_road_signs_in_the_Southern_African_Customs_Union

Could potentially also provide custom Priority sign icons too:

* Yield: https://commons.wikimedia.org/wiki/File:SACU_road_sign_R2.svg
* Stop: https://commons.wikimedia.org/wiki/File:SACU_road_sign_W302.svg

**Comment by kvakvs** [comment]
South African signs look very much like a mix of German signs and orange Swedish-Finnish style backgrounds. Also the country is not represented in top 15 Steam users, so I assumed also not in top 15 C:S users
https://www.statista.com/statistics/826870/steam-distribution-country/

**Review by aubergine10 — CHANGES_REQUESTED** [review]
Indonesia `NoParking.png` sign seems to be the old `Parking.png` (green parking allowed) sign?

image

I also noticed that, after changing theme via mod options, the parking overlays won't appear upon tool selection - until I move the camera (probably nothing to do with this PR and only very minor issue tbh).

**Comment by kvakvs** [comment]
> Indonesia `NoParking.png` sign seems to be the old `Parking.png` (green parking allowed) sign?

This is a confusing one. It allows me to supply a few signs and not all 5 if i wish so, and then it takes missing signs from the default old signs we're used to have. Why it picks the green one is beyond me, i need to look at it again.

**Comment by kvakvs** [comment]
> I also noticed that, after changing theme via mod options, the parking overlays won't appear upon tool selection - until I move the camera (probably nothing to do with this PR and only very minor issue tbh).

The parking tool does not subscribe to theme change event.

**Comment by kvakvs** [comment]
All issues fixed now:
- Indonesian no-parking added a special sign
- Found a bug when parking sign was missing in the current theme, a parking-allowed (green P) was always selected
- Camera cache reset forced when parking tool activates
- Also converted all fonts to curves, to make it easier to do minor edits without installing a dozen of fonts

**Comment by aubergine10** [comment]
Not for this PR, but would be cool if changing icon theme updated the button icons on tmpe toolbar. (Priority tool shows `Yield.png` icon, Speed tool shows `30.png`, parking tool shows `Parking.png`)

**Comment by aubergine10** [comment]
For visual simplicity, would it be worth removing the text box from under the French `Yield.png`?

image

It's unreadable in the overlays unless zoomed all the way in, and if we ever wanted to use the icon for the priority signs button on toolbar it would get in the way.

**Review by aubergine10 — APPROVED** [review]
LGTM from in-game testing 👍

**Comment by krzychu124** [comment]
Works great, but...

1. Missing translation keys: 
image

2. What about loading previously selected theme - backward compatibility? Not a big deal, but I didn't tested what will happen when loaded savegame with theme different than default (German)
3. Why we are loading textures after loading translations? They are used in game so I'm not sure if is that necessary. I also added log call to Load and Unload methods and I see that we are calling load after translations (that was mentioned) but then again after loading savegame -> there is no Unload call before which suggests small memory leak, but we are changing game Scene between Main Menu to InGame so there is a chance that textured are destroyed similarly to gameobjects without DontDestroyOnLoad call
4. Ok... there is a memory leak -> I don't see the code for unloading textures on mod disable

**Comment by kvakvs** [comment]
For memory leak my suggestion is to create one or more `TextureManager`'s which will get lifecycle start event and load, and then will get lifecycle end event and unload. In this PR or in separate.

**Comment by kvakvs** [comment]
> What about loading previously selected theme - backward compatibility? Not a big deal, but I didn't tested what will happen when loaded savegame with theme different than default (German)

When config option contains theme name that is not known, it will reset to default Kmph theme (Kmph_Germany) or to default MPH theme (MPH_UK).

**Comment by krzychu124** [comment]
> For memory leak my suggestion is to create one or more `TextureManager`'s which will get ~lifecycle start~ level loaded event and load, and then will get ~lifecycle end~ level unloaded event and unload. In this PR or in separate.

It can be done in separate PR, no problem. I'll approve this one, since it works pretty well.

**Review by krzychu124 — APPROVED** [review]
👍 memory leak issues can be fixed in the next PR

**Pull request merged**
