### PR TITLE
Version bump, compatibility fix for new BloodyPenguin's mod

### PR DESCRIPTION
**Pull request by krzychu124**
## TM:PE Stable v.11.5.2

Little compatibility hotfix for upcoming @BloodyPenguin's mod - support for new forms of transporting cargo (water and air)

_Note:
Current `master` branch does not require any changes because it will be fully compatible (we don't patch the same methods)_

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]
Nice

**Comment by krzychu124** [comment]
Mod Teaser, if you are curious what is it 🙃 

<div align="center">
  <a href="https://www.youtube.com/watch?v=hNniVbDs9ZU">barges teaser</a>
</div>

**Comment by kianzarrin** [comment]
what does the mod do?

**Review by kianzarrin — APPROVED** [review]
it would be better to add all these vehicle types to a relevant constant. but we are getting rid of CustomAI anyway so it does not matter for now.

I am not sure what the mod does and why this change is required but at least it's consistent.

**Comment by krzychu124** [comment]
This mod will add cargo ferries(barges) which will use canals to transport cargos. 
Vanilla does not have ferryAI for transport cargo and there is no ferry cargo port AI, so without assets with new AIs and barges (also with new AI) it won't make any difference.

**Pull request merged**
