### PR TITLE
Locale key updates

### LINKED ISSUE #1344: Translations for 11.6.5 (localisation / locale / crowdin)
Note, this is just a planned list - don't add these to Crowdin yet (items listed here are subject to change, even after PRs are merged).

- [x] PR #1455
    * Some new UI groups - eg. highways
- [x] PR #1454
    * Hint text for overground/underground view https://github.com/CitiesSkylinesMods/TMPE/pull/1454#issuecomment-1059610762
- [x] PR #1404
    * Mod option on Overlays tab
- [x] PR #1301
    * Checkbox not in scope tooltip
- [x] PR #1343
    * In-game message about despawn due to pathfinder update
- [x] PR #1347
    * In-game message about despawned vehicles
- [x] PR #1341
    * Despawn group + filters on Maintenance tab
- [x] PR #1284
    * https://github.com/CitiesSkylinesMods/TMPE/issues/1288
    * Mostly done - remaining stuff moved to #1567
- [x] Issue #1268
    * `Overlay Opacity`

### PR DESCRIPTION
**Pull request by aubergine10**
Note: Testing should be done with a DEBUG build (missing locale string pilcrows aren't shown in TEST/RELEASE builds).

Fixes #1344:

* Added new locale keys to Crowdin
* Included latest translations from Crowdin
* Updated few locale keys in code to match simplified keys on Crowdin
* Updated despawn button to use custom component (same as other buttons)
* Localise `What's New` button in mod options
* Localise title bar of `What's New` panel
* Localise pathfinder update message

Some additional future work is tracked in #1567

New languages (some translations already introduced in earlier PRs):

* Vietnamese = [DucAnhLam](https://crowdin.com/profile/ducanhlam)

List of contributors in this batch of updates:

* [Nguyễn Tài Đức (nguyentaiduc.mr)](https://crowdin.com/profile/nguyentaiduc.mr)
* [OldEj (agrey546)](https://crowdin.com/profile/agrey546)
* [AduitSSH](https://crowdin.com/profile/aduitssh)
* [Chamëleon (chameleon-tbn)](https://crowdin.com/profile/chameleon-tbn)
* [문주원 (sky162178)](https://crowdin.com/profile/sky162178)
* [krzychu124](https://crowdin.com/profile/krzychu124)
* [shg166 (shg166_csl)](https://crowdin.com/profile/shg166_csl)
* [John Lok Ho (lok91101)](https://crowdin.com/profile/lok91101)
* [Márcio Saeger (Saeger)](https://crowdin.com/profile/saeger)
* [DucAnhLam](https://crowdin.com/profile/ducanhlam)
* [DNSE (dnse)](https://crowdin.com/profile/dnse)
* [Arne Peirs (Olympic1)](https://crowdin.com/profile/olympic1)
* [Neoone (Neooneqq)](https://crowdin.com/profile/neooneqq)
* [Fatih YILDIRIM (symbol54)](https://crowdin.com/profile/symbol54)
* [Zeldslayer](https://crowdin.com/profile/zeldslayer)
* [GiorgioHerbie](https://crowdin.com/profile/giorgioherbie)
* [krzychu124](https://crowdin.com/profile/krzychu124)

### CODE REVIEW

**Comment by aubergine10** [comment]
image

**Comment by krzychu124** [comment]
I've updated translation scheme files (Vietnamese should be available `vi`), approved and improved some incorrectly translated strings (mostly Italian 😄 )

**Comment by krzychu124** [comment]
Is there are chance about merging it till e.g. this weekend, so we could push it to Test and then release hot-fixed 11.6.5.2 to Stable to move away from the current broken/not switchable state (Test <-> Stable)?
Since @kianzarrin working on UI for lane connector to separate tracks from road (or even finished if I see correctly) maybe the version should be `11.6.6.0` instead of current `11.6.5.3`?
It's just a thought to discuss further since would be nice to speed up development and move forward a little bit faster. Heh, my todo list is constantly growing 😂

Next up we have @Elesbaan70 persistence thingy which could be release along with Airports DLC support - not much left to add there, and I thought about using new persistence for serializing passenger airplane size restrictions as any modification to current serialization solution will break compatibility again and complicate things...

Persistence and Airports DLC improvements as a `11.7.x` or maybe even better, as `v.12` if we generate more changes? I mean.. persistence change is itself a big change 😅 
I'll try to squeeze few priority behavior improvements there too or minor improvements for ParkingAI (I've done few experiments already and results are promising - is slightly better than before, without much effort like e.g.: rewriting the logic) I remember you also started working on overlays so it could nicely fit into "big changes" release.

**Comment by aubergine10** [comment]
Yup, will try and get this done tomorrow. Sorry for delay, been spending lots of time this week arguing with lawyers about changing my legal name to "State Funded Terrorism" which they seem to have issue with yet they're finding it difficult to explain why without accepting that the entire legal system is complete bullshit.

**Comment by aubergine10** [comment]
ready for testing

**Review by kvakvs — APPROVED** [review]
Nice

**Comment by krzychu124** [comment]
Missing key (we can add later) :/
image

/// Not related to this PR but still something we should fix but can live with it

Slider is not disabled in the main menu
image

The same for speed limit themes + checkbox - shows warning that settings cannot be changed in main menu so at least that but both are stored in the global config so they could be changed, just skipped regular update and texture generation (will be generated at load time)
image

No vertical scroll at **Keybinds** tab (does not show up and work for some weird reason 🤷‍♂️ )

IMO it's still good enough to push to Stable, anyways

**Review by krzychu124 — APPROVED** [review]
Tested in game, `Vietnamese` lang works as it should, didn't notice any broken things with regards to translation 👍

**Comment by aubergine10** [comment]
> Missing key (we can add later) :/

Yup, tracked in https://github.com/CitiesSkylinesMods/TMPE/issues/1567

> Slider is not disabled in the main menu

I think they're disabled but just not 'dimmed'.

> The same for speed limit themes + checkbox

Those are acutally global options, although I'm not sure why. Personally I feel it would make more sense to have those as savegame options, but they were already done as global options prior to me and Kian reworking the UI components. We could probably look in to that with the new persistence stuff?

**Comment by krzychu124** [comment]
> I think they're disabled but just not 'dimmed'.

nope, I see it is reporting changes and enabled the dls checkbox despite it was disabled

**Comment by aubergine10** [comment]
> > I think they're disabled but just not 'dimmed'.
> 
> nope, I see it is reporting changes and enabled the dls checkbox despite it was disabled

I've added a note about that to #1567

**Pull request merged**
