### PR TITLE
What's New in TM:PE 11.6.4.3?

### PR DESCRIPTION
**Pull request by aubergine10**
This is bug fix release:

* [Meta] TM:PE 11.6.4-hotfix-3
* [Meta] This fixes rare issue on some PCs that are limited to single CPU core
* [Fixed] Incorrect minimal number of path-find threads #1331 (krzychu124)
* [Updated] Code clean-up: Refactor `OptionsManager.cs` #1321 (kvakvs, aubergine18)
* [Updated] Show full version in UI and log file #1335 (aubergine18)
* [Removed] Temporary: Don't auto-show What's New on TM:PE menu button click #1336 #1314 (krzychu124, aubergine18)

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]

**Comment by aubergine10** [comment]
@krzychu124 Can we push 11.6.4.3 to workshop today?

**Comment by krzychu124** [comment]
Yeah, I need to do something but will release it today

**Review by krzychu124 — APPROVED** [review]

**Comment by krzychu124** [comment]
_Merging and releasing_

**Comment by aubergine10** [comment]
Now the joy of dealing with that weird `Avoid` direction awaits... Pretty sure CO blundered something in their flag values tbh, unless my understanding of binary is wrong.

**Pull request merged**
