### PR TITLE
Apply Shift+Click speed limit to entire roundabout

### LINKED ISSUE #869: Apply Shift+Click speed limit to entire roundabout
> @thebugfixnet I figured out that the Speed-Limit function works within round-abouts in the same way they do on normal roads.
On normal roads with Shift-Klick the speed limit is assigned from one junction to the next. I can understand this as in real world also the speed limits at the next crossing may be different. So this behavior i was ecpexting.
But on roundabouts in my opinion there should be the logic to set the speed limit for the whole roundabout street with Shift-Klick. This is the way ot is in real i think. Additionally the super function of automated lower speed limits on roundabouts do it for the whole roundabout road. To be consistend to this function it would be good to handle it in the same way for the speed-limit function.
image

So if it is a roundabout, I apply to all roundabout segments. Otherwise I apply between to junctions.

### PR DESCRIPTION
**Pull request by kianzarrin**
image
fixes #869

The GIF below demonstrates what happens in the case of lane count mismatch
ezgif com-optimize(2)

The road names "inverted" or "not inverted" shows if the invert flag of the segment. I have tested with both flags in the GIF above.

PS: I used auto code cleanup. Please use ignore white spaces to make the code review easier for yourself :)

### CODE REVIEW

**Comment by aubergine10** [comment]
Looking forward to testing this!

**Comment by aubergine10** [comment]
@kvakvs did you get chance to test this in-game yet?

**Comment by kianzarrin** [comment]
I forgot to test with LHT

**Comment by kianzarrin** [comment]
image
works on LHT too :)

**Comment by aubergine10** [comment]
Yup, I tested on LHT and couldn't break it. :)

**Pull request merged**
