### PR TITLE
nuget UUI

### PR DESCRIPTION
**Pull request by kianzarrin**
use nuget to get the latest UUI 2.2.1 
this latest UUI avoids crash and null exception

### CODE REVIEW

**Comment by kianzarrin** [comment]
I released UUI V2.2.1 to WS.

**Comment by aubergine10** [comment]
Seems to work. I had some errors thrown but they look related to #1443 so ideally need that merging in before testing again.

**Review by krzychu124 — APPROVED** [review]
Looks good, no issues in game.

**Review by aubergine10 — APPROVED** [review]
👍

**Pull request merged**
