### PR TITLE
11.3.1 Changelog and Version bump

### PR DESCRIPTION
**Pull request by aubergine10**
Updated changelog and assembly version.

### CODE REVIEW

**Comment by kvakvs** [comment]
Why do you have to duplicate changelog in two files?
Maybe only store changes since major or minor release in README and full goes into the CHANGELOG?

**Comment by aubergine10** [comment]
The main readme just contains the most recent stuff for the current x.y releases; I add to full changelog at same time so I don't forget to add it later.

**Comment by krzychu124** [comment]
Is it final list of changes? Are there any simple fixes left?

**Comment by aubergine10** [comment]
I have one more fix - need to update incompatible mods list, 1 sec...

**Comment by aubergine10** [comment]
Also bumped game version in shields.io badges.

#831 requires review and merge first

**Pull request merged**
