### PR TITLE
Refactored the GuiTimedControlPanel() function

### PR DESCRIPTION
**Pull request by s2500111**
For making it easier to distinguish which piece of code does what, I created some local functions within the function and split the loop over the light steps, so they only do one state (active or inactive) at once. Now, when reading the code, it should be logically unfolding instead of being a mess where you need hours to understand it. Especially if you collapse all the local functions until you need them.

Functionally it's the same, except for the copy and rotate button being moved to the bottom of the panel and being not visible when adding (or editing, but in this case it's as before) a step, as clicking it then breaks the node selection.

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]
Looking good
This will be replaced in the future, but for now i take it

**Review by krzychu124 — CHANGES_REQUESTED** [review]
Please check if code works same as before change, because for me it is not working as intended.
Two issues: 
- Start button should not be visible if there are no steps
- Add a junction to traffic lights doesn't work

Not to mention that original version has other bugs I noticed while comparing both versions 😕

**Comment by s2500111** [comment]
Ouh, I'll look into this. The start button is probably an easy fix, the other one ... I'll search for it.

If you might write down the other bugs of the original version I can try to find them too ...

**Comment by krzychu124** [comment]
There is a but when you click `Add Step`, `Add/remove junction` is still visible, If you click `x` to cancel adding step, you still can't add junction after clicking that button. Something is wrong with the state of the tool. 
I think that we could hide Add/Remove if you user is adding/editing steps. It will be the easiest solution for now.

**Comment by s2500111** [comment]
> There is a but when you click `Add Step`, `Add/remove junction` is still visible, If you click `x` to cancel adding step, you still can't add junction after clicking that button. Something is wrong with the state of the tool.
> I think that we could hide Add/Remove if you user is adding/editing steps. It will be the easiest solution for now.

The button is broken from the moment you try to add a step and works fine again when you hit edit on a step of the light ...

**Comment by s2500111** [comment]
When setting the selection ```nodeSelectionLocked``` to true when clicking the button, it works.

One thing is still problematic. I can add nodes that already have a timed traffic light, resulting in the light to stop and my already implemented steps being overwritten. I didn't verify that it's also in the stable version, but I think so.

**Comment by krzychu124** [comment]
What happened with commits?

**Comment by s2500111** [comment]
> What happened with commits?

Which commits? Did I remove something when trying to get my repo up to date?

**Comment by krzychu124** [comment]
I don't know what you did but I see double commits 🤔 Was there any conflict?

**Comment by s2500111** [comment]
Ah, I rebased my fork, that's where the double commits are from.

**Comment by s2500111** [comment]
Yeah, should've merged and not rebased.

https://stackoverflow.com/questions/9264314/git-commits-are-duplicated-in-the-same-branch-after-doing-a-rebase

**Comment by s2500111** [comment]
Finally found the time, I now removed the redundant commits.

**Comment by krzychu124** [comment]
Cool, I'll test it in about few minutes. I was busy too and completely forgot about you PR 😬

**Review by krzychu124 — APPROVED** [review]
👍

**Comment by DaEgi01** [comment]
what is going on here? xD

**Comment by DaEgi01** [comment]
yooo? any merge happening here?

**Comment by krzychu124** [comment]
> yooo? any merge happening here?

I think that pushing commit to his `master` branch is not the best idea 😂  _(let's see how bad the web editor is for resolving conflicts...)_

**Comment by aubergine10** [comment]
Any progress on this?

**Comment by kianzarrin** [comment]
> @kvakvs This will be replaced in the future, but for now i take it

is there any issue? do you plan to do this?

**Comment by krzychu124** [comment]
> > @kvakvs This will be replaced in the future, but for now i take it
> 
> is there any issue? do you plan to do this? Is that why there is so many conflicts?

@kianzarrin it's not wise to push changes to someone's `master` branch, it's probably locked.

@s2500111 could you sync with our `master` and resolve conflict if any so we could re-test (a lot of things changed in the meantime) and merge in?

**Comment by kianzarrin** [comment]
> it's not wise to push changes to someone's master branch, it's probably locked.

i wasn't planing to.

**Pull request closed without merging**
