### PR TITLE
lom asset hot-reload

### PR DESCRIPTION
**Pull request by kianzarrin**
load order mod takes a record of asset user data so that other mods can reuse it for hot reload. see https://github.com/kianzarrin/LoadOrder/blob/06f06d6dedced11153462070416774374c258fb9/LoadOrderMod/AssetDataExtension.cs#L27

TMPE can reuse this to load TMPE rules for Intersections during hot-reload.

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]
Nice

**Review by krzychu124 — APPROVED** [review]

**Review by DaEgi01 — APPROVED** [review]

**Comment by kianzarrin** [comment]
This does not work with TMPE:
```
Error 198.0750241: System.ArgumentException: Object type System.Collections.Generic.List`1[TrafficManager.Util.Record.IRecordable] cannot be converted to target type: System.Collections.Generic.List`1[TrafficManager.Util.Record.IRecordable]
```
I am guessing System.Collections.Generic is linked against old TMPE assembly while we are trying to convert to type in new TMPE assembly.

**Comment by kianzarrin** [comment]
But TMPE saved game data (SerializableDataExtension) also uses binary serialization and that does not seem to face the same problem. why is that?

**Comment by kianzarrin** [comment]
i will close this until i fix the problem.
maybe this : https://docs.microsoft.com/en-us/dotnet/standard/serialization/version-tolerant-serialization#serializationbinder
> Some users may need to control which class to serialize and deserialize because a different version of the class is required on the server and client. SerializationBinder is an abstract class used to control the actual types used during serialization and deserialization. To use this class, derive a class from SerializationBinder and override the BindToName and BindToType methods. For more information, see Controlling Serialization and Deserialization with SerializationBinder.

**Pull request closed without merging**
