### PR TITLE
Onscreen Hints for more tools

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes: #720

- [x] Should be fixing the ominous null UIView problem when UI components are deactivated by SetActive(false) and beheaded by DetachChildren in their parent
- [x] Junction Restrictions tool
  - [x] Strings: JunctionRestrictions.csv: "OnscreenHint.Mode:Select", "OnscreenHint.Reset:Reset to default" (or reuse from LaneRouting.csv "LaneConnector.Label:Reset to default")
- [x] Manual Traffic Lights tool
  - [x] Strings: TrafficLights.csv: "ManualTL.Mode:Select", "ManualTL.Mode:Edit"
- [x] Priority Signs tool
  - [x] Strings: PrioritySigns.csv: "OnscreenHint.Mode:Select", "OnscreenHint.Mode:Edit"
  - [x] Strings: "Prio.Click:Quick setup prio road/roundabout", "Prio.Click:Quick setup high prio road/roundabout","Prio.Click:Quick setup prio junction"
  - [ ] Remove "Tooltip.Keybinds:Add priority signs"
- [x] Toggle Traffic Lights tool
  - [x] Strings: TrafficLights.csv: "ToggleTL.Mode:Click to toggle"
- [x] ~~Timed Traffic Lights tool~~
- [x] ~~Speed Limits tool~~
- [x] Parking Restrictions tool
  - [x] Strings: ParkingRestrictions.csv "OnscreenHint.Mode:Click to toggle"
- [x] Vehicle Restrictions tool
  - [x] Strings: VehicleRestrictions.csv "OnscreenHint.Mode:Select segment", "OnscreenHint.Mode:Toggle restrictions"

bild

# Review TODO list

- [x] TimedTL: Remove Ctrl+Click
- [x] Prio: move Ctrl+Click above Shift+... items
- [x] Prio: Click priority signs to toggle is confusing when editing a junction with no signs: Might be better as Click circles to change - [ ] signs ?
- [x] Prio: Remove right click to leave //comment
- [x] Prio: Click junction to edit will delete signs
- [x] JR: Default text when junction selected? Click icons to toggle
- [x] VR: Default Choose a segment to edit hint still visible even after choosing a segment: I know technically it's still valid, as I can choose another segment just by clicking it, but it just seems a little confusing from user perspective as it feels like I've done what it says (choose segment) and it's still asking me to choose segment. Maybe when segment is chosen it could change to Click icons to toggle vehicle bans ?
- [x] VR: Delete | Bksp Revert to default
- [x] Parking: Maybe simplify to Click icons to toggle parking ban?
- [x] Parking: Shift + Click Apply change to whole road
- [x] Parking: Remove [Shift]: Apply changes
- [x] LaneConn: Right Click Leave selected node is showing while I have a lane selected: Better as Right Click Leave selected lane ?

### CODE REVIEW

**Comment by aubergine10** [comment]
<details><summary>Assuming some default text is wanted for each tool:</summary>

#### Junction restrictions:

> Choose a junction to edit

#### Priority signs:

_The interaction model for priority signs is grim; would be good to make it work more like Junction Restrictions if possible._

> Choose a junction to edit

#### Toggle traffic lights:

> Click junctions to toggle traffic lights

#### Timed traffic lights:

_Maybe leave this one until we revamp the TTL UI?_

> Choose a junction to edit

#### Speed limits:

_Maybe leave this one until we revamp the speed limits UI?_

#### Parking restrictions:

> Click parking icons to toggle parking

#### Vehicle restrictions

> Choose a segment to edit
</details>

**Comment by kvakvs** [comment]
Ready for testing
Discovered bug: Speed limits window lost its background (still works)

**Comment by aubergine10** [comment]
I think speed limits should be next target for UI overhaul (separate PR obviously).

**Comment by aubergine10** [comment]
#### Priority signs

Can the `Ctrl+Click` be moved above the `Shift+...` items?

image

`Click priority signs to toggle` is confusing when editing a junction with no signs:

image

Might be better as `Click circles to change signs` ?

Also, right-clicking does not exit the selected node - issue with fsm?

**Comment by kvakvs** [comment]
I can modify the strings.
There is no finite state machine added to those other tools, that'd require full rewrite of the tool (namely i done that for Lane Arrows and currently doing that for Speed Limits).
The default old behaviour was that right click cannot exit. I can comment that text out.

**Comment by aubergine10** [comment]
#### Junction restrictions

Default text when junction selected? `Click icons to toggle`

image

**Comment by aubergine10** [comment]
#### Vehicle restricitons

Default `Choose a segment to edit` hint still visible even after choosing a segment:

image

I know technically it's still valid, as I can choose another segment just by clicking it, but it just seems a little confusing from user perspective as it feels like I've done what it says (choose segment) and it's still asking me to choose segment.

Maybe when segment is chosen it could change to `Click icons to toggle vehicle bans` ?

**Comment by aubergine10** [comment]
#### Parking restrictions

Maybe simplify to `Click icons to toggle parking ban`?

image

**Comment by aubergine10** [comment]
#### Lane connectors

`Right Click Leave selected node` is showing while I have a lane selected:

image

Better as `Right Click Leave selected lane` ?

**Comment by aubergine10** [comment]
#### Some missing shortcuts

For Parking Restrictions and Vehicle Restrictions:

* `Shift + Click` Apply change to whole road

For Vehicle Restrictions only:

* `Delete` | `Backspace` Revert to default

**Comment by aubergine10** [comment]
#### Tooltips

There's still old shorcut info in some tool buttons:

image

image

**Comment by kvakvs** [comment]
Created checklist (first post) from your comments.

**Comment by kvakvs** [comment]
Found the same: missing background in Vehicle Restrictions in IMGUI window
Same as the missing background in Speed limits IMGUI
Not sure what could it be

**Comment by aubergine10** [comment]
`Right Click` ....?

image

Missing locale string:

image

Speed limits bg is working for me:

image

As is vehicle restrictions:

image

Maybe something to do with opacity setting?

**Comment by kianzarrin** [comment]
@kvakvs can you please refresh tooltip for despawning toggle. it does not get updated when I click the button. I have to move the mouse out and back in again.
Screenshot (966)

**Comment by kvakvs** [comment]
ready for another round of review
also: inverted button highlight on despawning, active is easy mode, off is hard mode.

**Comment by aubergine10** [comment]
I don't have a lane selected yet, but the `Right Click` hint is saying it will leave selected lane...

image

Other than that, looks good. Does it include the fix for tooltips updating before UI is ready (that were causing you crashes as discussed in Discord chat)?

**Comment by kvakvs** [comment]
The fix for crash was done immediately and merged with the previous ticket (for priority signs positioning), it was a severe bug.

**Comment by aubergine10** [comment]
There is still the issue with right click hint mentioned in https://github.com/CitiesSkylinesMods/TMPE/pull/868#issuecomment-623876391 :

image

I do not have a lane selected; I only have the node selected. In this state it should be saying `Right Click Leave selected node`.

**Pull request merged**
