### PR TITLE
Patcher manual patching. Add Harmony patches for Reversible Tram AI mod

### PR DESCRIPTION
**Pull request by sway2020**
Fixes: #1361

Related issues: #1353 #1361

### CODE REVIEW

**Comment by sway2020** [comment]
Maybe we should only merge this after this discussion is solved:

https://github.com/sway2020/ReversibleTramAI/issues/3

**Comment by sway2020** [comment]
I am rewriting the mod the make it patch the original Tram AI instead of creating a new tram AI. I'll reopen this when the rewrite is done

**Comment by kianzarrin** [comment]
what changes TMPE needs to make?

**Comment by krzychu124** [comment]
@kianzarrin, none, it's old PR. You've even changed part of the solution recently (#1457)...

**Comment by kianzarrin** [comment]
Will TMPE need changes after sway changes his mod?

**Comment by krzychu124** [comment]
What changes do you mean? We only add triggers to his version of AI, just like for vanilla tram AI.

**Comment by aubergine10** [comment]
Worst case scenario is that the patches fail and some TM:PE features don't work on tram roads (game should still run fine though).

**Comment by kianzarrin** [comment]
@sway2020 said:
> I am rewriting the mod to make it patch the original Tram AI instead of creating a new tram AI. I'll reopen this when the rewrite is done

Will this require code change on TMPE side? 

I am asking this because I might be able to take preemptive measures to avoid failure all together.

**Pull request closed without merging**
