### PR TITLE
Simulation Accuracy setting regression

### LINKED ISSUE #1554: Yield/Giveway is not adhered to on master branch
### Describe the problem
Using Steam stable Traffic Manager, everything works fine with priority signage. With a self compiled version from master branch, all priority/yield is not adhered to, turning on and off give-way does nothing.

This could be an issue from my compiling but i have tried to reinstall VS a couple times with .net framework 4.8 and 3.5 and issue still persists.
 

### Log files

https://drive.google.com/drive/folders/1Fvu2WERDM28w5mUfIZ5otCXF8SJh4I6u?usp=sharing

this folder contains output and tmpe logs from both steam downloaded tmpe and self compiled. if link doesnt work please comment

### PR DESCRIPTION
**Pull request by krzychu124**
Fixed bug with **Simulation Accuracy** setting being completely ignored on load, save and update(via Options screen) in game

Once merged I'll update workshop **Test** directly(as a hotfix) since we need to release **Test** as **Stable** before [11.6.5.3](https://github.com/CitiesSkylinesMods/TMPE/milestone/65) goes to **Test** otherwise it would cause compatibility issues with other Kian's mods

Fixes #1554

### CODE REVIEW

**Review by aubergine10 — APPROVED** [review]
👍

**Comment by aubergine10** [comment]
As far as I can tell the only merged stuff in 11.5.6.3 is moving locations of stuff and not save altering?

There's a bunch of translations on Crowdin nearing completion for #1551 which we could put in 11.6.5.3 maybe? I'll try to finish reviewing the crowdin stuff tomorrow and commit to 1551.

**Comment by krzychu124** [comment]
> As far as I can tell the only merged stuff in 11.5.6.3 is moving locations of stuff and not save altering?

And exactly that "moving locations" will break Kian's mods :)

**Review by chameleon-tbn — APPROVED** [review]
Lgtm

**Review by kianzarrin — APPROVED** [review]

**Pull request merged**
