### PR TITLE
no double crossing policy

### LINKED ISSUE #936: on a segment to segment transition only the smaller segment needs crossings.
Problem:
CS has too many redundant crossings and they are ugly. 
image

Solution:
A policy to auto-disable crossings on the ~~smaller~~ bigger segment.(or highway segment)
image

This also would be useful at the ground to elevated/tunnel connections.

### PR DESCRIPTION
**Pull request by kianzarrin**
zip file here: https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=single-crossing

fixes  #936 
see issue.

this policy is a nice complement to my hide TMPE crossings addon to prevent ugly crossings. has no important influence on pathfinding.

### Detailed functionality:
when this policy is active on a two-segment node with a junction flag then this is the default behavior:
1- if only one of the two segments has pedestrian lanes then only that one gets crossings.
2- if neither has pedestrian lanes then neither gets crossings.
3- otherwise, at the entrance to a tunnel or abridges, only the ground road gets crossings (EDIT: except for equal size segments).
4- otherwise, the segment smaller in size gets crossings
5- ~~otherwise, the segment with fewer car lanes gets crossings ~~
6- ~~otherwise, the segment with bigger pavement gets crossings~~
7- otherwise, (impossible to reach here without node controller mod) both segments get crossings.

### Change log:
- added option for no double crossings.
- added Crowdin key for the new option
- statically assign segment/node/lane buffers for a potential performance boost. these buffers Are ready at startup 😄.
- modified `GetDefaultPedestrianCrossingAllowed()` to implement the new functionality.

### Testing:
Don't forget to turn on the policy because it is off by default:
image

result:

image

### CODE REVIEW

**Comment by kianzarrin** [comment]
if the road size is the same, the transition is very small. should I get rid of:
> 5- otherwise, the segment with fewer car lanes gets crossings
> 6- otherwise, the segment with bigger pavement gets crossings

?

**Comment by kianzarrin** [comment]
I excluded same size segments so now it looks like this:
image

**Comment by thebugfixnet** [comment]
I agree from optical view it is the better to have both crossings at equal sized roads.

**Review by thebugfixnet — APPROVED** [review]
Ingame: Works for me as intended. Works also together with Node Controller. Code looks good. I did not find errors 👍

**Review by krzychu124 — APPROVED** [review]
Good 👍

**Pull request merged**
