### PR TITLE
use the new MoveIT integration interface

### PR DESCRIPTION
**Pull request by kianzarrin**
in PR #956 I provided support for MoveIT. much of the support code is inside the MoveIT mod. but macsergey has created a new MoveIT integration interface where none of mod-specific code resides inside MoveIT. using this interface TMPE will have more control over its data and can tackle problems internally as opposed to fixing move it.

I have also remove old TMPE integration from move it (https://github.com/Quboid/CS-MoveIt/pull/15)

test with this MoveIT:
[MoveIt.zip](https://github.com/CitiesSkylinesMods/TMPE/files/5193367/MoveIt.zip)

TMPE zip = https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=MoveIT-Integration

### CODE REVIEW

**Comment by thebugfixnet** [comment]
Downloaded the two files above + HideCrossings as with the first start i got an error message HideCrossings is missing.

But only Speed limits overlay work all others where either invisible or not clickable. So i could not select any junction with TM:PE to setup rules. Therefore i could not test any more.... Move It worked as intended. 

Only installed Mods:

Remove Crossings 3.0
Harmony
Move It from above
TM:PE from above

**Comment by kianzarrin** [comment]
@thebugfixnet if there are no problems can you please approve?

**Review by thebugfixnet — APPROVED** [review]
Ingame test only - works as expected if FPS-Booster is completely removed!

**Comment by kianzarrin** [comment]
> if FPS-Booster is completely removed!

@thebugfixnet if you had time it would be really helpful to know : does FPS booster work with 
A) TMPE LABS
B) TMPE master

**Comment by krzychu124** [comment]
> > if FPS-Booster is completely removed!
> 
> @thebugfixnet if you had time it would be really helpful to know : does FPS booster work with
> A) TMPE LABS
> B) TMPE master

I think @thebugfixnet was referring to latest _pre-Beta_ **FPS Booster** version (0.5.x) aka **The Last Fix** 😅  _(I've sent him that version 2 days ago)_, because _Closed Beta (0.4.1)_ is already on workshop for quite some time (still hidden).

Latest test version fixed a lot of old, long standing bugs, but due to character of changes (tool controller and Start method invocation order). Looks like it actually pushed the mod one step forward, but also few steps backward due to new bugs(or rather revealed new problems) in places which worked perfectly in previous versions _(that's why I didn't wanted to push it directly to workshop)_.

No need to worry, I will test everything before final release (and add some notes about compatibility), no need to do anything if this **PR** works without FPS Booster mod.
When it comes to testing I would turn off FPS Booster, just in case, it's not 100% compatible, so weird things are expected and I will be hard to guess which mod is the problem, especially combined with not fully tested latest build.

**Comment by thebugfixnet** [comment]
> > @thebugfixnet if you had time it would be really helpful to know : does FPS booster work with
> > A) TMPE LABS
> > B) TMPE master

Yes @kianzarrin this works.

> I think @thebugfixnet was referring to latest _pre-Beta_ **FPS Booster** version (0.5.x) aka **The Last Fix** 😅 _(I've sent him that version 2 days ago)_, because _Closed Beta (0.4.1)_ is already on workshop for quite some time (still hidden).

correct 😁

> When it comes to testing I would turn off FPS Booster, just in case, it's not 100% compatible, so weird things are expected and I will be hard to guess which mod is the problem, especially combined with not fully tested latest build.

thanks for the new version of Patch Loader @krzychu124 🤗

**Comment by thebugfixnet** [comment]
Now i was able to test: all works!

NC2.1.1 + TM:PE 11.5.2 STABLE + Move It 2.9 UNSTABLE + newest Version of FPS Booster!
Also it runs on a full modded game with over all 131 Mods!

**Comment by kianzarrin** [comment]
thanks to @thebugfixnet I detected and fixed a problem. I now copy the move it integration dll to mod folder.

**Comment by krzychu124** [comment]
Is `integration.dll` necessary to run it? I don't see it in zip from build 🤔

**Comment by kianzarrin** [comment]
> Is `integration.dll` necessary to run it? I don't see it in zip from build 🤔

Yes. nice catch!

**Comment by thebugfixnet** [comment]
It's not needed If you have the newest Move It Beta i would say...

**Comment by krzychu124** [comment]
Yeah, I assume it's just API lib and needs to be accessible at runtime, but what if user don't use `MoveIt` at all? 
Will it crash on load?

**Review by krzychu124 — APPROVED** [review]
Code looks good.
I've fixed missing integration dll in zip😉

**Pull request merged**
