### PR TITLE
Parking Restrictions tool - Lane highlighting

### LINKED ISSUE #702: Add lane highlight to Parking Restrictions tool
While not immediately obvious, a lane highlight still useful for this tool as it has an "apply to route" mode (`Shift+Click`) so good to highlight the affected route!

This is already done, by accident lol (see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/682#issuecomment-586504886)... just creating issue to track it separtely and ensure it appears in the change notes.

route mode

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #702 

parking lanes are highlighted:
- green=allowed red=not allowed.
- shift => blue color for all affected segments. (see issue for pictures)
- click => highlight is emboldened and turns orange (visual feedback)
- oneway roads have 2 parking lanes affected by the same GUI, I highlight both lanes here.

Scope:
The scope of this review is not to change the functionality of the parking tool, but rather provide visual feedback for what it already does.

Crowdin: I did not introduce the shift functionality but since it does not show in the tooltip keybind I decided to add it. Can anyone add the following crowdin key:
```
FILE: Menu.csv
"Tooltip.Keybinds:Parking restrictions"=>"[shift] apply changes to the whole road."
```

EDIT: fixed overlapping sprite overlays. see https://github.com/CitiesSkylinesMods/TMPE/pull/708#issuecomment-587823337

### CODE REVIEW

**Comment by kvakvs** [comment]
Do not rely on green/red/blue/orange, because there exist color blind people.
Of course you can still use color, but make green brighter, and red darker, and that should work well.

**Comment by kianzarrin** [comment]
> Do not rely on green/red/blue/orange, because there exist color blind people.
> Of course you can still use color, but make green brighter, and red darker, and that should work well.

The orange color is also embolden. blue color is supposed to be natural so it does not matter. as for green VS red I am not relying on it but rather its just a nice touch. Note that there is GUI sprite that shows the person the state of parking restriction.

**Comment by aubergine10** [comment]
The primary purpose of the lane highlights is to illustrate _what_ will be affected. The colours are just embelishments. The parking icons remain as the primary explanation of state, with the bar across the icon indicating in non-colour terms when parking is disabled (again, the fact that the bar is red is just an embelishment).

**Comment by aubergine10** [comment]
I might be doing something wrong, but I'm not seeing lane highligting of parking lanes when hovering (or clicking) lanes or icons:

image

**Comment by aubergine10** [comment]
I suspect the issue is to do with direction inversion happening in LHT maps as I just discovered in #709.

So the highlight is possibly working, just in the wrong direction or something.

**Comment by kianzarrin** [comment]
fixed LHT direction problem by using m_finalDirection.

**Comment by aubergine10** [comment]
It's working a bit now, but still have some issues (testing with LHT city).

👍 This one-lane one-way road with parking is working properly - and both parking lanes highlighted which is good!

image

⚠️ [Two-way with parking lanes](https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013) isn't working:

image

However, from the same roads pack linked above the surburban parking road works fine:

image

⚠️ Also from the same road pack, this asymmetric road with parking isn't working:

image

👍 Again, from same roads pack, this two-lane one-way with parking works properly:

image

Maybe there are issues with the road assets? If so, it would be good to log them to `TMPE.log` when game loads if possible (so asset authors can get some idea what they did wrong). Otherwise it might be bugs in PR.

**Comment by kianzarrin** [comment]
@aubergine10 
What do you mean by not working?
I did some testing with 2L2W road with master branch TMPE. banning parking on one side does not do anything while banning parking on the other side bans both sides. shift does not work.

Something weird going on. Not my fault but I will try to see If I can do something quick to help as part of this review ...

**Comment by kianzarrin** [comment]
Also annoying that the parking sprites overlap and you can click both of them at the same time:
Screenshot (557)

**Comment by aubergine10** [comment]
I don't think sprite overlap trick works for parking (I use it all the time on speed limits, but never had need to use it for parking so not sure).

The issues I reported above are about lane highlights however; sometimes the lane highlight isn't showing regardless of which sprite (or even overlap) is hovered.

I just realised all my screenshots had overlapping sprites; that's purely coincidental. The primary issue was the lack of lane highlights.

That being said, if hovering the overlap would show lane highlights for both sprites, and clicking overlap toggle both sets of parking lanes, that would be good for consistency with speed limtis tool.

**Comment by kianzarrin** [comment]
The direction of the parking is both. That is why TMPE gets confused. see https://github.com/CitiesSkylinesMods/TMPE/issues/516#issuecomment-587837970. 

> The issues I reported above are about lane highlights however; sometimes the lane highlight isn't showing regardless of which sprite (or even overlap) is hovered.

These roads are not supported by TMPE so the highlight behavior is undefined. I will print error message and #516 will handle the rest. we have to change the code fundamentally as part of #516 so its not worth dealing with `direction=both` right now. if anything it is a good feedback to the user that its not working!

**Comment by aubergine10** [comment]
Is `direction=both` an error on part of asset author though? For example, I suspect that would also be cause of #366 which I noticed some time ago (I think, with those same roads!). I know the asset author so I can ask him to change the setting, but what to?

**Comment by kianzarrin** [comment]
@kvakvs lets be easy about the camelCase_ VS camelCase in this review.  next time OK?

**Comment by aubergine10** [comment]
Discussion about `direction=both` on parking lanes moved to: #516

**Comment by aubergine10** [comment]
just noticed another commit; do you want me to retest?

**Comment by kianzarrin** [comment]
Wait! I fixed the overlapping sprite problem.

**Comment by kianzarrin** [comment]
Also added error message for bad lanes:
```
#if DEBUG
            if(DebugSwitch.BasicParkingAILog.Get() &&
                dir != NetInfo.Direction.Forward &&
                dir != NetInfo.Direction.Backward) {
                Log.Error($"bad direction: {dir} expected forward or backward");
            }
#endif
```

added wiki information here : https://github.com/CitiesSkylinesMods/TMPE/wiki/Notes-for-Asset-Creators#parking-lanes . when #516 is fixed this may no longer be required.

**Comment by kianzarrin** [comment]
@aubergine10 I have modified the code since you reviewed it last. I prevented the sprites of speed limit tool and parking tool from overlapping. Also added debug error for bad parking lanes.

**Comment by aubergine10** [comment]
>  I prevented the sprites of speed limit tool and parking tool from overlapping

Now I can't change both directions with one click any more. :(

**Comment by kianzarrin** [comment]
> @aubergine10  Now I can't change both directions with one click any more. :(

What you wanted them to overlap?!

**Comment by aubergine10** [comment]
It's only a minor thing, I can live without it. I think it will probably be better for most users to have them more separated like you have them in this PR, the main thing here is that the lanes are highlighted so IMO this PR is good to merge.

**Pull request merged**
