### PR TITLE
Split some options in to `GeneralTab_LocalisationGroup`

### PR DESCRIPTION
**Pull request by aubergine10**
Part of #1356 Phase 2.

- Localisation group of options now in its own class
- Also change mph option to `CheckboxOption`
- Will need testing at main menu (they are global options) and also in-game

Mod options which need testing:

* Lanugage selection
* MPH speeds option
* Speed limit icon theme

Additionally:

* Toggling mph button on speed limits palette in-game

Remaining groups will be handled via separate PRs.

Compiled mod for testing: [TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=refactor-general-tab-groups)

### CODE REVIEW

**Comment by aubergine10** [comment]
ready for review

**Review by kvakvs — APPROVED** [review]

**Comment by aubergine10** [comment]
@krzychu124 any feedback on this PR?

**Comment by krzychu124** [comment]
> @krzychu124 any feedback on this PR?

Looks ok, but I wanted to test in game (I was really absorbed with aircraft AI experiments yesterday 😄)

**Comment by aubergine10** [comment]
> Looks ok, but I wanted to test in game (I was really absorbed with aircraft AI experiments yesterday 😄)

I've got another PR coming after this one that will complete work on the `General` tab groups so can test in there if preferred?

**Review by krzychu124 — APPROVED** [review]
Fine

**Pull request merged**
