### PR TITLE
routing detector tool

### PR DESCRIPTION
**Pull request by kianzarrin**
image
it shows different lane transitions type with different colors. when you hover over target lane it shows list of all transitions to that lane.

TODO:
- [x] highlight target lanes when hovering over source lanes (not only when selecting it).

Future:
- backward mode (show backward transitions). #1537

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=ShowRoutings)

### CODE REVIEW

**Comment by aubergine10** [comment]
Is this just for dev/debug, or is it aimed at end-users?

**Review by aubergine10 — APPROVED** [review]
LGTM 👍 

I'd remove [TLM/TLM/UI/MainMenu/MainMenuPanel.cs](https://github.com/CitiesSkylinesMods/TMPE/pull/1534/files#diff-1bd7ebd791f75b498867bd415261f42ddc63489daf6b5e10ae974fcc9db32fd2) before merge.

As mentioned in previous comment, if it's debug only tool consider finding some existing texture to use for the button rather than adding new textures.

**Comment by kianzarrin** [comment]
@aubergine10 
> I'd remove [TLM/TLM/UI/MainMenu/MainMenuPanel.cs](https://github.com/CitiesSkylinesMods/TMPE/pull/1534/files#diff-1bd7ebd791f75b498867bd415261f42ddc63489daf6b5e10ae974fcc9db32fd2) before merge.

That is what I did. it was an empty file so I just deleted it :). that is why it is showing here.

>  I suggest just re-use existing icons

But then how can you tell the difference between different tools? these icons are not too big.

**Review by chameleon-tbn — APPROVED** [review]
lgtm

**Comment by krzychu124** [comment]
Select node, hover above an outgoing lane (any without white circle):

```cs
NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.UI.SubTools.RoutingDetector.RoutingDetectorTool.RenderActiveToolOverlay (.CameraInfo cameraInfo) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.TrafficManagerTool.RenderOverlayImpl (.CameraInfo cameraInfo) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
TrafficManager.Util.Shortcuts:LogException(Exception, Boolean)
TrafficManager.UI.TrafficManagerTool:RenderOverlayImpl(CameraInfo)
TrafficManager.UI.TrafficManagerTool:RenderOverlay(CameraInfo)
ToolManager:EndOverlayImpl(CameraInfo)
SimulationManagerBase`2:EndOverlay(CameraInfo)
ToolManager:IRenderableManager.EndOverlay(CameraInfo)
RenderManager:Managers_RenderOverlay(CameraInfo)
OverlayEffect:OnPostRender()
```

**Review by krzychu124 — APPROVED** [review]
A little bit over engineered _(you don't need anything more than just the lane end (laneID + nodeID) to get all its transitions)_ but whatever. 

It does what was advertised.

**Pull request merged**
