### PR TITLE
What's New in TM:PE 11.6.4.8 ?

### PR DESCRIPTION
**Pull request by aubergine10**
This is a bugfix release to solve an ancient bug in the pathfinder which prevents road vehicles spawning/delivering at lanes with vehicle restrictions.

- [Meta] TM:PE 11.6.4-hotfix-8
- [Meta] Bugfix for vehicle spawning/delivery on restricted lanes
- [Mod] Malware: We are treating all mods by Chaos/Holy Water (same person) as targeted malware #1389 #1388 (aubergine18)
- [Fixed] Allow vehicles to use vehicle-restricted lane when spawning/delivering #1381 #1380 #494 #85 (krzychu124)

### CODE REVIEW

**Comment by aubergine10** [comment]
#85 updated. Also updated bunch of wiki pages that referenced #85.

**Comment by aubergine10** [comment]
Should we add Chaos / Holy Water mods as incompatible?

**Comment by krzychu124** [comment]
I was thinking about it... I didn't test his redesigned version but looking in the log from #1388 it may not work correctly. If his harmony won't work then Next3 should be added as incompatible too, since that mod won't work with different Harmony because of his tripwires...

**Comment by krzychu124** [comment]
Ok, never mind, it's not a bug, it is a feature 😄

**Review by krzychu124 — APPROVED** [review]

**Pull request merged**
