### PR TITLE
Remove Speed limit manager's cache to handle Roads added after load.

### PR DESCRIPTION
**Pull request by kianzarrin**
I introduced `IsCustomisable()` method to check if NetInfo's speed limit can be customised on the go.

This should make speed limit work in asset editor. also useful for future mods that generate roads in game like Road generator or lane manager.

The cache does not provide any noticeable performance boost anyway.

EDIT: I did some more stuff:
- i renamed some fields/variables so that they would make more sense.
- old code used to store custom NetInfo speed limit in `customLaneSpeedLimits_` as well as the NetInfo itself. I removed the part that stores in NetInfo. so now reset should work.
- `#if SPEEDLIMIT` was left over code. I removed the macro and deleted part of the code that was never compiled.
- speed limit manager is now single point of truth for speeds even when Speed Limit Manager is turned off from the settings. the API already returns the vanilla speed limit if Speed Limit Manager is turned off.
------
Tests:
- [x] does it work on new roads in asset editor? 
yes:
image
- [x] can speed limit manager change car speeds in game?
- [ ] Custom NetInfo Speed Limit works: test failed
- [ ] Custom NetInfo Speed Limit can be reset
- [ ] Custom NetInfo Speed Limit persists.

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]
Code looks good
Did not test in game

**Review by krzychu124 — CHANGES_REQUESTED** [review]
Looking at tests you've done you are not aware that your changes introduces a bug and regression.
How you are going to reset modified speed limit for asset without using cache of default values?

Yes, once you apply asset speed limit there is no way to revert it on your build -> cache was not only used to speed up searching for asset speed limit but also for holding its default unmodified limit. It was created each time as a source of truth before applying customized TMPE speed limits on savegame load.

**Comment by aubergine10** [comment]
When default speeds are changed, does TMPE change the actual prefab? If so, it needs to revert those changes on level unload - eg. what happens if user enters asset editor to alter a road asset after those assets speed was changed in-game?

**Comment by kianzarrin** [comment]
> @krzychu124 How you are going to reset modified speed limit for asset without using cache of default values?

Haven't tested this but I think it just gets all the info it needs from the NetInfo. SpeedLimitManager does not modify the original netinfo so the info is always there.

let me test ...

**Comment by kianzarrin** [comment]
OK the test failed. this is a bug in the code. but I think I can reset without the cache.

**Comment by kianzarrin** [comment]
oh damn you are right I am modifying the original netinfo!

**Comment by kianzarrin** [comment]
test failed so I convert to draft for now.

**Comment by kianzarrin** [comment]
This is getting out of hand. I am breaking this up.

**Pull request closed without merging**
