### PR TITLE
Parking AI - thinking about a parking spot bugfix

### LINKED ISSUE #1655: Plaza and Pedestrian Zones have broke Realistic Parking Feature
### Steps to reproduce
1.  Create Ped Zone
2.  Zone Ped Zone
3.  Let Game run a bit before a car becomes utterly confused and breaks itself blocking up traffic for miles

### Screenshots?

https://gyazo.com/1139ef27e2209102f1ab6eb7d975f513

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #1655 

- added missing vehicle category for Parking AI pathfinding parameters, 
- ignore pedestrian zone roads when searching for driving-only passenger car path when Parking AI is enabled
- minor logging changes

Build [ZIP](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=bugfix/parking-ai-stuck-vehicles-pathfinding-bug)

### CODE REVIEW

**Comment by chameleon-tbn** [comment]
```NullReferenceException: Object reference not set to an instance of an object
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.get_tooltipBox () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIComponent.RefreshTooltip () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.Helpers.SliderOption.UpdateTooltip () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.Helpers.SliderOption.AddUI (UIHelperBase container) [0x00000] in <filename unknown>:0 
  at TrafficManager.State.GeneralTab_InterfaceGroup.AddUI (UIHelperBase tab) [0x00000] in <filename unknown>:0 
  at TrafficManager.State.GeneralTab.MakeSettings_General (TrafficManager.UI.Helpers.ExtUITabstrip tabStrip) [0x00000] in <filename unknown>:0 
  at TrafficManager.State.Options.MakeSettings (.UIHelper helper) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
TrafficManager.Util.Shortcuts:LogException(Exception, Boolean)
TrafficManager.State.Options:MakeSettings(UIHelper)
TrafficManager.Lifecycle.TrafficManagerMod:OnSettingsUI(UIHelper)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
OptionsMainPanel:OptionsMainPanel.AddUserMods_Patch2(OptionsMainPanel)
OptionsMainPanel:CreateCategories()
OptionsMainPanel:Awake()
UnityEngine.Object:Internal_CloneSingle(Object)
UnityEngine.Object:Instantiate(GameObject)
ColossalFramework.UI.UIDynamicPanels:Init(UIView)
ColossalFramework.UI.UIView:Awake()```

**Comment by krzychu124** [comment]
@kianzarrin did you fix it (@chameleon-tbn error) when replaced tooltip with value displayed in the label?

**Comment by kianzarrin** [comment]
what is driving only path?

**Comment by krzychu124** [comment]
> what is driving only path?

The last phase of the path -> when citizen reaches the last position of original path and found the parking spot - the request for path to parking spot has `DrivingOnly` flag since it has to be passenger car path directly from current position to the parking spot.

**Review by chameleon-tbn — APPROVED** [review]
code lgtm
ingame it seems to work as expected. not tested all edge cases that might be possible though.

**Pull request merged**
