### PR TITLE
Skip searching for best emergency lane for non-car vehicles

### PR DESCRIPTION
**Pull request by krzychu124**
Airport DLC introduced new case when some vehicle flags can be used. 
New usage can be found in `PassengerPlaneAI`  - combination of `Emergency` and `Emergency2` and `WaitingCargo` flags represents assignment of passenger aircraft to one of six Airlines (new DLC feature). Because of that some aircrafts are wasting time in simulation loop trying to find best lane. Since our impl. is using lane routing created by `RoutingManager` probably better lane cannot be found (we don't collect `Plane` lane transition data - although might be required in #1368) also missing `is vehicle Car check` is really old bug (2017) but was not used before in such way.

Removed redundant `if` tests, merged into one.
`isLargeVehicle`:
image

### CODE REVIEW

**Comment by aubergine10** [comment]
@krzychu124 There is also a vanilla property on vehicles (not sure when introduced): `VehicleInfo.m_isLargeVehicle;` - is that of any use to us?

**Comment by aubergine10** [comment]
Are there potentially other situations where we might run in to trouble with non-car vehicle having emergency flag set?

Looking at `MayFindBestLane()` - https://github.com/CitiesSkylinesMods/TMPE/blob/a69fb7983785a65e12a36f077ec0909d48bffb4d/TLM/TLM/Manager/Impl/VehicleBehaviorManager.cs#L3035

```csharp
if ((vehicleState.vehicleType & (ExtVehicleType.RoadVehicle & ~ExtVehicleType.Bus)) == ExtVehicleType.None) {
```
(btw, does that also need to filter out trolley bus?)

If you find all references to `ExtVehicleType.Emergency` and look for where that's being set, there may be some fringe cases where something like aircraft or fire/medic/police helicopter can get that type assigned? For example, `DetermineVehicleType()` or `DetermineVehicleTypeFromAIType()` - do they need to do some additional checks before returning `ExtVehicleType.Emergency`?

**Comment by krzychu124** [comment]
> Are there potentially other situations where we might run in to trouble with non-car vehicle having emergency flag set?
> RoadVehicle includes Emergency...

The thing is, before use of that method there is a check if vehicle is vanilla VehicleType `Car` :) 
2nd, `MayFindBestLane()` is testing our `ExtVehicleType`, and we assign Emergency only to emergency vehicles (with lights) and we don't manage any air vehicles -> `ExtVehicleType` is always `None`

**Review by aubergine10 — APPROVED** [review]
Built from source as RELEASE, tested in game breifly - didn't notice any issues.

LGTM 👍

**Comment by aubergine10** [comment]
Want me to prep a hotfix release for STABLE/TEST, or will this be going in 11.6.5.0 -> TEST?

**Comment by krzychu124** [comment]
Naah, we are going according to plan, so this will be in `11.6.5 TEST`

**Review by DaEgi01 — APPROVED** [review]

**Comment by DaEgi01** [comment]
I bet this can be written cleaner 
if (1)
  if (2)
    if (3)
      if (4)
but if it works, it works :D

**Pull request merged**
