### PR TITLE
Revise warning that was confusing users

### PR DESCRIPTION
**Pull request by aubergine10**
This PR ~~removes~~ revises the warning dlg about vehicles being despawned due to pathfinder update. Many users thought it was an _error_ (it's using warning prompt UI as we don't have any alternative at present), so ~~just removed the warning dlg for now~~ updated how it works (see https://github.com/CitiesSkylinesMods/TMPE/pull/1347#issuecomment-1028180904 ).

### CODE REVIEW

**Comment by aubergine10** [comment]
Updated - message is shown again, but only if there were actually vehicles to despan - this will prevenrt dlg appearing on new games, or cities that don't have that vehicle type. Also revised message to hopefully make it more obvious that it's not an error, but a fix for a past error.

**Comment by krzychu124** [comment]
> I was thinking of that but how do I know if they just started a new city?
> 
> Also, most people will be loading an existing city so they'll see the message and think it's an error. I had a look for "info"-styled CO UI but couldn't find anything yet.

OnLevelLoaded has parameter of load mode and I think the same info could be read via `SimulationManager` metadata or it's stored somewhere on the `SimulationManager` instance

**Comment by aubergine10** [comment]
Now checks `Mode` property to make sure it's not `NewGame` or `NewGameFromScenario`

(I assume `Mode` is the correct one to check vs. `LoadMode` ?)

**Comment by krzychu124** [comment]
> Updated - message is shown again, but only if there were actually vehicles to despan - this will prevenrt dlg appearing on new games, or cities that don't have that vehicle type. Also revised message to hopefully make it more obvious that it's not an error, but a fix for a past error.

Have you tried `MessageBoxPanel` instead of `ExceptionPanel`? It should have Ok button and nothing else.

**Comment by krzychu124** [comment]
Oh shit, I've never seen that vanilla dialog before😂 @aubergine10 is it good enough?

image

**Comment by aubergine10** [comment]
@krzychu124 Sorry for delay in replying...  yes that is significantly better!

**Comment by aubergine10** [comment]
Spotted a typo though - will send a commit shortly

**Comment by aubergine10** [comment]
done :)

**Comment by aubergine10** [comment]
Maybe add that dlg to the `Prompt` class as an `Info()` method?

**Review by krzychu124 — APPROVED** [review]

**Pull request merged**
