### PR TITLE
TTL minor UI improvements.

### PR DESCRIPTION
**Pull request by kianzarrin**
[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=TTL-UI-redundancy)

make sensitivity slider logarithmic. the `+-0.1` buttons are no longer necessary.
hide the slider when redundant
reorder change step criteria by importance.

### CODE REVIEW

**Comment by kianzarrin** [comment]
image

**Comment by kianzarrin** [comment]
@krzychu124 how can I change criteria text for all languages to this:
```
default (flow>wait)
priority (flow=0)
SOS(wait>0)
limiter (flow>0)
clearance (wait=0)
```
Is it just a crowdin change?

**Comment by kvakvs** [comment]
> @krzychu124 how can I change criteria text for all languages to this:
> 
> ```
> default (wait>flow)
> priority (flow=0)
> SOS (wait>0)
> limiter (flow>0)
> clearance (wait=0)
> ```
> 
> Is it just a crowdin change?

Now that would be confusing, because you made it shorter. Then maybe have a tooltip or popup or some other way to explain what these modes mean.

**Comment by kianzarrin** [comment]
> @kvakvs Now that would be confusing, because you made it shorter

how about ?
```
default: more waiting than driving (wait>flow)
priority: no one is driving (flow=0)
SOS: someone is waiting (wait>0)
limiter: some one is driving (flow>0)
clearance: no one is waiting (wait=0)
```

**Comment by kvakvs** [comment]
> > @kvakvs Now that would be confusing, because you made it shorter
> 
> how about ?
> 
> ```
> default: more waiting than driving (wait>flow)
> priority: no one is driving (flow=0)
> SOS: someone is waiting (wait>0)
> limiter: some one is driving (flow>0)
> clearance: no one is waiting (wait=0)
> ```

That doesn't add any new meaning, confusing even.
Why would you want to change the wording? I still like the existing better than the suggested. Is the existing wrong?

**Comment by chameleon-tbn** [comment]
works as expected... but i also do not see any value in changing the texts...

**Comment by kianzarrin** [comment]
OK no need to change the text then. lets review this WRT https://github.com/CitiesSkylinesMods/TMPE/pull/1670#issue-1402002755

**Review by chameleon-tbn — APPROVED** [review]
W/o the Text Change: Approved. :)

**Review by kvakvs — APPROVED** [review]

**Pull request merged**
