### PR TITLE
no lane arrows => no lane routings.

### PR DESCRIPTION
**Pull request by kianzarrin**
phase 1 of #1213

At junctions if lane has no arrows, it will have no lane transitions (except for relaxed transitions for SOS vehicles). 

applies to JUNCTIONS ONLY!!!!

in the next phase I use the lane connector tool so that we can remove lane transitions from track lanes too.

### CODE REVIEW

**Comment by kianzarrin** [comment]
works 
image

**Review by kvakvs — APPROVED** [review]

**Comment by Elesbaan70** [comment]
What is the use case for this? If I have to support this in the new routing logic, I have to understand what purpose it serves.

**Comment by Elesbaan70** [comment]
In this example, how is this industrial zone impacted? I'm assuming vehicles can't use the right lane because it has no outbound connection. Does this mean they'll connect from the middle lane? Will connections be possible at all?
image

**Review by Elesbaan70 — COMMENTED** [review]
I don't think this is a good idea, especially if it causes issues in the final segment of the arrowless lane. It's a hack, not a real solution for the use case.

This is not a dead end, and we should not call it that or use dead end symbols. Doing so would be very confusing.

It's basically a hack to make it look like vehicles are treating the lane as a **service lane**.

**Comment by kianzarrin** [comment]
@Elesbaan70 
I haven't hard-coded any names/symbols in this PR. That would be for the next phase where I will allow user to make lane to not go anywhere using lane connector tool. 

So what we call it is only a matter of release notes. I renamed the PR to avoid implying any name.

**Pull request closed without merging**
