### PR TITLE
clear all node rules

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes: #692
when no subtool is selected alt-click on a node and then press delete to clear all node rules (except TTL).

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=clear-node)

### CODE REVIEW

**Comment by kvakvs** [comment]
Tested and it works

Still confusing as i tried to apply this to lane connectors and it naturally did not work.
But is it possible to include lane connectors in this? Makes any sense?

**Comment by kianzarrin** [comment]
@kvakvs 
> Built and tested from branch and it works

did you use alt-click to select node and delete rules?

> Still confusing as i tried to apply this to lane connectors and it naturally did not change lane connectors.

Apply what?

> Problem: Holding CTRL shows existing speed limits, but then Speed limits overlay checks if CTRL is pressed, and shows speeds per lane. That's probably too much detail, need to make Speed limits overlay to ignore pressed Ctrl if in this mode?

Interesting observation. created #1680

**Comment by kvakvs** [comment]
> > Still confusing as i tried to apply this to lane connectors and it naturally did not change lane connectors.
> 
> Apply what? clearing node rules does clear lane connections for me. are you talking about clearing rules when selecting segment?

I was unable to clear lane connectors using this feature.

**Review by kvakvs — APPROVED** [review]

**Review by chameleon-tbn — APPROVED** [review]
Lgtm

**Pull request merged**
