### PR TITLE
Update localization files

### PR DESCRIPTION
**Pull request by aubergine10**
These are the translations from PR #1267 - notably they contain translations for the new speed limits UI.

Contributors: Chamëleon, MenschLennart, John Deehe, Skazov, AlexofCA, CrankyAnt, Иван Соколов, AduitSSH, John Lok Ho, DNSE, shg166, GiorgioHerbie, footbool, krzychu124, aubergine18, Dmytro Lytovchenko, Fizzy_LaFizz, Vladimír Krajč, alvaroer, Mahmoud Al Gammal, ipd, 田七不甜, vitalii201, 許景翔, Mehmet Ömer Tüzer, vicugna-pacos, kianzarrin, Mbyron26, Headspike, lennier3, kevinlin18, Ikki_di_Phoenix

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]
Nice

**Comment by krzychu124** [comment]
I noticed couple of unapproved tranlations on Crowdin 😕 Approving...

**Comment by krzychu124** [comment]
Done! You can rebuild translations and update PR

**Comment by aubergine10** [comment]
@krzychu124 I've done rebuild and download, but github is saying there's no changes since the last commit. :/ Which is odd cosidering there should be 40+ changes. Not sure what's happening there; think my git client is fubar again.

**Review by krzychu124 — APPROVED** [review]
👍 and as mentioned in different PR, I've added few translations, so update will be required before merge

**Comment by aubergine10** [comment]
translations updated, merging

**Pull request merged**
