### PR TITLE
What's New panel

### LINKED ISSUE #118: What's new!
I think it would be nice to show dialog after mod update (One time only like similar to that after game dlc release).

Currently user has no idea which workshop item was updated(or I am wrong 😄 )

I'm thinking about creating something like this to point main issues which where resolved and notify user about new content and other things.

What do you think?

### PR DESCRIPTION
**Pull request by krzychu124**
~Important!~
~Savegame created with this version won't be loadable by any previous version of the mod.~ 
**Improved backward/forward compatibility**

EDIT: Markup guide https://github.com/CitiesSkylinesMods/TMPE/wiki/Changelogs#whats-new-panel

Basic implementation of `What's new` panel.
- [x] read simplified markup from changelog file
- [x] automatically show panel at first open of the main menu in-game, depends on version of last shown panel.
- [x] save and load information about new What's New panel and TM:PE assembly version used.
- [x] added link-to-changelog support (optional)
- [x] updated changelogs to latest version

[Build (Stable) zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=whats-new-panel)
[Build (Test) zip](https://github.com/CitiesSkylinesMods/TMPE/files/7878225/TrafficManager_what.s_new_test_latest.zip)

Closes #118 

image

### CODE REVIEW

**Comment by aubergine10** [comment]
What's the plan with the title text?

Also, would it be worth adding text link in window footer that when clicked will open full changlog in browser?

**Comment by krzychu124** [comment]
> What's the plan with the title text?
> 
> Also, would it be worth adding text link in window footer that when clicked will open full changlog in browser?

Hmm, I will experiment with that.
I was thinking about extended or full changelogs for TEST, and simplified for Stable (good fit for link, but where should it direct?)

**Comment by krzychu124** [comment]
Changelogs updated, attached `Test` build since Appveyor build target is `Stable`

**Comment by krzychu124** [comment]
@aubergine10 
Since anchors to changelog are `<url(readme.md/changelog.md)>#tmpe-version-build-release_date_string` I can add new `[link]` element and make Title clickable
e.g.: 
- link: <https://github.com/CitiesSkylinesMods/TMPE/blob/master/CHANGELOG.md#tmpe-v1150-labs-07052020>
- markup: `[link] tmpe-v1150-labs-07052020`

What's do you think? We can add more features later 😉

**Comment by krzychu124** [comment]
WIP - latest version, 
- changelog of current version is bigger and text is white
- other changelogs are smaller and text is in shade of gray
- links should navigate to changelog entry (currently fake, I forgot to add latest Test releases to `Changelog.md`)

image

**Comment by krzychu124** [comment]
## Important!
### Savegame created with this version won't be loadable with any previous version of the mod.

**Comment by aubergine10** [comment]
The larger/brighter text for current version is a bit weird IMO.

image

Also, do we need to state `Traffic Manager` for each release note block? It's already in the title bar of the `What's new in TM:PE` window.

----

Instead of using `[*]` for list items, would it be better to use a keyword? For example, currently the `.txt` file contains stuff like this:

```
[*] New Speed Limits UI #1168
...
[*] fixed: regression: Auto TTL should set-up dedicated turning lanes properly #1242
...
```

Why not specify keyword for each item, eg:

```
[New] Speed Limits UI overhaul #1168
...
[Fixed] Auto TTL should set-up dedicated turning lanes properly #1242
...
```

The `New`, `Fixed`, `Updated`, `Removed` keywords could translate in to an enum, eg: `Dictionary<ItemType, string>`, the list can then be sorted by the enum to put `new` items top, etc. - that ensures ordering of items is consistent across releases, and would allow us to make release notes look something like this (ignore the grey line down the side I did the mockup in html and forgot to remove it):

image

* Background color:  `rgb(36,41,46)`
* Text color: `rgba(255,255,255,0.65)`
* Green (added/new): `rgb(40,167,69)`
* Blue (updated/improved): `rgb(3,102,214)`
* Red (removed): `rgb(215,58,73)`

**Comment by aubergine10** [comment]
Also, why are we storing the `what's new` version in the savegame rather than global xml? Does user need to see `what's new` each time they load a different city?

**Comment by krzychu124** [comment]
> Also, why are we storing the `what's new` version in the savegame rather than global xml? Does user need to see `what's new` each time they load a different city?

I'm rewriting that part to move version info outside current tmpe data container, so users and we will be able to load new savegame using older version of mod, even just for tests/performance comparison, but now when I think of it, that's not necessary. I was thinking about using it to notify about required actions after load like reset vehicles, cims etc.

Also, you probably noticed that `what's new` version is a bit different. 
Currently because of `AssemblyVersion` setting in `SharedAsssemblyInfo` (11.6.2.*) that `*` is dynamic and value is related to built time only. When I build version at about 1am, I'll get value `~2000`, but when built at 5pm it will be `~30000`. Day doesn't matter so I can't use version number to order entries or find current version which is PITA

**Comment by kvakvs** [comment]
If this is to show what's changed since savegame version, then last shown whats new should be stored in the savegame together with savegame version.
if this is to show what's changed since user updated TM:PE, then store last whatsnew shown version in global config

**Comment by krzychu124** [comment]
@aubergine10 cool mockup, I'll add some code to the parser and include suggestions 😉

**Comment by aubergine10** [comment]
With regards to savegame vs. global, I'm thinking about **youtubers who are regularly switching between different saves**... They probably only want to see that popup once per TM:PE version, not once per city.

**Comment by krzychu124** [comment]
> With regards to savegame vs. global, I'm thinking about **youtubers who are regularly switching between different saves**... They probably only want to see that popup once per TM:PE version, not once per city.

I agree. I'll move what's new version to global, but I want to leave assembly version (it will be under different key for compatibility reasons) - it might be useful to know which version (build) of mod was used to create savegame data in case of debugging weird serialization issues.

**Comment by aubergine10** [comment]
>  it might be useful to know which version (build) of mod was used to create savegame data in case of debugging weird serialization issues.

Yup, especially if we have workshop assets and/or move it exports made with a bad/old build we'll need some way to handle that with subsequent updates.

**Comment by aubergine10** [comment]
@krzychu124 FYI: I'm updating changelog.md to add in recent releases

**Comment by krzychu124** [comment]
> @krzychu124 FYI: I'm updating changelog.md to add in recent releases
> 
> EDIT: Just saw this in OP but didn't see any updates to changelog.md in the PR.... LMK if you want changelogs updating.
> 
> image

Heh, I edited that, it was about missing changelog that are displayed in What's new panel. Feel free to update Changelog.md etc.. 😉

**Comment by krzychu124** [comment]
@aubergine10 what do you think?

image

**Comment by aubergine10** [comment]
That looks freaking awesome.

Possible to do the bg color of the panel too (dark grey)?

**Comment by krzychu124** [comment]
> That looks freaking awesome.
> 
> Possible to do the bg color of the panel too (dark grey)?

Lighter, darker or perfect?
I've changed sprite to `GenericPanel` from `UnlockingPanel2` (used in IncompatibleModsDetector with blue tint) and tweaked font to slightly darker

1# Current `(36,41,46, 255)`
image

2# A bit lighter `(55,55,55,255)`
image

**Comment by aubergine10** [comment]
2nd one looks better, good call!

**Comment by aubergine10** [comment]
Are the `Fixed` etc lozenges using `GenericPanel` too? If not, could try that too as it would make the corner rounding a little tighter.

**Comment by krzychu124** [comment]
> Are the `Fixed` etc lozenges using `GenericPanel` too? If not, could try that too as it would make the corner rounding a little tighter.

Nope, they are `ButtonWhite` (because of no gradient).
Changed to `GenericPanel` and now they have pretty cool gradient, maybe too heavy? 🤔 

image

**Comment by aubergine10** [comment]
Hrm, it's made them a bit too dark IMO - is there some other bg texture with similar small corner radius but without the darkening effect?

**Comment by krzychu124** [comment]
> Hrm, it's made them a bit too dark IMO - is there some other bg texture with similar small corner radius but without the darkening effect?

I think I found something `TextFieldPanel` - grayish, so a bit darker, but I tweaked colors... 😄 

image

**Comment by aubergine10** [comment]
Looks good - can you commit those changes so I can test?

**Comment by aubergine10** [comment]
Is it OK if I tweak some of the text in changelogs and push a commit to this PR?

**Comment by krzychu124** [comment]
> Is it OK if I tweak some of the text in changelogs and push a commit to this PR?

Yeah, go ahead. I have nothing to add, everything seem to be working properly (maybe version check...?). 
If you notice something or want to tweak colors/position/text etc, no problem. 
Also would be nice to merge your #1267 and update position of What's new button in the options (it is also hooked into global config so it won't bother the user later in game)

**Comment by krzychu124** [comment]
@aubergine10 just realized... should be add build type to What's new header (stable/test/etc)?

**Comment by aubergine10** [comment]
> @aubergine10 just realized... should be add build type to What's new header (stable/test/etc)?

Yup - we can use the same string that's used for mod name in options panel as that contains version and STABLE/TEST as applicable.

**Comment by krzychu124** [comment]
Ok, tested loading savegame created with this version with use of `master` build. Loaded fine, without any issues.
Anyway I think we should add note if something go wrong because I'm pretty sure I saw that exception panel after load fail was commented out 🤔

**Comment by aubergine10** [comment]
Also, how much of a PITA would it be to parse the `#nnnn` issue references and wrap them in `<color>` tag to make them purple `rgb(111,66,193)` text so they stand out from the decriptive text? (alternatively the `<color>` tags could go in the .txt files so no need to do slow memalloc/gc of string parse/alteration on mod load)

**Comment by krzychu124** [comment]
Haha... I thought about that, even about adding them as links 😄 but this PR was meant to add `Basic implementation of What's new panel.` 😂

**Comment by aubergine10** [comment]
try that :)

**Review by aubergine10 — APPROVED** [review]

**Review by kvakvs — APPROVED** [review]
This is good

**Comment by aubergine10** [comment]
I've got some more changelog ammends to push to this PR for 11.6.3 release and also some earlier releases - when are you wanting to merge?

**Comment by aubergine10** [comment]
Also, I'd like to add that `[Stable]` keyword and combine both `.txt` files in to one. Stable (`RELEASE`) builds will only show versions with the `[Stable]` keyword.... OK if I submit that to this PR?

**Comment by aubergine10** [comment]
Implemented `[Stable]` keyword - now everything is in single `whats_new.txt` file and changelogs are displayed depending on which branch is built. Should make ongoing maintenance a bit easier.

Also simplified some text as per #1288

**Comment by aubergine10** [comment]
Unreleased version:

image

Released as TEST vs. STABLE:

image

Makes the purple pills look a bit grim though - wonder if there's a way to shrink version number a bit and then put `TEST`|`STABLE` as smaller text underneath version number?

**Comment by krzychu124** [comment]
Awesome! I was about to make some changes but you did all 😄 

> Makes the purple pills look a bit grim though - wonder if there's a way to shrink version number a bit and then put TEST|STABLE as smaller text underneath version number?

Quick uglu mockup?

> when are you wanting to merge?

if you want to add something we can wait. I see you've put #1267 into [11.6.3](https://github.com/CitiesSkylinesMods/TMPE/milestone/37) and added it to changelog as (pending), sooo I can wait😄

**Comment by krzychu124** [comment]
Oh, I noticed that "Not released yet" is not showing on Stable (no [Stable]) 😕 Only 11.5.2 is visible (has [Stable])🤔 

image

**Comment by aubergine10** [comment]
> Quick uglu mockup?

Something like this....?

image

But with version number similar to current size and `STABLE`/`TEST` in smaller text. Version number should be the primary focus visually.

> I see you've put #1267 into 11.6.3 and added it to changelog as (pending), sooo I can wait😄

It doesn't need to be in 11.6.3 - just shoved it in there for now so it wasn't in the main 11.6.0 milestone. Assuming there will be an 11.6.4 milestone I'll create that at move it in to there.

Would be better to get 11.6.3 out to TEST workshop asap so people can be testing it prior to the update for new DLC/CCP as you mentioned earlier.

> Oh, I noticed that "Not released yet" is not showing on Stable (no [Stable]) 😕 Only 11.5.2 is visible (has [Stable])🤔

When 11.6 stuff is released to STABLE, each of the 11.6 entries in the `whats_new.txt` will have `[Stable]` keyword added = they'll all appear in the stable `What's New` panel. Question then is do we want them all appearing in TEST builds, heh, but that can be sorted later (it's easy to filter).

BTW, I've now sorted all the 11.6 stuff in to relevant milestones on github. Going to do another check through everything to make sure nothing missed; there's still some PRs without milestone so I'll try and sort those too. Then I'll update all the changelogs, releases, etc., to ensure they are all consistent.

**Comment by krzychu124** [comment]
Done :) Changes pushed. I'll release it later today (as is 0:30am). If you want to do some tweaks, go ahead 😉 

image

**Comment by aubergine10** [comment]
I'll push a commit with updated `whats_new.txt` in an hour or three. 100% of PRs are now assigned correct release milestone and there were loads of things missing from the 11.6.0 release and few from subsequent releases too.

**Comment by aubergine10** [comment]
Updated `whats_new.txt` - see commit description for details.

---

Before I forget, I can't find the PR that fixes this issue anywhere:

```
[Fixed] Cannot setup timed traffic lights on monorail nodes #1160 PR??? (Adreos, krzychu124)
```

**Comment by aubergine10** [comment]
got another update to the .txt incoming in an hour or two - found some stuff that was listed as released in 11.6.0 was actually released in 11.5.1, also some issue numbers were wrong, etc.

**Comment by aubergine10** [comment]
done

**Pull request merged**
