### PR TITLE
V11.5.0

### PR DESCRIPTION
**Pull request by aubergine10**
- Update changelogs
    - Also added missing changlogs for STABLE update on 16th April 2020
    - Added missing workshop links to recent changelogs
- Bump mod version to 11.5.0

### CODE REVIEW

**Comment by kianzarrin** [comment]
> Fixed: NetSegment.CalculateCorner() exception for unsubbed roads (#883, #881)

Are we going to mention the bugs the we fixed before it was even released?

**Comment by kianzarrin** [comment]
> Added: Bulk customisation buttons on road info panel (#631, #691, #557, #542, #541, #539, #537)
Added: While toolbar visible, click road = show info panel; right-click = hide (#631, #822, #557, #29)

**Comment by aubergine10** [comment]
> Are we going to mention the bugs the we fixed before it was even released?

Yes, I try to mention everything, even if users haven't encountered it. We may be looking to see what changed some time in the future and having a full list in changelogs helps with that.

> people don't know what the following terms mean: road info panel means | Bulk customisation | toolbar visible

Some peopole call it 'toolbar' others call it 'menu'... the wiki generally refers to it as 'toolbar'. It's generally not a problem for that aspect of the UI.

Road info panel will be clarified with content in release announcements (reddit / discord). I'll upload proposed screenshots / vid to discord this evening(ish).

**Comment by aubergine10** [comment]
I've updated changelogs to include missing translation contirbutors list from 11.3.0 release:

```
- Updated: British translations (charlco, kvakvs, kian.zarrin) (#726)
- Updated: Chinese Simplified translations (wxf26054) (#726)
- Updated: Dutch translations (CaptainKlums) (#726)
- Updated: English translations (kian.zarrin, kvakvs) (#726)
- Updated: French translations (mjm92150, Stuart) (#726)
- Updated: German translations (eilmannhenrik, BanditBloodwyn, Rodirik, Cirez) (#726)
- Updated: Hungarian translations (szekely.david9) (#726)
- Updated: Italian translations (emiliomacchione, DelvecchioSimone) (#726)
- Updated: Korean translations (TwotoolusFLY_LSh.s, neinnew) (#726)
- Updated: Polish translations (krzychu1245, dom.kawula)
- Updated: Portuguese translations (BS_BlackScout) (#726)
- Updated: Russian translations (kvakvs) (#726)
- Updated: Turkish translations (revolter00, Koopr) (#726)
- Updated: Ukranian translations (kvakvs) (#726)
```

@krzychu124 Might want to update the changelog (description and changes tabs) in STABLE workshop page with that; I'll do same for LABS.

**Comment by kianzarrin** [comment]
>  I'll upload proposed screenshots / vid to discord this evening(ish).

Which time zone?

**Comment by kianzarrin** [comment]
The real name of the Panel that lets you change the roads name is "Road World Info Panel" 
Screenshot (1051)
Are you sure its a good idea to change the name of the panel to Road Info Panel? I know I called it that in that chat but I was being lazy because I did not want to write the whole name.


The Panel that lets you Adjust the road is called "Adjust Road" Tab 
Screenshot (1052)

which is contained in the "Traffic routes Info View Panel"
Screenshot (1053)

In the code I have contained by bulk adjust buttons in a UI that I have called Road Selection Panel. I suggest we use this name or something like bulk edit panel (assuming that we TMPE is not going to have a bulk edit tool in the future).

**Comment by aubergine10** [comment]
I doubt most users will know or care about the internal name of the UI component. I think maybe just "Road panel" or "Road info panel" is sufficient - it's the panel that appears when you click a road.

The green bar button on that panel is generally known as "adjust roads", which goes to Routes info view with the Adjust Roads tab selected. Althrough as discussed elsewhere, CO made some weird changes in SH update that now there can be multiple connected roads of same name but with different green bars defining their 'road routes'.

**Comment by kianzarrin** [comment]
I hope this will not be confused with wiki because there I have use the name Road Selection Panel to refer to the panel containing my buttons but I doubt people can tell the difference.

**Comment by kianzarrin** [comment]
> Yes, I try to mention everything, even if users haven't encountered it. We may be looking to see what changed some time in the future and having a full list in changelogs helps with that.

I hope that this does not confuse users.

**Pull request merged**
