### PR TITLE
Managed dll locations for EA Origin builds

### PR DESCRIPTION
**Pull request by DannyDannyDan**
Update build guide to mention correct reference paths to managed dlls for users who run the game via EA Origin game portal.

### CODE REVIEW

**Comment by aubergine10** [comment]
@DannyDannyDan Thanks for the contribution! Reviewing...

----

@kianzarrin Can you update our reference hint paths to add compatibility for devs building on EA Origin deployed Cities: Skylines?

`\Program Files (x86)\Origin Games\Cities Skylines\Cities_Data\Managed`

Likely registry keys to find non-default install locations for Origin: https://www.regfiles.net/registry/origin-registry   (⚠️ article > 2 years old)

----

@DannyDannyDan Can you check your registry to see if those registry keys above still exist? We'll add hint paths based on default location, and if not found there we'll scan registry keys to find a location and try that as fallback.

**Comment by aubergine10** [comment]
Specifically this registry key looks promising:

```registry
[HKEY_LOCAL_MACHINE\SOFTWARE\Electronic Arts\EA Core]
"EADM6InstallDir"="C:\\Program Files\\Origin"
```

**Comment by kianzarrin** [comment]
> @aubergine10 Can you update our reference hint paths to add compatibility for devs building on EA Origin deployed Cities: Skylines?

sure  I just have a few things I want to get done first. The code is a piece of cake but updating all those freaking sub-modules is time consuming! lets create an issue for it.

**Comment by kianzarrin** [comment]
@DannyDannyDan if you have origin can you please search your registry  for `Origin Games` and `Cities Skylines`
Does origin allow installation in different location?

**Comment by DannyDannyDan** [comment]
Looking...

**Comment by DannyDannyDan** [comment]
[Origin Cities Skylines registry search.zip](https://github.com/CitiesSkylinesMods/TMPE/files/4269702/Origin.Cities.Skylines.registry.search.zip)

**Comment by DannyDannyDan** [comment]
> 
> 
> @DannyDannyDan Thanks for the contribution! Reviewing...
> 
> @kianzarrin Can you update our reference hint paths to add compatibility for devs building on EA Origin deployed Cities: Skylines?
> 
> `\Program Files (x86)\Origin Games\Cities Skylines\Cities_Data\Managed`
> 
> Likely registry keys to find non-default install locations for Origin: https://www.regfiles.net/registry/origin-registry (⚠️ article > 2 years old)
> 
> @DannyDannyDan Can you check your registry to see if those registry keys above still exist? We'll add hint paths based on default location, and if not found there we'll scan registry keys to find a location and try that as fallback.

All of the registry keys in that link exist,

**Comment by aubergine10** [comment]
Created issue #760 to track task of adding Origin-specific reference hint paths.

**Pull request merged**
