### PR TITLE
trams/trains are blocked by their own trailer

### LINKED ISSUE #1572: trams/trains are blocked by their own trailer.
This is also a vanilla problem:
when segment is updated or TMPE rules are updated, the leading vehicle will go a little bit backwards (because it will reset simulation speed data) while the trailers will not (they will stop immediately). if the vehicle is going fast enough it can get behind its own trailer and get blocked by it.

https://user-images.githubusercontent.com/26344691/168418804-592f2b8c-1d33-4079-a765-a7cde4bcc51c.mp4

https://cdn.discordapp.com/attachments/545066674605391882/965713435935506512/2022-04-18_23-39-26.mkv

Solutions:
- leading vehicle must ignore its own trailer in collision checks.
- trailers must also reset their simulation frame data.

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #1572. see #1572
code idea comes from `CarAI.InvalidPath()`

I set all target positions to `m_targetPos2` because `m_targetPos3` is too far away and train can go out of rail on curved segment.
`m_targetPos0 or 1` are too close and causes the train to go backward and get stuck.

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=trailerfix2)

### CODE REVIEW

**Review by chameleon-tbn — COMMENTED** [review]
lgtm

**Review by chameleon-tbn — APPROVED** [review]

**Comment by krzychu124** [comment]
@kianzarrin is there any difference if you do it like e.g. CarAI (update all targets with `targetPos3` then reset its `w`) instead of the other way around?

**Comment by kianzarrin** [comment]
> @krzychu124  is there any difference if you do it like e.g. CarAI (update all targets with `targetPos3` then reset its `w`) instead of the other way around?

No. The W component is discarded (I don't know why its there maybe for future proofing?) in `StartPathFind()`. The reset of the target pos fields are also discarded. it won't matter what you set them to. you just need to make sure that the one that is used (targetPos3 in case of car, targetPos0 in case of train/tram) is far enough. 

I reset them the w for all of because that makes more sense. maybe it helps in future. who ever wrote that code was probably not at his best when he wrote it which is why there are errors inside it.

or maybe I should just not bother with w?

**Comment by krzychu124** [comment]
> No. The W component is discarded

Noo, `w` is discarded but only for `targetPos3`. See `red` are copies from original targetPos3 (x,y,z,w) and **then** `w` is reset to 0f, but only for that one. 

`w` is speed component in the lane units value (1u -> 8f -> 50km/h)

They are all structs so it should behave slightly different if you reset speed first and copy instead of copy then reset speed for last target that's why I asked.

image

**Review by krzychu124 — APPROVED** [review]

**Pull request merged**
