### PR TITLE
What's New in TM:PE 11.6.5.1 ?

### PR DESCRIPTION
**Pull request by aubergine10**
This update adds two new features, overhauls mod options code, and improves modding API.

- [New] `Disable Despawn` feature now has vehicle-type filters #1441 #1434 (Marconius6, lokpro, krzychu124)
- [New] Timed Traffic Lights now available in Map and Scenario editors #1425 #959 (aubergine18)
- [Mod] API: Mods can now use TMPE.API.dll alone, without referencing TrafficManager.dll #1448 (kianzarrin)
- [Mod] API: TM:PE Harmony ID changed from `de.viathinksoft.tmpe` to `me.tmpe` #1456 #897 (krzychu124)
- [Mod] Update: UUI version 2.2.1 via NuGet #1442 (kianzarrin)
- [Fixed] `NullReferenceException` if version in global config is not set #1443 (krzychu124)
- [Fixed] UI windows/overlays not consuming mouse events #1443 #934 #749 (somethingstarted, MacSergey, krzychu124)
- [Fixed] Missing textures in Scenario Editor #1451 #1450 #1449 (krzychu124, kianzarrin)
- [Fixed] Memory leak when closing Lane Arrows panels #1451 (krzychu124)
- [Fixed] Features missing if starting new game after using asset editor #1425 #1423 #1422 (NateNate60, aubergine18)
- [Fixed] Typo in notifier method name #1440 (aubergine18)
- [Updated] Use game-defined elevation keymapping to select under/over-ground views #1454 #1326 (krzychu124)
- [Updated] Add/update UI helpers for use in mod options #1431 #1430 #1424 #1419 (aubergine18)
- [Updated] Refactoring mod options #1464 #1455 #1435 #1432 #1422 #1411 #1416 #1356 #1279 #62 (aubergine18)
- [Updated] Replaced `Overlay Transparency` with `Overlay Opacity` #1432 #1268 (aubergine18)
- [Updated] Minimum GUI/Overlay opacity limited to 10% #1432 #1409 (KHY-afk, aubergine18)
- [Updated] Use `Prompt.Error` for error message display #1445 (aubergine18)
- [Updated] Better handling of `KeyNotFound` exception when copying segments #1453 (kianzarrin)
- [Updated] Improved mod option lifecycle for game/editors #1452 #1449 #1425 (aubergine18)
- [Updated] Extension for managed-type `vehicleId` to `ExtVehicleType` #1444 (aubergine18)
- [Updated] Simplify Harmony patching for Reversible Tram AI #1457 (kianzarrin)
- [Updated] Un-invert `Options.disableDespawning` data byte (aubergine18, kianzarrin)
- [Updated] `MayPublishSegmentChanges()` moved to `TMPELifecycle`; API unaffected #1432 (aubergine18)
- [Updated] `Buses may ignore lane arrows` enabled by default when starting new city #1455 (aubergine18)
- [Removed] Obsolete gamebridge stuff from build script #1436 (aubergine18)
- [Removed] "Apply AI changes right away" option; changes always applied immediately now #1432 (aubergine18, kvakvs)

### CODE REVIEW

**Comment by krzychu124** [comment]
Is there a chance to collect pending PRs to release it tomorrow or at Sunday?

**Comment by aubergine10** [comment]
Added pending PRs, updated changelog and readme too.

**Comment by aubergine10** [comment]
Bumped game ver for recent patch: https://steamcommunity.com/games/255710/announcements/detail/3103548062078262527

**Review by kvakvs — APPROVED** [review]

**Comment by aubergine10** [comment]
Ready for release. The few green icons in OP are just ongoing work; everything for this PR is now merged.

**Comment by aubergine10** [comment]
Just waiting on #1464 now; if the altered bus lane arrows option is to be kept (was off by default, now on by default) should that be mentioned in changelog?

**Comment by aubergine10** [comment]
@krzychu124 All PRs merged, ready for release (again heh)

**Review by krzychu124 — APPROVED** [review]

**Comment by krzychu124** [comment]
I'll update workshop when I wake up :)

**Comment by krzychu124** [comment]
@aubergine10 why all features at Maintenance tab are disabled when I start new game??

**Comment by krzychu124** [comment]
I'm also 99% sure that you've added change to the localization reading method to include TEST for translation key stripping if no translation is added (like it does for Stable). What is going on??

image

**Comment by krzychu124** [comment]
plus... it looks like scrollbar is not visible and not working at Keybinds tab ☹️

**Comment by krzychu124** [comment]
Something is broken (dlc map, new game, latest `master`)... [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/8239845/TMPE.log)

**Pull request merged**
