### PR TITLE
Amend #851: Add missing strings and write config on toggle OSD

### PR DESCRIPTION
**Pull request by kvakvs**
* Missing strings for mode descriptions added
* OSD toggle now saves global config

### CODE REVIEW

**Comment by aubergine10** [comment]
Looks like there's some new translations in there too - who contributed those? (so we can mention on changelog)

**Comment by kvakvs** [comment]
Czech translation, entirely new, but the language code is not added to the game UI yet (out of scope of this amendment)
Contributed by Kuba Kukuč Pátek (user: jakubpatek)

**Comment by aubergine10** [comment]
So, I added `cz` to the language codes dictionary:

image

In-game, changed the language and noticed this (note top two items of list are same):

image

**Comment by aubergine10** [comment]
Slight scope creep, but hopefully quick to change... Parking icon is dimmer than nearby vehicle restriction and speed limits icons; if memory serves this is intentional in its unselected state.

image

However, when hovering (as the mouse was doing in image above) could it be given full opacity? Otherwise it feels like it's disabled (despite the blue background color on hover). Having the foreground icon change as well would provide more tactile feedback for the button.

**Comment by kvakvs** [comment]
A problem 1: The sprites for Parking Restrictions normal and active look correct brightness. The skin setup for PR button is exact same as for example SpeedLimits button, so should be correct too. Now why exactly that button looks differently?

A problem 2: Child of a window cannot be more opaque than its parent.

**Comment by aubergine10** [comment]
Ooh, I think I found a bug.... Steps to reproduce (not sure if all steps are required, but just in case):

1. From main menu I changed language to Czech to test the options screen looked ok
2. Changed back to Game Language (English, in my case)
3. Loaded my city
4. Tested the key/mouse hints (in English)
5. Decided to test them in Czech: Pause menu > TMPE mod options > Czech language

First, with lane arrow tool selected, clicking the `?` button does not toggle hints panel:

image

Then I went to lane connector tool to see if that would work:

image

Note the `?` at this point isn't remembering state; it keeps resetting to "off".

So now I try going back to Lane Arrows tool:

image

First click does nothing (note the darker blue background indicating the lane arrows tool should be active, but also the dark blue background indicating lane connectors tool is also still active):

image

> Note: This specific bit of state fail seems to only occur if I click the `?` button while in the lane connector tool (I've not tested all possible combinations).

A second click now removes (lane connector) node select circles but still has lane connector tool selected:

image

Note, however, that segments are hovering when I hover them - indicating that the Lane Arrows tool has input focus:

image

(note also button states in that image above)

A few more clicks of the lane arrows button and now both buttons are disabled and I'm getting green road selections (indicating that the 'mass edit' tool has input focus):

image

By this point it is very diffcult to get the lane arrows button selecting at all, although every so often it does select:

image

Logs:

* [AutoRepair.log](https://github.com/CitiesSkylinesMods/TMPE/files/4519213/AutoRepair.log)
* [DuplicateAssemblyScanner.log](https://github.com/CitiesSkylinesMods/TMPE/files/4519214/DuplicateAssemblyScanner.log)
* [output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4519215/output_log.txt) - plenty of exceptions in there
* [SequenceLogger.log](https://github.com/CitiesSkylinesMods/TMPE/files/4519216/SequenceLogger.log)
* [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4519217/TMPE.log)

**Comment by aubergine10** [comment]
Regarding comment above, I suspect we will need to reset fsm's of buttons/etc when language changes?

**Comment by kvakvs** [comment]
@aubergine10  i had similar problem before, and it was related to me trying to set visible of some control to false during input processing. If i don't try to hide anything, it returns to working state. That's when i was asking whether input processing is another thread or some other unsafe situation
Possibly related to me detaching the hint controls when refreshing the hint panel. There was no easy way to delete them cleanly within the same frame so i started detaching them, i.e. resetting their parent, and they're sad when they lose parent UIView.

**Comment by aubergine10** [comment]
I think Forest Brush also removes UI elements when not displayed and from vague memory (it was eitehr boformer or TPB) ran in to some similar issues - but they found some way to resolve them. Might be worth having chat with boformer on skylines.code.

**Comment by kvakvs** [comment]
Pushed one line change, not detaching controls now. Can you verify if anything changed?
It should get rid of that `UIView is null` crash but it may affect layout of the hint panel "ghosting" empty spaces where previous generation controls were placed.

**Comment by aubergine10** [comment]
Just reporting this before I forget... These tooltips seem swaped (should be incoming first, then outgoing):

image

Tooltip `Click outgoing lane to connect to something` is confusing, because user is clicking lane entering the junction (not leaving, a.k.a. "outgoing").
image

**Comment by aubergine10** [comment]
^ Edited comment above (in case git notifications already arrived with old text)

**Comment by aubergine10** [comment]
I can confirm the null reference / fsm bugs are fixed! (ref: https://github.com/CitiesSkylinesMods/TMPE/pull/858#issuecomment-618064756)

**Comment by kvakvs** [comment]
The text is correct. It says exactly what i wanted to say.
Outgoing lane (traffic source)
connects to
Incoming lane (traffic destination).

Although now if i think the wording might be wrong. If we take the junction as a reference point we take a lane incoming to the junction/node, and then lane outgoing to redirect the flow.

**Comment by aubergine10** [comment]
Can't remember if you wanted a reminder in this PR or next one, but just in case:

image

Display hint about being able to click road for the mass edit tools? Something like:

"Select a tool to use, or click a road for mass-edit options"  ...?

**Comment by kvakvs** [comment]
We can add that as one independent and small PR.
Is that always to be displayed when no tool is active?

**Comment by aubergine10** [comment]
> If we take the junction as a reference point we take a lane incoming to the junction/node, and then lane outgoing to redirect the flow. (ref: https://github.com/CitiesSkylinesMods/TMPE/pull/858#issuecomment-618094689)

Yup, it's always been the junction that we used as reference point, because the user has to select the junction first, so subseqent actions are in relation to the junction.

So they start by selecting incoming lane they want to edit, then they click outgoing lanes to toggle connection to the current incoming lane.

It's important that we mention 'toggle connection' (or 'add/remove connection'?) in the 'choose outgoing lanes' stage of the task, as there is always some users asking how to remove a connection after they've added it.

> We can add that as one independent and small PR. (ref: https://github.com/CitiesSkylinesMods/TMPE/pull/858#issuecomment-618096966)

Ok.

> Is that always to be displayed when no tool is active? (ref: https://github.com/CitiesSkylinesMods/TMPE/pull/858#issuecomment-618096966)

Yes, it would be, which could be confusing hence the mention of "Select a tool to use" at the start of of the hint text (there might be better alternate wording but I couldn't think of any yet).

The mass edit thing is weird to explain but feels intuitive once you know how to use it. Unlike all other tools, the "button" for the mass edit is the road itself.

At some later date we could potentially add other icons to the road world info panel for performing other tasks; eg. speed limit icon would switch to the speed limit tool with that road already selected. We could further extend by allowing node selection, so I could just select node to see info panel and then click junction restrictions icon to jump in to that tool with the node already selected. But that's stuff to ponder at later date.

**Comment by kvakvs** [comment]
@aubergine10 I suggest introducing the user to the concept of a named road, or street, and integrate it more with all relevant tools. For example encourage users holding shift more, and seeing the streets more often. This will create awareness what the streets are, and then the hint will begin making sense.

**Comment by kvakvs** [comment]
@aubergine10 Please suggest exact wording change for the modes, and let's get done with this PR :)

**Comment by aubergine10** [comment]
I'll update later tonight (currently wading through mod checker stuff which will take another few hours).

**Comment by aubergine10** [comment]
Default interaction hints...

#### Mass edit

When toolbar visible, but no tool selected (green road select "mass edit" can be used):

> Choose a tool to use, or click a road

#### Lane arrows

When lane arrows tool active, but nothing selected:

> Choose a segment to edit

#### Lane connectors

When lane connector tool active, but nothing selected:

> Choose a node or junction to edit

When a node/junction is selected:

> Choose which lane to edit

When an incoming (lane entering junction) is selected:

> Click target lanes to toggle connections

**Comment by kvakvs** [comment]
Modified the strings and updated the English translations to what is suggested above.
Other translations which I can do will wait until final approval arrives.
The bug with "UIVIew is null" is reappearing sometimes. I am worried.

**Comment by kvakvs** [comment]
Idle hint added now
Avoiding to hide the panel, instead empty panel is made 0% opaque and it should help.

**Pull request merged**
