### PR TITLE
Refactor OptionsGeneralTab.cs

### PR DESCRIPTION
**Pull request by aubergine10**
Updates #1262, #62

The `General` settings tab was getting a bit cluttered (visually), especially with new options for speed limits UI. This PR does some refactoring to:

- Collate related options in to UI groups
- Move bulky option code in to methods
- Clarify intent in `MakeSettings_General`
- Add Crowdin button -> https://crowdin.com/project/tmpe
- Add Localisation guide button -> https://github.com/CitiesSkylinesMods/TMPE/wiki/Localisation

Todo:

- [x] Locale keys for new UI groups

Translators:

* Chamëleon, MenschLennart, John Deehe, Skazov, AlexofCA, CrankyAnt, Иван Соколов, AduitSSH, John Lok Ho, DNSE, shg166, GiorgioHerbie, footbool, krzychu124, aubergine18, Dmytro Lytovchenko, Fizzy_LaFizz, Vladimír Krajč, alvaroer, Mahmoud Al Gammal, ipd, 田七不甜, vitalii201, 許景翔, Mehmet Ömer Tüzer, vicugna-pacos, kianzarrin, Mbyron26, Headspike, lennier3, kevinlin18, Ikki_di_Phoenix

Not in this PR:

- Remove MPH vs. km/h option & allow road sign theme to determine that ( see #1262 , #1221 )
- Remove advisor tutorial option ( see #1240 )
- Standardise opacity vs. transparency (see #1268 )

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=refactor-general-settings-1262)

### CODE REVIEW

**Comment by aubergine10** [comment]
image
image

**Comment by kvakvs** [comment]
We changed window from transparency to opacity
Why not we also change overlay transparency to opacity? There was a helper class made for that `U.UOpacityValue`

**Comment by kvakvs** [comment]
Instead of colorizing maybe try increasing font size/scale for heading labels?

**Comment by kvakvs** [comment]
Let's leave info text for a second pass of this work.
I really want to add extra help to each option, a hint like in the screenshots, or multiline tooltip, or click ? to toggle hints, possibly even a popup page with some illustrations or something like that, or a link to the Wiki page which will open Steam or system browser.

**Comment by aubergine10** [comment]
> Let's leave info text for a second pass of this work, not now.

Yup, once I get the translation keys sorted that should suffice for this PR. How is that handled btw?

> possibly even a popup page with some illustrations or something like that, or a link to the Wiki page which will open Steam or system browser.

Yup, see: #733

> We changed window from transparency to opacity
> Why not we also change overlay transparency to opacity? There was a helper class made for that `U.UOpacityValue`

Yup, it will be much better having them both use same approach. What needs to change in the code? Is it just the display/setting of the value, or will it require updates to tool UI (thus separate PR)?

**Comment by kvakvs** [comment]
Translations are handled via Crowdin.
You click Content -> Strings, select CSV file where it will be added, and add the translation keys
Then you click the project main page, where the languages are, click English and in the ... menu on the right click Translate
Translated keys then need to be approved, there's a separate editor mode for approvals, but you can also self-approve from the translation UI by clicking ✔ on the translation you've just added.
When done translating into all languages you know, in the main project page there's big green build&download button. The contents of that zip go into TLM/TLM/Resources/Translations, as is unmodified.

**Comment by kvakvs** [comment]
> Yup, it will be much better having them both use same approach. What needs to change in the code? Is it just the display/setting of the value, or will it require updates to tool UI (thus separate PR)?
The opacity is 1.0f-transparency so it should be straightforward change to the tools using this value.
Separate ticket is fine

**Comment by krzychu124** [comment]
> The group heading text is already a little bolder than normal option text. IIRC, with vanilla font manager, different text sizes result in additional textures being created (I think that's one of the things FBS Booster mod tackles with its improved fonts system?). Also, larger headings = more vert scrolling.

Nope. Every font used to render text in game has own, separate texture for characters (res. max 4096x4096). 

When you use non standard font size (not the one already used) game will request all new characters using the texture of selected font. 

Unity starts filling texture font from 256x256, then doubles width or height to resize - all characters will get requested again in that case which usually results in "alien characters" rendered until next deep update of text component because of UI is reading old glyph positions using a new recreated texture as a lookup table (glyph position is not guaranteed between font texture resizes)

**Comment by aubergine10** [comment]
Ready for review.

**Comment by aubergine10** [comment]
Is it possible to put buttons side by side?

image

**Comment by kvakvs** [comment]
You can check how its done in Keybinds component in `KeybindSettingsBase.AddAlternateKeybindUI` which creates a panel with horizontal autolayout then plops 2 components into it.

**Comment by kianzarrin** [comment]
I think if you want to change the code it would be nice to do so properly and use:
https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/UI/Helpers/CheckboxOption.cs

If there is no duplicate code fixing this would be easier https://github.com/CitiesSkylinesMods/TMPE/issues/562

**Comment by aubergine10** [comment]
Yup, I'd like to do that - maybe as phase 2. At the moment my focus was just on getting the options in to coherent sections in the UI, and slipped in those buttons for translators (I think I'll leave them as they are for now until more translations come in - eg. text might get too long to have them side by side).

I'll add note on `ChecboxOption` and the button layout to the parent issue #1262

**Comment by krzychu124** [comment]
> I think if you want to change the code it would be nice to do so properly and use: https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/TLM/UI/Helpers/CheckboxOption.cs
> 
> If there is no duplicate code fixing this would be easier #562

Yes but remember to use `nameof` when passing field names so our IDE's won't warn about unused fields (they are used but previously were called by `string` name instead of `nameof`). I think that @kvakvs fixed that in some places, don't remember if everything (I think so)

**Comment by aubergine10** [comment]
Ok, looking at the `CheckboxOption` stuff there's blockers to using it on the `General` tab:

1. Most checkboxes on General tab are stored in `GlobalConfig`, although strangely some also have fields in the main `Options` but I struggle to find if there's any crossover between the two.
2. Some of the translations are from differnt csv files, eg. `Translation.SpeedLimits`

As such I think it's best to keep this PR as basic cosmetic changes and tackle the architectural changes in a later PR.

**Comment by krzychu124** [comment]
> Most checkboxes on General tab are stored in GlobalConfig, although strangely some also have fields in the main Options but I struggle to find if there's any crossover between the two.

OK... because `nameof()` value points to itself e.g.: https://github.com/CitiesSkylinesMods/TMPE/blob/23ee4b2e0c1f90e994296ccaeff82ab0854eb3ed/TLM/TLM/State/OptionsTabs/OptionsVehicleRestrictionsTab.cs#L27-L28

It should be `new CheckboxOption(nameof(Options.NoDoubleCrossings))`, same for `DedicatedTurningLanes` 😉 

> As such I think it's best to keep this PR as basic cosmetic changes and tackle the architectural changes in a later PR.

Cool 👍

**Comment by kianzarrin** [comment]
@aubergine10 
>  strangely some also have fields in the main Options but I struggle to find if there's any crossover between the two.

what is crossover?

> Most checkboxes on General tab are stored in GlobalConfig | Some of the translations are from differnt csv files

fair enough

maybe we can define a boolean `IsGlobal` in `SerializableUIOptionBase` that would change the serialization behavior. but if you think its out of scope that is also fair.

> Some of the translations are from differnt csv files

Maybe we should move them to options csv file for consistency.

**Comment by aubergine10** [comment]
> what is crossover?

Ah, ingore that - I'd missed an event handler but found it now...

Example: Go look at `GlobalConfig.Instance.Main.ScanForKnownIncompatibleModsAtStartup` vs. `Options.scanForKnownIncompatibleModsEnabled` and how they both interact.

There should always be a single source of truth, regardless of where setting is persisted. But in example above there's two options with different names in different places being synchronised in a confusing way and I have no idea why. It's made all the more perplexing as that option isn't save-specific; it has no relevance in-game.

> maybe we can define a boolean IsGlobal in SerializableUIOptionBase that would change the serialization behavior.

Some settings update both `State.Options` and also `State.GlobalConfig`, some just one or the other. A key question is if something is `GlobalConfig` only, why would there also an entry in `Options`? `ScanForKnownIncompatibleModsAtStartup` being a good example.

> > Some of the translations are from differnt csv files

> Maybe we should move them to options csv file for consistency.

First I'd need to know why it's done that way currently.

Notable example is the `GlobalConfig.Instance.Main.DisplaySpeedLimitsMph` option which has locale `Translation.SpeedLimits.Get("Checkbox:Display speed limits mph")`.

**Comment by aubergine10** [comment]
cacophony
image

**Comment by kianzarrin** [comment]
please consider resolving the conflict.

**Comment by aubergine10** [comment]
done

**Comment by krzychu124** [comment]
> ~done~
> 
> urgh, something else broke, brb...

`TLM\TLM\State\OptionsTabs\OptionsGeneralTab.cs(174,32): error CS0120: An object reference is required for the non-static field, method, or property 'RoadSignThemes.ThemeNames'` 😉

**Comment by aubergine10** [comment]
yup just fixed it, waiting for CI

**Comment by kianzarrin** [comment]
can you please update the branch too. I mean I can update it my self but I am not sure if you will like it.

**Review by krzychu124 — APPROVED** [review]
Looks good 👍

**Comment by krzychu124** [comment]
> Is it possible to put buttons side by side?
> 
> image

Hehe, that was the first thing I noticed 😄 
Solution (`panel` is `UIPanel` - you can use `(UIPanel)group.AddSpace(height)`):
```cs
 panel.autoLayoutDirection = LayoutDirection.Vertical; 
 panel.autoLayoutStart = LayoutStart.TopLeft; 
 panel.autoLayoutPadding = new RectOffset(5, 0, 0, 6); 
 panel.autoFitChildrenVertically = true; 
```

Create `UIHelper` from the panel like this:
```cs
UIHelper helper = new UIHelper(panel);
///add buttons as usual
helper.AddButton(...); 
```

**Comment by krzychu124** [comment]
I think it looks good enough to release in 11.6 but I'm not sure what else you plan for this (no milestone set).
@aubergine10 do you have any in-progress things regards to this? 

I would like to release latest version/`master` to the Workshop to be tested before releasing everything as Stable at DLC release day. Is there any chance to finish this or the Options refactor before DLC release (25th Jan) or we will release everything later? If not, no pressure, I just want to collect info what we have and what is still not finished and e.g. correct changelog in What's new panel for TEST because that one for Stable is pretty much final.

**Comment by aubergine10** [comment]
I'll pull in latest translations if there are any. 

Regarding putting buttons side by side, I'm waiting to see if there are any super-long translation strings that might thwart that.

I was planning to do another PR with many of the options transitioned to `CheckboxOption` but could probably manage to do that in this PR well before 25th.

BTW, I assume we're releasing as 11.6.3 or 11.6.4 to the stable page rather than rolling it all in to 11.6.0 for stable? If so, I'd also like to sort out the milestones (eg. stuff we merge now should be going in to a 11.6.3 milestone) including going back over the 11.6.0 - 11.6.3 merges and assigning those to relevant milestones then updating the main changelog.md.

Speaking of changelog.md, any idea what the full game version will be for the upcoming DLC/CCP releases?

**Comment by krzychu124** [comment]
Cool. 
That's my plan:
- bump version to 11.6.3, update changelog and merge #1284 and #1290,
- release to workshop and you can work on Options panel improvements here on in new PR. it will be either in internal 11.6.3.1 or 11.6.4 (as last number is dynamic, which I don't like)

Yes, we will release Stable as either 11.6.3 or 11.6.4 depends on above. Like I said I don't like current versioning since when I build version manually I have no idea later if it is newer or older when I compare multiple 11.6.2 builds (only by creation date+time). That needs to be improved to some automated incremental thingy. I'll try to reconfigure `Appveyor` to create draft releases on build tag (or something else) to utilize Appveryor versioning (it can automatically update `AssemblyInfo.cs` before build to test correct version). 
> I'd also like to sort out the milestones (eg. stuff we merge now should be going in to a 11.6.3 milestone) including going back over the 11.6.0 - 11.6.3 merges and assigning those to relevant milestones then updating the main changelog.md.

If you want and have too much time you could split milestones and reassign but on the other hand you can just rename it to 11.6 (so drop last `0`) and leave it like it is. It is a little mess... Versioning always was 🙁 

Game versions: `(1, 14, 0, 4) - 1.14.0-f4` (at 99.9% won't change), serialization version `193061904u`

**Comment by aubergine10** [comment]
WIP: Added `Enabled` property to `CheckboxOption` so I could disable the `Ignore disabled mods` option when `Check for known incompatible mods on startup` option is disabled. Which quickly evolved in to this...

image

Translations also working now. Just need to tidy up some stuff then will send commits.

**Comment by aubergine10** [comment]
@krzychu124 I tried adding panel but couldn't seem to get it to work - specifically creating the actual panel. (Once I have panel I can config it and add stuff to it)

https://github.com/CitiesSkylinesMods/TMPE/pull/1267#issuecomment-1013784882

I'm not sure what you meant by: `panel` is `UIPanel`

**Comment by aubergine10** [comment]
Pushing back to 1.7.0 - settings look weird (particularly Policies tab) with only half the checkboxes updated - will do additional PRs to port each tab to `CheckboxOption`, etc.

**Comment by aubergine10** [comment]
This is now superceded by a much better implementation via #1369, #1411, #1432

See also: https://github.com/CitiesSkylinesMods/TMPE/issues/1356

Buttons will be reintroduced later as part of #813, #733, #659, etc.

Translations were merged in: #1415 , etc.

**Pull request closed without merging**
