### PR TITLE
Converted almost all .m_segments.m_buffer[segmentId] calls to segment…

### PR DESCRIPTION
**Pull request by DaEgi01**
…Id.ToSegment()

And some minor stuff here and there.

My fingers and eyes are bleeding.
Your eyes will bleed too.

### CODE REVIEW

**Review by krzychu124 — APPROVED** [review]
Good, no bugs spotted :)

**Comment by DaEgi01** [comment]
> Good, no bugs spotted :)

are you even able to spot anything after this review ? ;D

**Comment by krzychu124** [comment]
> > Good, no bugs spotted :)
> 
> are you even able to spot anything after this review ? ;D

Enough coding for today 😄

**Review by kvakvs — APPROVED** [review]
This will add conflicts with SpeedLimits manager and tool in my branch, but its ok i can fix them, or you fix yours, whoever merges first wins 😁

**Comment by DaEgi01** [comment]
you lost ;p

**Pull request merged**
