### PR TITLE
LaneArrows facelift and refactor

### LINKED ISSUE #571: Lane arrow super-small on some resolutions
Biffa reports super-small UI on the lane arrows popup:

image

That's on STABLE release, but I assume similar on LABS and ALPHA.

I've not seen this before; it might be something to do with screen resolution or gfx drivers?

As we already plan major overhaul of lane arrow UI (see #391) I suggest we do that rather than spend time on the old UI...?

@kvakvs What is the current plans for #391?

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #571 

# New Features

New API for building forms: `U`
You can build forms with nested code structure with `using (var x = UIBuilder...) {}` API. Each form component can have an init function, and an optional resize function (which will be called when UI needs resizing) and can reposition and resize each control. The controls can be stacked to previous sibling's right, or below, with spacing if you wish. And controls can have a padding.
New UI forms take notifications from the Options UI scale slider and scale accordingly.

bild
(note: The keybinds feature is commented out and will be reintroduced later)

bild

# TODO

* [x] Darker shades of blue for active
* [x] Darker shades of grey for hover
* [x] Lower the left and right arrow images a little (maybe)
* [x] Check "Delete" works
  * (aubergine10): also, can you check over the 'delete' buttons on the vehicle/cim info panels - there were some bugs when you were in USA and quick patches were applied to get them working again; could probably do with some cleanup and adjust scaling - relevant issues/PRs are: #765, #763, #759
* [x] UI Scaling reduce to 150% at 4k resolution (current: 200%)
* [x] Allow UI Scale slider range from 50% (current 65%)
* [x] Position window correctly upon creation
* [x] Allow selecting other segments in the tool window state.
* [x] Remove keybinds panel for this merge, and reintroduce in a separate PR.
* [x] When screen resolution changes, the window is misaligned with the node on screen.

### CODE REVIEW

**Comment by kvakvs** [comment]
Testing and debugging at the moment.
Funny enough, having tool window for Lane Arrows as a child of TMPE Main Menu creates rubber banding drag effect on the tool window while dragging the main menu.

bild

**Comment by aubergine10** [comment]
This is looking awesome! Do you think we can get this in to the 11.1.1 release?

**Comment by aubergine10** [comment]
Also, can we add a reset button?

**Comment by kvakvs** [comment]
Important
This needs to be tested at 4k resolution and possibly we need a formula to reduce the scaling a bit, so it is not very large compared to the rest of the game UI.

**Comment by aubergine10** [comment]
The UI momentarily appears small in middle of screen then pops in to position at chosen user scaling. See attached vid:

[bandicam 2020-03-31 22-28-14-496.zip](https://github.com/CitiesSkylinesMods/TMPE/files/4411683/bandicam.2020-03-31.22-28-14-496.zip)

Maybe have the UI hidden until it's possitioning/sizing is finalised?

----

With a segment selected, it feels a bit clunky selecting a different segment. Could we make it so I can just click any other junction-entering segment to select it (even if another segment is already selected). Right-click should still de-select current segment as it currently does.

----

The UI still feels a bit big to me, is it possible to allow the scale slider in mod options to go down to 50%? (Currently it's min value is 65%)

----

The tooltip is making the floating panel unnecessarily large when there's less than 3 lanes:

image

Could it word wrap? Or maybe an option to toggle it's display (once I know the shortcut I don't really want to be seeing it every time)?

----

The positioning seems to get offset when screen res is changed in-game. For example, on 1920x1080 (everything above was tested at this res), the panel is shown in centre of junction like so:

image

When I change to 2560x1440 it gets offset like this:

image

----

Note: everything above was using 65% UI scaling in mod options. I just did a quick test at 100% and the same issues occur.

**Comment by kvakvs** [comment]
This now looks like its scaling correctly, and positioning correctly too.

**Comment by krzychu124** [comment]
I'm getting exception when I right click with arrows tool enabled
```cs 
NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.UI.SubTools.LaneArrows.LaneArrowTool.OnToolRightClick () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.TrafficManagerTool.OnToolUpdate () [0x00000] in <filename unknown>:0 
  at ToolBase.Update () [0x00000] in <filename unknown>:0 
 ```
to be precise it breaks at this line:
```cs
Log._Debug(string.Format("LaneArrow right click state={0}, new={1}", state, this.fsm_.State));
```

**Comment by aubergine10** [comment]
It's allowing seemingly non-valid arrows to be selected:

image

I would expect the left turn button there to be disabled.

----

Text doesn't seem to be scaling with the UI?

image

----

Other than those two very minor details it's working great! Hope you do Speed Limits palette next :)

**Comment by kvakvs** [comment]
* Font scaling fixed, now font scales to ridiculous small or big size too.
* Lane-arrows-window hopping on creation fixed.
* Clicking other segments was showing old Lane-arrows-window, now fixed, the state is correctly exited and re-entered and the window is updated now too.

As for extra rendering of direction arcs and disabling the buttons, i am not sure the old UI had this feature either.

**Comment by kvakvs** [comment]
Trying new error propagation rules using `Result<ErrorEnum>` and guide popups while lane connectors are enabled, the guide should pop up.

**Comment by krzychu124** [comment]
@kvakvs you can leave it there. 
I think we will push both your PR's and Kian's (i have to test it) as one update to the Labs

**Comment by kvakvs** [comment]
Setting DONOTMERGE, as the next PR will come into this branch, and when all is good, they both can be merged.

**Pull request merged**
