### PR TITLE
Themed default speed signs (redux)

### PR DESCRIPTION
**Pull request by aubergine10**
Compiled mod for testing: [TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=themed-defaults-redux)

This is a redux of #1320

image

Changes to speed limits overlay:

* Segment and lane modes now always use themed icons (defaults mode still always shows unthemed icons).
* If user customises a speed to value other than network default, a green sub-icon is appended to the themed speed sign.

Example:

image image

That sub-icon is only shown in interactive mode, when used has customised the speed to non-default value, but only if a mod option is enabled in Overlays tab:

image

Todo:

- [x] Apply same thing to lane mode
- [x] Persist option to savegame
- [x] Fix size of lane mode icons (similar to #1320)
- [x] Test with monorail in lane mode (which adds passenger train sub-icon)

Updates: https://github.com/CitiesSkylinesMods/TMPE/issues/1221#issuecomment-1022557573

### CODE REVIEW

**Comment by aubergine10** [comment]
> An alternative is to show the green sub-icon (complete with speed value) on non-default speeds, and maybe have mod option to toggle whether it's shown at all?

I'm thinking tht would be much better approach acutally. And have the option disabled by default.

Now _actually_ going to get some sleep.

**Comment by kvakvs** [comment]
I would say it does not matter where and how you show the default green icon, this is a case of [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding). Just show the default somewhere. Need an option to hide it - fine, you already had that implemented.

**Comment by aubergine10** [comment]
ready for review

**Comment by krzychu124** [comment]
Some themes does not play well with default 😕 

image

image

**Comment by aubergine10** [comment]
Ah, good catch, it's currently using same aspect ratio as the themed sign. Hopefully easy to fix, brb...

**Comment by aubergine10** [comment]
Ok, try that :)

**Review by krzychu124 — APPROVED** [review]
Code looks ok, tested in-game.
image

**Comment by aubergine10** [comment]
@kvakvs any feedback?

**Review by kvakvs — APPROVED** [review]
Me likey

**Pull request merged**
