### PR TITLE
Incorrect minimal number of path-find threads

### PR DESCRIPTION
**Pull request by krzychu124**
User reported that on the map with TM:PE enabled there was no traffic at all and game didn't spawn new vehicles.

It's super weird case but somehow game reported 1 core CPU which does not make sense, but... TM:PE created 0 path-find threads 😂 

Specs from `output_log.txt` (`i7-1165G7` is 4 core/8 threads CPU)
```
Model: HP Laptop 17t-by400 (HP)
OS: Windows 10  (10.0.0) 64bit
Language: English
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (1 core(s))
System Memory: 29594
Gfx Device: Intel(R) Iris(R) Xe Graphics
Gfx Version: Direct3D 11.0 [level 11.1]
Gfx Memory: 7526
Gfx Shader Model: 50
Game Version: 1.14.0-f4-steam-win
```

### CODE REVIEW

**Review by aubergine10 — APPROVED** [review]
LGTM 👍

**Comment by krzychu124** [comment]
@aubergine10 It turned out it is not HP laptop specific thing but disabled cores in boot adv. options (accessed with Win+R `msconfig.exe`)

image

**Comment by aubergine10** [comment]
Why on earth would anyone do that lol

**Review by kvakvs — APPROVED** [review]

**Comment by krzychu124** [comment]
> Why on earth would anyone do that lol

You know... guides on the web, some are for improving performance, some other not 😂

**Comment by DaEgi01** [comment]
> > Why on earth would anyone do that lol
> 
> You know... guides on the web, some are for improving performance, some other not 😂

I remember breaking my windows installation with those guides from time to time ages ago xD
made me force to reinstall clean which actually did the perf improvement, so they kinda worked out ;)

**Pull request merged**
