### PR TITLE
New Speed Limits UI

### PR DESCRIPTION
**Pull request by kvakvs**
This introduces:

- New speed limits UI
- New overlay for speed limits showing both current override, and defaults, or both (holding Alt). Textures rendered transparent when they overlap with TM:PE UI which reduces the overlay/UI overlapping problem since Harbor DLC.
- New textures for default speed limits (blue signs), SVG source file with the graphics
- New texture for no override (circle)
- MIP mapped textures instead of old aliased textures

bild

TO DO and Bugs:

- [x] BUG: Changing display MPH option sends event handled by speed limits tool which rebuilds the UI
- [x] Cosmetic: Move X button to the left because it has a long label
- [x] Cosmetic: Make cursor tooltip have 2px padding
- [x] BUG: When TM:PE main panel must close, the Speed limits window must hide and then properly reappear too
- [x] BUG: Dragging window only works on the title label, make label width to fit window.
- [x] BUG: Tooltip label on mouse cursor contributes to window size
- [x] BUG: Changing language does not rebuild window labels in new language
- [x] BUG: When MoveIt changes road segment, lane signs remain misplaced
- [x] BUG: Holding Shift in lane mode works on click, but does not highlight with blue sausages
- [x] BUG: Transparency of signs when colliding with UI windows does not work. The collision boxes seem to be wrong/off. Is something to do with UI scale?
- [x] BUG: Holding shift to set speed limits for a street not working
- [x] TODO: How to show that there is no override, or override is same value as the segment default? Old solution was to show white ⭕ and small blue default speed limit (like this but reverse https://user-images.githubusercontent.com/288724/118206586-1a3e8900-b463-11eb-8f10-e4914ddbf4d9.png )
- [x] Speed limit value buttons sometimes don't accept clicks in their bottom half?
- ~Get rid of the tooltip and use existing tooltip helper class, problem when UI scale is different than 100%.~
- [x] Cursor tooltip position is wrong when UI scale is different than 100%
- [x] Tooltip position blinks for a frame (I think it's worth setting correct position before first render),
- [x] Add the translation strings
- [x] opening panel takes way too long IMO (~2sec), lag is consistent, no matter how many times I try, which suggest that panel is build from scratch each time or some really slow operation is running before showing the panel.
- [x] speed limits overlay (outside tool) does not work, probably because of that:
```
Error 210.3279831: GUI Error: System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.U.HelperExtensions.GetScreenRectInGuiSpace (ColossalFramework.UI.UIComponent ctrl) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.SpeedLimits.SpeedLimitsTool.CreateOverlayDrawArgs (Boolean interactive) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.SpeedLimits.SpeedLimitsTool.RenderGenericInfoOverlay_GUI () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl (UnityEngine.Event e) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl(UnityEngine.Event e)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUI(UnityEngine.Event e)
   at ToolBase.OnGUI()
```
- [x] Make default overlay view to show signs per whole road, not per direction - just like IRL.
- [ ] (Minor) add some kind of feedback to the user that shown speed limit is averaged value when one or more lanes have different speed.
- [x] (Minor) since we can't(won't) change default limits per lane, maybe we should hide that from view, so we can reuse the key modifier to switch between handles per-road and per-lane
- [x] Overlay seems to be cached, so after moving segment it shows sign handles at the same place https://user-images.githubusercontent.com/19638970/141699445-26c3c738-ad0a-4e01-a3ac-cd407ade1fda.png
- [x] BUG: MoveIt integration trying to copy roads would crash with assertion error trying to apply "no override" to copied lanes
- [x] BUG: in loading speed limits conversion https://user-images.githubusercontent.com/19638970/141701722-91135805-d4cb-47f4-8f29-0a156c837421.png
- [x] BUG: in default speed limits view, no matter what the lane/segment toggle is, must only show per segment speed limits, and click must work also regardless that toggle
- [x] Redesign the tool states: 1st button becomes tri-state: Show segments, show lanes, show defaults. 2nd button is removed. Alt always shows either default speed for this road type or segment speed if defaults is on, and hides whatever other was being rendered.
- [x] BUG: no overlays when cursor is intersecting with sign, nor when holding shift
- [x] BUG: when holding alt - shows default speed but you can still click and change overrides 
- [x] BUG: Keybind tooltip is correct but opens junction restrictions tool

### CODE REVIEW

**Comment by DaEgi01** [comment]
> The TODOs changes should be small. Can review new commits separately.

I never care for draft PR and would rather review the final one. or is it really a draft in the sense that you want some feedback first before you want to proceed?

**Review by krzychu124 — COMMENTED** [review]
Looks good, UI nicely separated from the tool 👍
Will test in-game...

**Comment by krzychu124** [comment]
Couple findings: 
- cursor tooltip position is wrong when UI scale is different than 100%
- tooltip position blinks for a frame (I think it's worth setting correct position before first render),
- opening panel takes way too long IMO (~2sec), lag is consistent, no matter how many times I try, which suggest that panel is build from scratch each time or some really slow operation is running before showing the panel.
- speed limits overlay (outside tool) does not work, probably because of that:
```cs
Error 210.3279831: GUI Error: System.NullReferenceException: Object reference not set to an instance of an object
  at TrafficManager.U.HelperExtensions.GetScreenRectInGuiSpace (ColossalFramework.UI.UIComponent ctrl) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.SpeedLimits.SpeedLimitsTool.CreateOverlayDrawArgs (Boolean interactive) [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.SubTools.SpeedLimits.SpeedLimitsTool.RenderGenericInfoOverlay_GUI () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl (UnityEngine.Event e) [0x00000] in <filename unknown>:0 
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUIImpl(UnityEngine.Event e)
   at TrafficManager.UI.TrafficManagerTool.OnToolGUI(UnityEngine.Event e)
   at ToolBase.OnGUI()
```
- apparently bugs reported about issues with loading and storing settings are gone. Cannot reproduce them once I merged this PR into latest `master`

One thing which once I realized about some time ago, now can't be unseen and would be nice to address it:
- make default overlay view to show signs **per whole road**, not per direction - just like IRL.

Other minor things to consider:
- add some kind of feedback to the user that shown speed limit is averaged value when one or more lanes have different speed.
- since we can't(won't) change default limits per lane, maybe we should hide that from view, so we can reuse the key modifier to switch between handles _per-road_ and _per-lane_

**Comment by krzychu124** [comment]
I found one more issue:
image

Overlay seems to be cached, so after moving segment it shows sign handles at the same place

**Comment by kvakvs** [comment]
Added the notes to the TODO list, will begin fixing one by one now.

**Comment by krzychu124** [comment]
> apparently bugs reported about issues with loading and storing settings are gone. Cannot reproduce them once I merged this PR into latest master

Nope, after loading older savegame everything is ok, but once saved and reloaded any lane/segment I touched with speed limits tool is gone. Investigating...

**Comment by krzychu124** [comment]
Yup, there is a bug in conversion when loading settings 

image

**Comment by krzychu124** [comment]
@kvakvs 
https://github.com/CitiesSkylinesMods/TMPE/blob/b703cc4feea90768f3c551c483a2ed1e83d5b0cb/TLM/TLM/State/Flags.cs#L573
limit per lane dictionary is filled with Kmph, but then while saving they are treated as `GameUnits`

https://github.com/CitiesSkylinesMods/TMPE/blob/b703cc4feea90768f3c551c483a2ed1e83d5b0cb/TLM/TLM/Manager/Impl/SpeedLimitManager.cs#L922-L926
https://github.com/CitiesSkylinesMods/TMPE/blob/b703cc4feea90768f3c551c483a2ed1e83d5b0cb/TLM/TLM/State/Flags.cs#L893-L899

here converting again to Kmph
https://github.com/CitiesSkylinesMods/TMPE/blob/b703cc4feea90768f3c551c483a2ed1e83d5b0cb/TLM/TLM/State/Configuration.cs#L21-L23

Am I missing something here?

**Comment by kvakvs** [comment]
Thanks for investigating
That is the conversion point and i made it safe to that point but i always forget how speeds are stored in the savefile 😀

**Comment by krzychu124** [comment]
>  laneSpeedLimit[laneId] = action.Override.Value.GetKmph(); 

That lane was changed in previous PR, probably by accident, since the code for loading and saving data is pretty much the same. I did 20? quick saves that's why values were so big.

I haven't found any new issues other than those from previous comments😃 👍

**Comment by aubergine10** [comment]
Is there a zip of the latest build of this PR? (I've still not got round to reinstalling build env)

**Comment by kvakvs** [comment]
> Is there a zip of the latest build of this PR? (I've still not got round to reinstalling build env)

Below click ✔ All checks have passed: Show details, then click Appveyor -> Details
Then click Artifacts
bild

**Comment by aubergine10** [comment]
Could some additional keyboard shortcuts be added:

* `1`-`9` and `0` -> set speed 10 .. 90 .. 100)
* `-` `=` (customisable) -> increase/decrease speed
* `Del` `Backspace` -> 'revert to default'
* `/` -> unlimited
* `Ctrl` -> temp toggle between segment vs. lane mode (as applicable to current mode)

That way I don't need to keep going back to palette to choose speed, I can eg. press `5` (50) then `=` to get 55.

**Comment by aubergine10** [comment]
Blue signs for defaults might be issue as blue is often used for _minimum speed limit_ in many countries: https://commons.wikimedia.org/wiki/Speed_limit_road_signs#Minimum_speed_limit_signs

Not sure what colour would be better (something other than white, yellow or blue). Maybe grey, or green?

**Comment by kvakvs** [comment]
> Blue signs for defaults might be issue as blue is often used for _minimum speed limit_ in many countries: https://commons.wikimedia.org/wiki/Speed_limit_road_signs#Minimum_speed_limit_signs
> 
> Not sure what colour would be better (something other than white, yellow or blue). Maybe grey, or green?

Pick some color and shape. Green maybe, that's fine with me. I would use gray to indicate something inactive or disabled in the UI, so maybe not gray.

**Comment by aubergine10** [comment]
Something like this (robbed from github 'all checks passed' icon lol): 
image

**Comment by kvakvs** [comment]
> Something like this (robbed from github 'all checks passed' icon lol): image

Probably use game default font, not German or any other?

**Comment by kvakvs** [comment]
Pressing 1-2-3 switches simulation speed, i am not sure how to consume the key press.
I tried doing `UIPanel.OnKeyDown`, `OnKeyUp`, `OnKeyPress`, and use the event parameter p (`p.Use()`), it still goes through to the game.

**Comment by kvakvs** [comment]
Here's the result. With translations. +- keys configurable. Could not use 0..9 but instead can use Alt+0..Alt+9
Only small problem after opening speed limits tool it does not receive Alt+0..9 key presses but after you select something manually it suddenly works.

bild

**Comment by aubergine10** [comment]
Is there merit to merging the segment vs. lane buttons in to one button (where its icon changes to indicate current mode), working similar to km/h vs. mph...?

Then move the default speeds button next to the segment/lane button...

Then replace the current title bar text with the text from above the speed buttons...

And in the space where the text above the speed buttons is, have a text-captioned button to toggle between km/h vs. mph with the speed unit caption next to it...

```
Editing speed limit overrides for segments
            [km/h] Kilometers per Hour
(S/L) (DS) [/] [x] [speed buttons]
```

**Comment by kvakvs** [comment]
> Is there merit to merging the segment vs. lane buttons in to one button (where its icon changes to indicate current mode), working similar to km/h vs. mph...?

Two state segments/lanes switch was in the original prototype.

> Then move the default speeds button next to the segment/lane button...
> Then replace the current title bar text with the text from above the speed buttons...
> And in the space where the text above the speed buttons is, have a text-captioned button to toggle between km/h vs. mph with the speed unit caption next to it...

This is just another layout change, it will work, and it might save some pixels of panel size. Buttons also can be sized down to 40px, like main menu panel buttons.

**Comment by aubergine10** [comment]
✔️ Love the new green default speed icons!

⚠️ `Alt+1..9` shortcuts are used by **Find It 2** mod (opens Find It with a specific asset category already selected). Could some other modifier be used? Note that `Ctrl+0` is used by **Broken Node Detector** mod.

⚠️ All the new shortcuts seem to have the issue that they don't work immediately after opening the speed tool, they only start working after I've clicked one of the speed buttons after which they work as advertised.

❓ To get round the two ⚠️ issues above, could an invisible text box be added to speed palette? We could set focus to it on speed tool open, hopefully activating all the shortcuts, and also we could set focus to it after any interaction and it might provide a way to accept 0-9 as shortcuts without the need for modifier keys? (eg. numeric-only text box and we listen for on-change, grab the digit, then clear text box so it's ready for another use)

➕ When holding `Alt` to show default speeds, would be nice if I could set the defaults in that state (ie. in much the same way I can set lane/segment speed overrides while holding `Ctrl` key).

➕ Add a space between `x` button and the other buttons?

➕ Could 'unlimited' speed button be better placed at the end of the speed bar (eg. after 90mph); that way speed bar follows scale from `10 -> 90 -> unlimited` which seems more logical; also `=`/`+` shortcut could go up to unlimited

➕ Could 'unlimited' button be reduced in size, so that speed window doesn't change width when it's selected (eg. can it work same way as the numbered buttons)

➕ Change 'unlimited' button bg color to blue? (current red bg feels like it's going to delete/cancel something)

❓ Are clickable overlay icons becoming more transparent as I zoom out? It's making them difficult to read as I zoom out.

❓ Is it possible to hide overlay icons if they appear behind the tootip panel (as they make tooltip panel text harder to read):
image

**Comment by kvakvs** [comment]
> ⚠️ `Alt+1..9` shortcuts are used by **Find It 2** mod (opens Find It with a specific asset category already selected). Could some other modifier be used? Note that `Ctrl+0` is used by **Broken Node Detector** mod.

> ⚠️ All the new shortcuts seem to have the issue that they don't work immediately after opening the speed tool, they only start working after I've clicked one of the speed buttons after which they work as advertised.

Got to come up with something better. 1 2 3 work in any tool mode and switch game simulation speed. But other mods' keybinds only should work when those mods are active, and if those mods become active, TM:PE should hide, like it hides with MoveIt mod. So we can make it work. Instead what I've done is I have added a new checkbox: Extra keybinds in speed limits, which can disable these +- / Delete and 0..9 keybinds.
 
> ❓ To get round the two ⚠️ issues above, could an invisible text box be added to speed palette? We could set focus to it on speed tool open, hopefully activating all the shortcuts, and also we could set focus to it after any interaction and it might provide a way to accept 0-9 as shortcuts without the need for modifier keys? (eg. numeric-only text box and we listen for on-change, grab the digit, then clear text box so it's ready for another use)

Focusing one of existing buttons done the trick. Now its all good. The button wasn't clicked so its also good.

> ➕ When holding `Alt` to show default speeds, would be nice if I could set the defaults in that state (ie. in much the same way I can set lane/segment speed overrides while holding `Ctrl` key).
> 
> ➕ Add a space between `x` button and the other buttons?

Added

> ➕ Could 'unlimited' speed button be better placed at the end of the speed bar (eg. after 90mph); that way speed bar follows scale from `10 -> 90 -> unlimited` which seems more logical; also `=`/`+` shortcut could go up to unlimited

The hint under the button will hang out of the window, that does look bad.

> ➕ Could 'unlimited' button be reduced in size, so that speed window doesn't change width when it's selected (eg. can it work same way as the numbered buttons)

> ➕ Change 'unlimited' button bg color to blue? (current red bg feels like it's going to delete/cancel something)

X and Ø buttons do not change size on click, its the speed palette buttons which grow to fit larger text.

> ❓ Are clickable overlay icons becoming more transparent as I zoom out? It's making them difficult to read as I zoom out.

They do. I cap the opacity at 1.0 for now, they still fade to 0.4x if they intersect one of GUI elements (Speedlimits window, Main window, and will also add to that list Main window onscreen hint panel).

> ❓ Is it possible to hide overlay icons if they appear behind the tootip panel (as they make tooltip panel text harder to read): image

Yes i predicted this will be needed, the upgrade of the game to Sunset Harbour changed the way overlays render and our road signs went all over the GUI (render order changed). I had to be creative and check intersection and fade graphics if it intersects. At least now we have this technology to apply it to other overlays.

**Comment by aubergine10** [comment]
> The hint under the button will hang out of the window, that does look bad.

Is there any way to identify when an under-button hint text will go out the window and somehow right-align it to the edge of the window?

> X and Ø buttons do not change size on click, its the speed palette buttons which grow to fit larger text.

Yup, but if `Ø` is treated as if it were a speed (and the under-button hint text issue overcome) it would be nice if it could shrink when not focussed, similar to how the speed palette buttons do, to avoid the window width changing when cycling through the speeds.

**Comment by aubergine10** [comment]
Random idea: Is it possible to trap mouse wheel events while mouse is hovering a speed icon in the overlay?

For example, I could hover a speed sign on the map and use mouse wheel to scroll the speed of that specific sign? `Shift`+`Wheel` could adjust sign speeds between junctions.

Also: When mouse is over the speed tool window, the mouse wheel could cycle through the speeds on the speed bar?

**Comment by aubergine10** [comment]
Pressing `Esc` doesn't exit the speed tool. Instead it opens the game Pause Menu.

**Comment by aubergine10** [comment]
Unable to vertically scroll the keybinds tab in mod settings:

image

Also, should speed icon theme be moved to Overlays tab (under "Speed limits" heading, and the other persistent overlays could go under a "Persistent Overlays" heading)? Although it might be hard for users to find in there.

> Are clickable overlay icons becoming more transparent as I zoom out? It's making them difficult to read as I zoom out.

> They do. I cap the opacity at 1.0 for now, they still fade to 0.4x if they intersect one of GUI elements (Speedlimits window, Main window, and will also add to that list Main window onscreen hint panel).

They could still fade a bit as they approach maximum distance from camera, as that lets user know they're about to disappear. Is it possible that up to a certain zoom there's capped fading, but beyond that they fade with further distance? (hope that makes sense lol)

**Comment by kvakvs** [comment]
This is getting out of hand, i don't have a year to rewrite entire new UI. Might roll back to some stable point and release it there.

**Comment by kvakvs** [comment]
6c8ce5f is okay, except i need to focus one of the buttons.

**Comment by aubergine10** [comment]
Only major point for this PR is that `Esc` key not exiting speed tool.

I'll create a separate issue to track all the other points, those can be done later.

**Comment by kvakvs** [comment]
Now fixed Esc, and form focus fixed too. The branch with reworked UI layout is here https://github.com/kvakvs/TMPE/tree/u-speedlimits-tool-feature-creep and it took far more work than i anticipated. Don't let this happen, first plan, then execute. Rewriting UI in review comments is no good.

**Comment by kvakvs** [comment]
Added cheaper simple changes back. Layout changes are not cheap, the UI allows some of those tricks you desire, and doesn't allow some others, so it quickly becomes messy.

**Comment by aubergine10** [comment]
❤️ the new layout!

image

**Comment by kvakvs** [comment]
> ❤️ the new layout!
> 
> image

The change size was growing, and i yet have to do some other work tonight. We can return to it later, probably, or redo it a bit cleaner.

**Review by aubergine10 — APPROVED** [review]
Tested:

✔️ Loading/conversion of speed customisations from v11.5.2 and v11.6.1 saves
✔️ Vanilla + Workshop roads (including some weird roads I had subscribed)
✔️ Lane vs. segment
✔️ Inside/outside central 25 tile area
✔️ km/h vs. mph speeds
✔️ Setting default speeds
✔️ OSD collision transparency
✔️ Camera angles/zooms
✔️ Road vs. tracks
✔️ Short segments
✔️ Asymmetric roads
✔️ 1-way and 2-way roads/tracks

I've not tested save/load yet as another mod is currently breaking my saves. I've not tested monorail/tram-only networks or trolleybus. Those can be tested in future PR.

**Comment by kvakvs** [comment]
If Ctrl is not in this branch i can add it, the change set is short for that.

**Comment by aubergine10** [comment]
> If Hold Alt to show defaults is not in

It's in (tested via latest appveyor build)

**Comment by kvakvs** [comment]
> > If Hold Alt to show defaults is not in
> 
> It's in (tested via latest appveyor build)

I mean holding Alt and editing defaults, and holding Alt in defaults and editing overrides.
It is in now, just pushed.

**Review by DaEgi01 — APPROVED** [review]

**Comment by aubergine10** [comment]
Regarding minor task in OP:

> (Minor) add some kind of feedback to the user that shown speed limit is averaged value when one or more lanes have different speed.

Maybe:

* Use basic circle icon (similar to default speeds, but different colour/shape)?
* Or, rotate the icon by 45 degrees? Or make bigger than normal?
* Or, force per-lane speed display on segments that have lanes with different speeds? (might clutter overlay tho)

If leaving to later PR, add to #1221 to track.

**Review by krzychu124 — APPROVED** [review]

**Pull request merged**
