### PR TITLE
More Accurate Lane Connection Arcs

### LINKED ISSUE #3: UI: More accurate lane routing arcs
The lane routing lines at junctions don't follow the actual path the vehicles take, they just use a very basic arc between source lane and destination lane.

Would it be possible to use the same approach that the vehicle AIs use in order to create more accurate lines to depict the lane routing? They'd still be an arc, but the properties of the arc would be more accurate based on the actual trajectory the vehicles take.

While this in itself is a minor and somewhat superfluous enhancement, it would be very useful for several other enhancements which I'll post as separate tickets.

### PR DESCRIPTION
**Pull request by krzychu124**
Key changes:

- greatly improved shape of lane connection. Now it should be almost equal to path of moving vehicle :wink:
- removed rendering of gray circles from all intersections (still visible on intersection with lane connection set - todo)
- improved drawing performance in edit and preview mode (little game hang when switching from preview -> edit - todo)
 
I think this could be the first new enhancement pushed to LABS first before moving to STABLE but we will see 😉 

PR set as draft for now until I'll fix those problems 😃

lane connections

Fixes #3

### CODE REVIEW

**Comment by aubergine10** [comment]
testing :)

**Comment by aubergine10** [comment]
Looking good!

I noticed that, in edit mode, when mouse is over a road segment, the node-selection circles hide the lines as shown below:

blank

This makes it hard to see the existing connections.

When mouse is not over a road segment, the lines show normally through the circle.

**Comment by krzychu124** [comment]
Yeah some colors has to be changed. 

I will check what can be done with that circle on hover. 
Would be nice to add transparency to it and make it appear on hover in edit mode only, to be consistent with other tools involving node selection.

BTW. There is an array with colours at the bottom of that class. You can play with those colors if you find some time 😉

**Comment by aubergine10** [comment]
I think part of the problem with the colours at the moment is that it tries to give each lane entering the junction its own colour, which can be a huge number of colours on complex junctions. If there is viability to get some of the other lane connector UI improvements in we might be able to simplify some aspects of that.

**Comment by aubergine10** [comment]
> I kind of like the behavior of the lines being unable to be seen on hover

The lines get hidden when the mouse is over _any_ road segment, not just the node.

I don't use the overlays to keep fps high (a habit I got in to when I was back on the old potato computer), so when I want to check my lane connections I activate the lane tool and look around the map. Having lines disappear if the mouse hovers a road breaks that use case, a use case that's important for people with potato computers.

If we wanted to show feedback when mouse is over a node, the circle could just change colour.

> I'm unsure of what this "game hang" you're talking about is

I also did not notice any lag, however my current computer is pretty good spec and while testing I was just in small city with few roads and fewer lane connectors active. I assume the issue becomes prevalent in larger cities, slower computers, or just with more lane connections?

**Comment by krzychu124** [comment]
There is an issue when you set lane connections at complex intersection  Lane connections preview is not refreshed after removing segments. Currently lane connection arcs are rebuild only after switching from preview to edit... I'll have to add some listeners for that.

**Comment by aubergine10** [comment]
Can this line be altered:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/4b68e8939c6d94b2e466d814568ae75c86b4800c/TLM/TLM/UI/SubTools/LaneConnectorTool.cs#L492

So that if `isTarget` is `true` it uses white color (ideally from a constant as I plan to remove white from the list of colors at bottom of file). This will ensure all target nodes are white by default.

**Comment by aubergine10** [comment]
I converted the `colors` array to fake CSS so I could use pigments plugin, here are the colors visualised:

colors

There are several that are too dark. Before I get started working on new `colors` palette, do we need 48 colours?

**Comment by krzychu124** [comment]
> There are several that are too dark. Before I get started working on new colors palette, do we need 48 colours?

Honestly I think we don't. 
48 colors means - 48 incoming lanes to intersection node. 
That has to be 6 segments with 8 lane one-way road each.

**Comment by krzychu124** [comment]
I've created simple 'sigh!' performance test setup 😄 _Notice FPS gain on my not so potato computer_
- ~**30-31FPS** 
 _no connection rendered_
Zrzut ekranu (162)
- ~**15-18 FPS** 
**[Stable]** _Lane connections - **Preview mode**_
Zrzut ekranu (164)

- ~**13-15 FPS** 
**[Stable]** _Lane connections - **Edit mode**_
Zrzut ekranu (165)

- ~**25-27 FPS** 
**[Labs - current PR version]** _Lane connections - **Preview mode**_  no difference between _Edit mode_
Zrzut ekranu (163)

**Comment by aubergine10** [comment]
So the penalty we pay for better lane routing arcs is a performance increase. 😀 

> 48 colors means - 48 incoming lanes to intersection node.

Currently color choice is based on `nodeMarkers.Count % colors.Length` (line 492 as mentioned in earlier comment). If we have a counter that tracks number of `isSource` nodes, that would be better metric than `nodeMarkers.Count` as it will avoid skipping colors in the palette due to `isTarget` nodes, so less chance of reusing same colour on the soon-to-be reduced `colors` palette.

**Comment by aubergine10** [comment]
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/blob/4b68e8939c6d94b2e466d814568ae75c86b4800c/TLM/TLM/UI/SubTools/LaneConnectorTool.cs#L481-L483

Would it be better to just update the `.y` of the existing vector? Will reduce number of new vectors created = less garbage collection.

**Comment by krzychu124** [comment]
I will try to hardcode target markers to be white.

Some thoughts about performance 😃 

The funny thing is that there is still room for improvements with regards to rendering performance 😄 

Current lane connections and markers are rendered using the same shader that is used to render blue placeholder when placing road segments, selecting buildings, cars etc... 

I was digging through code and I think that removing unnecessary calculations (rounded ends and transparent filling) should boost rendering speed. 

Additionally we can increase performance even more by writing simple custom shader which job would be only to draw arc with some width with lower resolution (it's not a rocket science 😄 ). 
Collisions for conflict points could be calculated using  bezier curves then add to list of shapes to render

After that I will try to create shader for square and triangle #41 lane connectors because it seems to be better tool for rendering those shapes with nice anti-aliased lines than using complex mesh or texture 🙃  

Good catch with this Vector3 👍 _I am sure there are more issues like this._

**Comment by aubergine10** [comment]
Research on color alphabet for lane connector: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/287

**Comment by krzychu124** [comment]
Lane connections test setup [save](https://steamcommunity.com/sharedfiles/filedetails/?id=1717497356)

**Comment by aubergine10** [comment]
Testing that save...

Stable 10.18:

* No overlay: 42fps
* Preview: 24-30fps
* Edit: 24-30fps

Labs PR 282:

* No overlay: 42fps
* Preview: 38fps
* Edit: 38fps

So, 8fps faster than current release :D 

One thing that became very apparent while in edit mode is that it's difficult to see which node is being edited. Would it be possible to "thin" the lines of other nodes, or maybe make them slightly transparent? That way the node being edited will have visual difference to the non-editing nodes.

**Comment by aubergine10** [comment]
Heading to bed, but some things I realised need testing....

* Lane connections underground (in tunnels)
* Lane connections on other networks (do they even apply to other networks? rail, metro, tram, monorail, paths?)
* Lane connections on junction under elevated/bridge, and on elevated/bridge

**Comment by krzychu124** [comment]
To test issue with refreshing preview, just build big intersection using wide segment e.g. 6-lane 2-way (node will be bigger) then connect outer lanes of near segments and after that change segments type to smaller e.g. rural road or basic 2-way one-lane. Lane connections will stay the same in preview mode. Refresh is performed only when you switch to edit mode (bezier arcs cache is rebuild there)

Yeah... I think I will add one more color but half transparent. Original for preview all or belonging to currently edited node and half transparent to preview other from not selected nodes

**Comment by aubergine10** [comment]
There is another issue in the GIF above, that the outgoing connector for u-turn is not appearing (see also report from end-user: #293).

@FireController1847 Does the issue in your GIF only happen on monorail roads, or does it happen on normal roads as well?

**Comment by FireController1847** [comment]
@aubergine10 No. It happens on all roads. I'm unsure why they're not appearing at all. I didn't have a lot of time to test on different maps, but I did try on a savegame and the issue was still there. I will note the issue was NOT there when I tested on my Desktop.

~~I think you missed my comment right below my gif lel~~

**Comment by krzychu124** [comment]
Interesting...

**Comment by aubergine10** [comment]
I've just tested on my desktop (Win10, Ryzen 5 2600X, GTX 1080 Ti) and it was working fine.

What are the specs of  your laptop, specifically your graphic card and DirectX? Does adding or removing `-force-d3d9` parameter resolve the issue?

**Comment by aubergine10** [comment]
Regarding #293, I can confirm that lane router tool doesn't allow u-turns on junction segments that contain monorail track:

monoturn

**Comment by aubergine10** [comment]
Testing lane connector in tunnels:

underground

While it works, there are some obvious issues:

1. I can't see the roads (I had to just move mouse randomly until node selector appeared)
2. When adding connections, the 'live connection' (from source to mouse pointer) is not taking account of the camera angle & depth of target node (or something along those lines).

Other than that, it the connections do seem to work.

**Comment by aubergine10** [comment]
Some additional issues with underground connectors - it seems that depending on a combination of camera angle and distance from source node, the "live connector" (that follows mouse) will disappear:

Short distance from source:

ug1

Longer distance from source:

ug2

If, however, the camera was facing directly downwards (as shown in image in my previous comment), the line would remain visible.

**Comment by aubergine10** [comment]
Just noticed another strangeness when working with underground lane connections...

The target circle is 'activated' (gets bigger indicating the line can be connected to it) when either of the following are true:

* Mouse is over target circle
* End of "live connection" line is over target circle

It seems odd that both situations activate the target circle - surely it should just be one or the other? If code is checking both, that's eating fps.

Solution would be to make "live connection" line end where the mouse pointer is (when connection is underground it goes wildly astray) and only check mouse pointer in order to determine when connection can be made.

**Comment by aubergine10** [comment]
Buglet: With a node selected, if I press `Backspace` to delete custom lane connectors for that node, the source circles disappear. I have to exit the node (right-click) then re-select it (left click node circle) to bring back the source circles in order to create any new connections.

**Comment by aubergine10** [comment]
Testing on Bridges and got similar issue to what @FireController1847  mentioned...

bridge

The line was not appearing on top of bridge but the lane arrows were updating. Then I moved camera to look under the bridge and tada! There's the line - on the ground under the bridge.

I also found another issue with bridges - if, with a "live connection" line to mouse pointer, you move the mouse off the bridge, the line was disappearing completely:

noline

In the image above, the mouse is about 1cm off the bridge (ie. on the grass at the bottom of the image, about 1cm away from the purple target circle that appears on the grass).

**Comment by krzychu124** [comment]
I think I know where is the problem with invisible lane connections. I will try to fix it, give me a minute 😉

**Comment by krzychu124** [comment]
Quick fix: (didn't checked monorails yet)

Zrzut ekranu (169)

The problem with rendering is that the lanes and markers are projected from above and depth is not taken into account while drawing new connection. It seems to be impossible to fix with actual shader 😕 

BTW shader used for rendering has name `CustomOverlayShapeBlend.shader` so looking only at name you see that its job is to lay shape over everything(with transparency) 😄 

I think this issue could be possibly fixed by changing that shader but currently there is no other to choose IIRC. I have an idea how to fix it but it will take some time to implement. I will try to explain details later.

**Comment by aubergine10** [comment]
Yes, I can confirm the bridge lines are now working. Would be great if there was some way to prevent them appearing on the ground below the bridge.

I've not been able to reproduce issue that @FireController1847  was having on ground level lines disappearing.

However I still get lines disappearing underground (during placement - in this case the green source is selected and the mouse is hovering over a white exit lane, the connection not yet made):

under

**Comment by aubergine10** [comment]
Oh, and love the white exit circles, that's made the whole thing surprisingly more usable as the exit lanes are now differentiated from entry lanes.

**Comment by aubergine10** [comment]
Update on bridge: "live connector line" still disappears if the mouse moves off the bridge. Placed lines are fine, but the connector line that follows mouse disappears when mouse is away from bridge.

BTW, it might be worth looking at the source for Move It mod as that does a load of stuff with shape overlay stuff - such as drag rectangle, square/rectangle/circle object selection shapes, curve lines, etc. Also, Quboid, TPB, Boformer, etc., are all active in the [dev discord](https://discordapp.com/channels/436608207788703753) (no idea if that link will work) and might have some ideas for alternate shaders or whatever.

**Comment by krzychu124** [comment]
Is junction area (where node is rendered on hover) always flat? (e.g. rectangular area in between pedestrian crossings below)
Zrzut ekranu (152)_LI

I have an idea to create there rectangular plane and render all lanes and markers at that level. 
It would looks like regular road markings but rendered on the fly. That should resolve problem with projection and doubled lanes and markers but still I need new shader do eventually render on that plane.

I will check source code and see what I could get from there

**Comment by aubergine10** [comment]
> Is junction area (where node is rendered on hover) always flat?

According to this, yes, the node area will always be flat, even if the terrain around it is not flat:

https://cslmodding.info/asset/network/#flat-junctions

**Comment by aubergine10** [comment]
Oh, yeah, that's another thing.... Some networks are nodeless.... Like several of the CSUR roads, and several of the Railway rail networks.

**Comment by aubergine10** [comment]
Junctions and corners are flat.

node flat

Not sure what the score is with inter-segment nodes (that don't really appear as nodes, they're just join between two segments). I guess in that instance you could just angle the rectangular surface that you're drawing on?

**Comment by krzychu124** [comment]
I am asking about that because I don't want to create situation where part of that rectangular plane would be overlapped by segment/node texture.

**Comment by aubergine10** [comment]
If you can get a filled rectangle rendering then should be possible to splat those over all types of node where lane connector can be used, to see if any are at weird angles or if they are all flat.

**Comment by FireController1847** [comment]
@aubergine10 Specs are the following:

- OS: Windows 10 Home 64-Bit, Build 17763
- CPU: 8-Core Intel i7-4700MQ @ 2.4GHz
- GPU1: Intel Graphics 4600
- GPU2: nVIDIA GeForce GT 740M
- GRAM: 2 GB
- RAM: 12 GB, Page: 12 GB
- DXv: DirectX 12

The launch flag does not make a difference (other than making it run much worse).

**Comment by VictorPhilipp** [comment]
@aubergine10 
> Testing lane connector in tunnels:
> While it works, there are some obvious issues:
> 
>     1. I can't see the roads (I had to just move mouse randomly until node selector appeared)

grafik

You can press "Page Down" to switch to underground view.

**Comment by VictorPhilipp** [comment]
> I think this could be the first new enhancement pushed to LABS first before moving to STABLE but we will see 😉

So the milestone should be 11.0 then?

**Comment by aubergine10** [comment]
@VictorPhilipp 

> You can press "Page Down" to switch to underground view.

Is that hard-coded to PageDown key or is it based on whatever key is assigned to one of the standard game shortcuts (eg. lower road, or whatever)?

**Comment by kvakvs** [comment]
When measuring performance please refer to micro/milliseconds per frame, not the FPS or FPS drop
It is more precise and allows to remove the the rest of the game logic and render from the measurement.
60 fps is 16.67 ms/frame, not all of it is available for TM:PE, game needs time too.

**Pull request closed without merging**
