### PR TITLE
What's New in TM:PE 11.6.5.0 TEST?

### PR DESCRIPTION
**Pull request by aubergine10**
TM:PE 11.6.5.0 is a pre-release to the TEST workshop page. It introduces full compatibility with Reversible Tram AI, and fixes some bugs.

- [Meta] Due to targeted malware, we are unable to provide support if you have mods by `Chaos`/`Holy Water`/`drok`, even if those mods are currently malware-free #1391 (TM:PE Team)
- [Meta] Compatible with Cities: Skylines v1.14.0-f9 #1387 (krzychu124)
- [New] Overlays mod option to show default speed when overriding segment/lane speeds #1404 (aubergine18)
- [New] Added API for external mods to query TM:PE mod options #1378 #1376 (aubergine18)
- [Mod] Compatible: `Reversible Tram AI` full compatibility #1386 #1353 (sway2020)
- [Mod] Compatible: `Supply Chain Coloring` workshop version only #1390 (aubergine18)
- [Mod] Compatible: `Transfer Broker BETA` workshop version only #1390 (aubergine18)
- [Mod] Incompatible: `TM:PE LABS` - discontinued (replaced by TM:PE TEST) #1390 (aubergine18)
- [Mod] Incompatible: `Traffic Manager (Curated)` - unsupported clone #1390 (aubergine18)
- [Mod] Incompatible: `TMPE:TrafficManager全部汉化` - unsupported clone #1390 (aubergine18)
- [Fixed] `StackOverflowException` due to `What's New` panel autolayout #1393 #1314 (krzychu124)
- [Fixed] Skip searching for best emergency lane for non-car vehicles #1408 (krzychu124)
- [Updated] Speed Limits: Always use themed icons in segment/lane modes #1404 (aubergine18)
- [Updated] Extend Harmony patch manager to allow manual patches #1386 #1361 (sway2020)
- [Updated] Various code clean-up and micro optimisations #1413 #1407 #1406 #1401 #1400 #1399 #1398 #1397 #1396 (egi)
- [Updated] Remove duplicate button clean-up code in lifecycle #1375 (aubergine18)
- [Updated] Internal restructuring of mod options code #1403 #1369 #1370 #1371 #1373 #1374 (aubergine18)
- [Updated] Translations for mod options, speed limits, traffic lights #1415 (krzychu124, freddy0419, Natchanok Kulphiwet, MamylaPuce, ipd, 田七不甜 TianQiBuTian, TwotoolusFLY_LSh.st, Never2333, 문주원 sky162178, MenschLennart, Chamëleon, John Deehe, Skazov, AlexofCA, CrankyAnt, Иван Соколов)
- [Updated] Update assembly info metadata #1417 (krzychu124)

Todo (once all merges are in):

- [x] Update `README.md`
- [x] Update `CHANGELOG.md`
- [x] Add dates/etc to `whats_new.txt`

Closes: #1387

### CODE REVIEW

**Comment by krzychu124** [comment]
Argh, I found another bug with regards to Aircraft behavior. They use combination of Emergency flag and some others and since aircrafts use our VehicleAI path it may call vanilla `FindBestLane` (no idea what it could break)

**Comment by aubergine10** [comment]
@krzychu124 The "find best lane" thing might be what's causing some of the weird aircraft paths such as:

* #1368
* https://www.reddit.com/r/CitiesSkylines/comments/srjpq1/nothing_to_see_here_just_a_jet_waiting_for/

**Comment by krzychu124** [comment]
It does not affect initial path but it may change part of the path later but theoretically since it's ~vanilla~ (correction... it's not - it reads Routing data, but we don't collect it for Planes iirc...), it should use the same segment and taxiways have only one lane for Plane vehicle type, same runways, so probably doesn't break anything, just wasting CPU time - it's dynamic thing calculated each simulation step (if vanilla and `Emergency2` flag present)

**Comment by aubergine10** [comment]
TM:PE 11.6.5.0 is ready for pre-release to TEST workshop page :)

**Comment by aubergine10** [comment]
lmk if https://github.com/CitiesSkylinesMods/TMPE/pull/1413 needs going in to this release and I'll update changelogs, otherwise it will be 11.6.5.1 milestone

**Comment by krzychu124** [comment]
I think we can push it with this one (didn't test changes 😅 )

**Comment by aubergine10** [comment]
ok, updated change logs / milestone / OP to include #1413

**Comment by aubergine10** [comment]
Sneaking in #1415 as well :) - latest translations from crowdin

**Review by krzychu124 — APPROVED** [review]

**Review by kvakvs — APPROVED** [review]

**Comment by aubergine10** [comment]
all ready for merge and TEST release 👍

**Comment by krzychu124** [comment]
Will do short test if everything works and merge when done

**Pull request merged**
