### PR TITLE
Add Chinese Simplified Icon

### PR DESCRIPTION
**Pull request by TianQiBuTian**
Add Chinese Simplified Traffic light & Road Icon

### CODE REVIEW

**Comment by TianQiBuTian** [comment]
Some TChinese texts are different from SChinese, but they do not affect reading and understanding.
If you want to add TChinese at the same time and no any more increase the mod file size. Maybe add a judgment at the change language.
|Text|SChinese|TChinese|IsSame|
|-|-|-|-|
|Counter|计时器|計時器|No|
|Change Mode|更改模式|更改模式|Yes|
|Auto|自动|自動|No|
|Manual|手动|手動|No|

**Known BUG(?):** If change game/mod language, doesn't apply(or load?) this language(or English default language).

**Comment by krzychu124** [comment]
Finally I found some time to finish pending tasks.
I've tested it, works without any issue and yeah it looks like a bug when it comes to switching language in-game. 
I'll create issue for later investigation. Thanks for contributions. 

Traffic lights UI will get complete overhaul so probably we won't use those textures, but who knows. I'm still thinking how it should look like.
<p align="center">

</p>
<p align="center">

</p>

P.S. I assigned you as proofreader on TM:PE _Crowdin_, so since now you can approve Chinese Simplified and Traditional translations😉

**Review by krzychu124 — APPROVED** [review]
👍

**Review by thebugfixnet — APPROVED** [review]
Code ist OK. I waited to approve as i know about the possible overhaul. But as @krzychu124 Approved and explained, I've no reason to hold back 😊

**Comment by TianQiBuTian** [comment]
So do you want to add Chinese Traditional at the same time? I have two idea:
1) Making Icons different from Chinese Simplified (maybe increase mod size)
2) Add a judgment (zh-tw = zh)
(You can see the difference between the two texts in the form above.)

**Comment by thebugfixnet** [comment]
@TianQiBuTian Thanks again for your support here. I think it would be an additional PR to decide how to implement what you mentioned. By this you could merge this pull request.

**Comment by DaEgi01** [comment]
why is this not merged already? :D

**Comment by DaEgi01** [comment]
@TianQiBuTian I will close this pull request since I opened a new one in our repo.
It was easier that way to fix the conflicts.
See https://github.com/CitiesSkylinesMods/TMPE/pull/1081

**Pull request closed without merging**
