### PR TITLE
What's new in 11.6.4.4?

### PR DESCRIPTION
**Pull request by aubergine10**
- [Meta] TM:PE 11.6.4-hotfix-4
- [Meta] Bugfix release targeting aircraft pathfinding, and info views.
- [New] Filtered despawn tools in Maintenance options tab #1341 #270 (aubergine18)
- [New] Ability to despawn specific vehicle categories when pathfinder is updated #1343 #485 (aubergine18)
- [Fixed] Aircraft stuck at taxiway junction #1338 #1329 (krzychu124)
- [Fixed] Aircraft taking off from taxiways #1338 #1327 (krzychu124)
- [Fixed] Unable to edit underground nodes in Traffic info view #1333 #1330 (aubergine18)
- [Updated] TM:PE toolbar closes in non-applicable info views #1333 (aubergine18)

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]

**Comment by krzychu124** [comment]
@aubergine10 When we plan to push next hotfix? I caught a cold and slowly catching up. I saw a change to 02 Feb. Theoretically might be even today, I just need to re-review and test your PRs

**Comment by aubergine10** [comment]
If today that's even better :) I'll update the changelogs.

**Comment by aubergine10** [comment]
11.6.4.3 tag not in releases btw - does creating a new release create the tag automatically or does that need doind separately?

**Comment by aubergine10** [comment]
I'll need to send another commit to update the byte array again before this #1339 can be merged (the pathfinder version check needs to add a byte option).

**Review by krzychu124 — APPROVED** [review]
👍

**Comment by aubergine10** [comment]
Ready for Lift Off! 👍

**Pull request merged**
