### PR TITLE
move lane connection manager to sub folder.

### PR DESCRIPTION
**Pull request by kianzarrin**
preparation for #354: 
- renamed the namespace/folder LaneConnectionManagerData to LaneConnection.
- moved LaneConnectionManager there.

in the next phase I will put `SubLaneConnectionManager` in the same place. there will be 2 instances of SubLaneConnectionManager. one for car and one for track.

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=354-prepare-cleaned)

Note: this PR has no functional change. its just moving files. But since it appears that I have changed a lot I decided not to mix it with my real changes to make review easier.

### CODE REVIEW

**Comment by kianzarrin** [comment]
I need to run some tests.

**Comment by kianzarrin** [comment]
test works.

**Review by kvakvs — APPROVED** [review]
Looking fine

**Review by chameleon-tbn — APPROVED** [review]
lgtm

**Review by aubergine10 — APPROVED** [review]
👍 

If this is waiting for 11.6.5.3 (as stated in sidebar) please add `Do not merge` label

(I'm fine with this going in 11.6.5.2 btw)

**Pull request merged**
