### PR TITLE
Improve mod options lifecycle in editors

### PR DESCRIPTION
**Pull request by aubergine10**
Compiled mod for testing: [TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=only-save-options-in-playmode)

TM:PE mod options should not be persisted while in editors, particularly the map/scenario editor (which are essentially savegames; any user starting new city from them would get unexpected options set = confuses users).

This PR makes the following changes:

- Mod options are never persisted in editors
    - Note: Other data such as road customisations is unaffected by this change
- When starting a new game, options will always be reset to default
- When loading a savegame, options are loaded normally
- If no data to deserialize, default options will be applied

Additionally:

- TTL tools can now be used in the map/scenario editor

Fixes: #1423
Updates: #1452
Updates: #1449
Updates: #959

### CODE REVIEW

**Comment by aubergine10** [comment]
@krzychu124 Is the Ci artifact thing still disabled?

**Comment by krzychu124** [comment]
How does that fix the issue? In asset editor that function is not used at all IIRC

**Comment by aubergine10** [comment]
> > @krzychu124 Is the CI artifact thing still disabled?
> 
> Enabled and rerun builds, we will see if works

Yup, working again :)

**Comment by aubergine10** [comment]
If is saving TM:PE options to map in the editor, then a better fix would be to check for `PlayMode` right at the outset in `TMPELifecycle':

```csharp
public override void OnSaveData() => if (PlayMode) Save();
```

**Comment by krzychu124** [comment]
I'll check the save loop later to see what is going on

**Comment by krzychu124** [comment]
Is it ready for review? After looking how it works it seem that should fix the issue

**Comment by aubergine10** [comment]
Was it actually saving options/etc to map in Map Editor?

**Comment by krzychu124** [comment]
Map created in the map editor is like regular save game but running in special mode to limit interactions. Once created, new games created from it becomes detached from the source so any later updates to original map won't affect games that has been already created.
I've not tested it yet, but knowing that it makes sense.

**Comment by aubergine10** [comment]
Should I move the `PlayMode` check to the `TMPELivecycle.OnSaveData()` as mentioned in comment above?

I have no clue how road customisation data gets saved in map/asset editor (ie. stuff we do want storing in the map/asset file) so not sure if it will have unintentional effects.

**Comment by aubergine10** [comment]
Also... should I add something that checks `NewGame` or `NewGameFromScenario` and if true prevent loading options (and other?) data?

**Comment by krzychu124** [comment]
> Should I move the `PlayMode` check to the `TMPELivecycle.OnSaveData()` as mentioned in comment above?
> 
> I have no clue how road customisation data gets saved in map/asset editor (ie. stuff we do want storing in the map/asset file) so not sure if it will have unintentional effects.

If you mean `if (PlayMode) Save();` -> that will completely break saving other things in the map editor (arrows, lane connections etc.)

> should I add something that checks NewGame or NewGameFromScenario

yes, that might help if the user subscribed to already published maps on workshop
>  (and other?)

Which other? AFAIK Timed traffic lights could be enabled in the map editor since created "map" is in 99% a regular savegame, but still disabled in asset editor because asset segments/nodes needs to be remapped after creation (asset editor segment/node ids are just the template to mirror settings) and we don't have mapper for TTL

**Comment by aubergine10** [comment]
Tweaked how it works - see OP for details.

**Review by kvakvs — APPROVED** [review]
Confused how it fully inverts the logic, but trust you on this :)

**Comment by krzychu124** [comment]
> @kvakvs Confused how last commit fully inverts the logic, but trust you on this :)

Previous commit had no sense (didn't notice it while reviewing) - mode cannot be equal to `NewGame` and `NewGameFromScenario` at the same time 😄

**Comment by aubergine10** [comment]
Options should be using defaults in following situations:

- When in any of the editors
    - This ensures things like TTL are properly disabled based on the way defaults now work
- When a new game is started (either from map or scenario)
    - This prevents issues arising from stuff like #1423

If the user is loading savegame of existing city, the options will be pulled from savegame as usual.

**Comment by aubergine10** [comment]
@krzychu124 any further comments on this?

**Comment by krzychu124** [comment]
> @krzychu124 any further comments on this?

I'm going to test it when I clear my github notification list :)

**Comment by aubergine10** [comment]
Need some additional tweaks as per https://github.com/CitiesSkylinesMods/TMPE/issues/1452#issuecomment-1057571113

brb

**Comment by aubergine10** [comment]
Waiting for more review prior to merge.

**Comment by krzychu124** [comment]
Wiki needs an update because features listed in the table below are **enabled** by default 😉 

image

As of PR, tested scenario, looks like it nicely saves and loads tmpe feature settings, options are not loaded unless I already saved wrong settings with previous version of the mod. Still need to test map save and restore of TTL, just in case if you haven't already.

**Comment by aubergine10** [comment]
> Wiki needs an update

Done :)

> Still need to test map save and restore of TTL, just in case if you haven't already.

I've only tested the scenario editor, I've not yet tested map editor.

**Comment by kianzarrin** [comment]
it does fix the icons in new game 
image

**Comment by krzychu124** [comment]
> it does fix the icons in new game image

Yeah, I already merged in atlas fix from #1451 :) 
We didn't test saving/loading settings in Map editor and that's probably the last thing that needs to be tested before merging this.

**Review by krzychu124 — APPROVED** [review]
Working in map editor and scenario editor, loads and saves all tm:pe features, mod options are not saved 👍 Works as expected in the Asset/intersection editor.

**Pull request merged**
