### PR TITLE
TMPE tool should behave when returning from free camera view

### PR DESCRIPTION
**Pull request by kianzarrin**
User presses Escape to return from the free camera view. This switches current tool is set to whatever it was before entering the free camera view.

### Problem:
This can re-enable TMPE tool without displaying the TMPE panel. This behaviour confuses Biffa:
https://cdn.discordapp.com/attachments/545066674605391882/712986161936728124/CS_Fixit_-_TMPE2a.mp4

### Reason:
~~Threading extension hides TMPE menu if TMPE is not the tool.~~
We do not view the Panel when TMPE tool is enabled.

### Need:
TMPE must act like other tools and TMPE panel should be visible when returning from free camera view.

### Solution:
Threading extension is the wrong place to show/hide TMPE panel.
this must be done from inside TMPE tool.

### Problem2:
TMPE panel disappears when user presses escape in free camera view.

### Reason:
Threading extension captures the Escape key and closes TMPE.

### Need:
TMPE must ignore Escape key when in free camera mod.

### Solution:
Handle Escape the same way other tools handle it: from `TrafficManagerTool.OnToolGUI()` 

PS: I deleted `ThreadingExtension.OnUpdate()` because it does not do anything anymore.

### CODE REVIEW

**Comment by aubergine10** [comment]
Code looks good, I'll need to test in game.

**Comment by kianzarrin** [comment]
There was a problem that when I switched to another tool TMPE panel did not disappeared. I fixed that problem.

**Comment by kianzarrin** [comment]
@aubergine10 Can you please approve the new code I put in? I can merge this ...  but ...

**Comment by aubergine10** [comment]
I'll test in-game today.

**Comment by aubergine10** [comment]
Found some possible issues when testing in-game.

Note: I'm using [First-person Auto-Walking](https://steamcommunity.com/sharedfiles/filedetails/?id=659877005) mod, rather than the more commonly used First Person Camera (Updated) mod.

First, if a tool is active, the overlays are still rendering in first person cam. At the very least this is bad for fps.

image

Second, I press `Esc` to exit the first person cam, and TM:PE toolbar still visible etc. (this is correct).

However, when I press `Esc` to exit the toolbar, the toolbar does get closed but the `Pause Menu` is also displayed. It's like the UI fsm somehow got confused.

**Comment by aubergine10** [comment]
Actually, it doesn't look like the TM:PE toolbar is getting closed; I suspect it thinks it's already closed (due to `Esc` press while exiting the first person cam):

image

Steps:

1. Open TMPE toolbar, select lane connector tool (for example)
2. Tab key= go in to first person autowalking cam
3. Esc key = exit first person cam
4. Esc key = should only close TMPE toolbar, but it doesn't; instead it shows Pause Menu

**Comment by kianzarrin** [comment]
@aubergine10 I am unable to use your first-person auto walk mod. When I press that nothing happens. No exceptions either???? (when I pressed tab to bulldoze it throws some exception. I did sub out of that though and still, I had the problem).
In any case, those lane connections will not get rendered if the Traffic manager tool is not the active tool. 

- Can you reproduce this problem with TMPE labs as well?
- If so let's fix this in another pull request. I think the fix would be for first-person auto walk mod to change tool to default. Can't say for sure if I cannot use the mod.

**Comment by kianzarrin** [comment]
@aubergine10 The problem you raised is due to an exception preventing the rest of the code from running:
```
NullReferenceException: Object reference not set to an instance of an object
  at ColossalFramework.UI.UIComponent.OnResolutionChanged (Vector2 previousResolution, Vector2 currentResolution) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.OnResolutionChanged (Vector2 oldSize, Vector2 currentSize) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.OnResolutionChanged (Int32 oldSize, Int32 currentSize) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.OnResolutionChanged () [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.OnEnable () [0x00000] in <filename unknown>:0 
UnityEngine.Behaviour:set_enabled(Boolean)
ColossalFramework.UI.UIView:ShowView(Boolean)
ColossalFramework.UI.UIView:Show(Boolean)
IINS.AutoWalking.MonoCamera:UpdateFreeCamera()
IINS.AutoWalking.MonoCamera:OnDestroy()
IINS.AutoWalking.WalkingCamera:OnDestroy()
 
(Filename:  Line: -1)

NullReferenceException: Object reference not set to an instance of an object
  at ColossalFramework.UI.UIComponent.OnResolutionChanged (Vector2 previousResolution, Vector2 currentResolution) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.OnResolutionChanged (Vector2 oldSize, Vector2 currentSize) [0x00000] in <filename unknown>:0 
  at ColossalFramework.UI.UIView.Update () [0x00000] in <filename unknown>:0 
```
To prevent scope creep can you please ignore this issue. If there are no other issues please approve this PR.

**Comment by kianzarrin** [comment]
@aub I created #958 to track the issue you raised

**Comment by aubergine10** [comment]
Also, I tested with current LABS version and there are similar (but slightly less bad) issues with that too.

**Comment by kianzarrin** [comment]
@aubergine10 I think the issue is with TMPE.
CS Camera view changes the tool so it disables TMPE and avoids the problem.
auto-walk mod does not change the tool (as it should) and TMPE also has null reference exception. both of these together leads to #958

**Pull request merged**
