### PR TITLE
TM:PE settings not copy pasted in-game

### LINKED ISSUE #1300: `MoveItIntegration` plugin - settings are not copy-pasted on segment clone with `MoveIt`
### Describe the problem
Some TM:PE Settings are lost/ignored after copy&paste with **MoveIt**, looks like data is transferred so it should correctly save data in Asset Editor as AssetSerialization thingy uses the same code.

### Steps to reproduce

1. Add few segments
2. Setup some TM:PE settings (lane arrows, speed limits, junction restrictions, priority signs)
3. Select and copy segments with TMPE settings, observer result

image

Transferred: 
- Lane connections,
- Vehicle restrictions,
- Parking restrictions,

image

Not transferred:
- Lane arrows (not transferred, not recalculated based on lane connections),
- Speed limits (theoretically something is transferred when logging transfer data but also not applied),
- Junction restrictions (looks like returns false at some point during validation when transferring settings to new segments),
- Priority signs (not sure yet, might be similar to junction restrictions),

I've prepared dirty hack (few C# reflection lines) to force **MoveIt** to fetch again integration plugins after hot-reload since it was using older version which resulted in lots of null refs -> accessing destroyed instances via static methods. 

**Integration plugin was referencing static field of specific Assembly version so it has access to nullified static field value from before hot reload since the old Assembly still exist in memory!**

### PR DESCRIPTION
**Pull request by krzychu124**
Fix typo resulting in wrong lane id while applying settings on pasted segments with **MoveIt**

~~Partial fix for #1300, other bugs are simulation timing related -> require queuing and applying change records in the next `SimulationStep` instead of current (node flags are not fully initialized right after creation)~~

Full implementation of fix for transferring TMPE settings with use of MoveIt integration plugin!
Closes #1300 

[Build zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=speedlimit-copy-paste)

### CODE REVIEW

**Review by kvakvs — APPROVED** [review]

**Comment by krzychu124** [comment]
I've added a fix to resolve all issues with integration plugin

**Review by chameleon-tbn — APPROVED** [review]
Lgtm

**Comment by aubergine10** [comment]
Is there possibility of similar issues arising when user plops assets that contain TM:PE settings (defined in asset editor)?

**Comment by krzychu124** [comment]
> Is there possibility of similar issues arising when user plops assets that contain TM:PE settings (defined in asset editor)?

I've created one simple intersection with all possible settings (using this build) and everything works in-game. Ovelay caching is broken so when you use it to check if everything was restored you need to switch tools to force refresh. I plan to fix overlays in 11.7.x, not a big deal for now.

**Review by aubergine10 — APPROVED** [review]
Tested in-game for a bit and seems to work fine.

**Comment by krzychu124** [comment]
> Is there possibility of similar issues arising when user plops assets that contain TM:PE settings (defined in asset editor)?

Correction -> issue still exist when IMT or NCR is enabled. I found the problem and solution.
Merging...

**Pull request merged**
