### PR TITLE
What's New in TM:PE 11.6.4.5 ?

### PR DESCRIPTION
**Pull request by aubergine10**
This release makes some refinements to error checking/logging, and refines the pathfinder edition check/warning.

- [Meta] TM:PE 11.6.4-hotfix-5
- [Meta] Updates to error checking/logging, and refine pathfinder edition checks
- [Updated] Catch and log errors in savegame options save/load #1345 (aubergine18)
- [Updated] Pathfinder edition check refinements #1347 (aubergine18)
- [Updated] Reduce severity of some normal log messages #1348 #1350 (aubergine18)

### CODE REVIEW

**Comment by aubergine10** [comment]
@krzychu124 is it possible to do a release to workshop with these changes today? hopefully it will make support a bit easier

**Comment by krzychu124** [comment]
Yeah, I need to do something and I'll start merging everything

**Review by krzychu124 — APPROVED** [review]

**Comment by krzychu124** [comment]
@aubergine10 anything else to add?

**Comment by aubergine10** [comment]
Yup, 1 sec

**Comment by aubergine10** [comment]
done

**Pull request merged**
