### PR TITLE
Modify how info views affect TM:PE

### LINKED ISSUE #1330: Lane Connector isn't working on Underground Metro Tracks
### Describe the problem
For some off reason, I am unable to utilize the lane connector for underground metro tracks as I had done before. Strangely enough, all prior connections that I've implemented are still active, but are invisible. Typically you'd hover over a white circle and thus edit lane connections. For my underground metro, the circles are orange and when I hover over it this symbol "🚫" pops up.

### Steps to reproduce

1. Load game
2. Click Lane Connector
3. Hover over underground metro tracks

### Log files

N/A

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2733863566

### Screenshots?

https://imgur.com/a/Tk4UnnB

### Notes or questions?

N/A

### PR DESCRIPTION
**Pull request by aubergine10**
Closes #1330

- TM:PE is allowed to function in certain info views
- Those info views will be treated as underground mode by tools (ie. tunnels can be customised)
- All other info views close TM:PE toolbar/tool
- It's event driven so should not affect performance
- After closing info view, TM:PE toolbar is not restored - this is intentional; it just seemed weird while testing in game

Permitted info views:

* `Undeground`
* `Traffic`
* `TrafficRoutes`

I've tested each tool, including mass edit (Adjust Roads Panel), and they seem to work as expected.

The mass edit tool already closes TM:PE toolbar but has it's buttons on the vanilla UI so I left that functionality untouched.

[TMPE.zip](https://ci.appveyor.com/api/buildjobs/qt3x4893suv7rq47/artifacts/TMPE.zip)

### CODE REVIEW

**Comment by aubergine10** [comment]
@krzychu124 can this one go in the hotfix too?

**Comment by krzychu124** [comment]
> @krzychu124 can this one go in the hotfix too?

I don't think it works as user could expect it
Example:
I can select lane connector tool, then enter Traffic or Traffic Routes View but then tool will allow only for setting underground nodes (speed limits too), to select normal nodes I need to hit pageUp so basically exit that info view

(traffic routes view)
image

image

image

**Comment by aubergine10** [comment]
So in these views it should allow user to change both underground _and_ overground?

**Comment by aubergine10** [comment]
The updates to show better overlays in undeground/overground are planned for 11.6.5 (see milestone). This PR is just to allow:

1. Editing of underground in Traffic info view
2. Treat Traffic Routes info view as allowed underground view (more work likely in 11.6.5)
3. Close TMPE toolbar on non-applicable underground views

**Comment by krzychu124** [comment]
ok, in that case it works as it should

**Review by krzychu124 — APPROVED** [review]

**Comment by aubergine10** [comment]
Pls merge - I'll need to send another commit to the PR #1343 which is currently using the same byte index in OptionsManager as this PR #1333

**Pull request merged**
