### PR TITLE
flag extension

### PR DESCRIPTION
**Pull request by kianzarrin**
previously IsFlagSet was using CO's extension which allocates heap memory in each frame.
I introduced our own IsFlagSet for every Enum [that we use] to avoid using heap memory.

### CODE REVIEW

**Review by krzychu124 — APPROVED** [review]

**Review by DaEgi01 — APPROVED** [review]
very nice!
why internal though?

**Comment by krzychu124** [comment]
@kianzarrin, you can merge it if you think is complete 😉

**Comment by kianzarrin** [comment]
@DaEgi01 
> why internal though?

why not internal?

**Comment by DaEgi01** [comment]
> @DaEgi01
> 
> > why internal though?
> 
> why not internal?

Because when I look at it I see nothing about this function that is specific to TMPE.
Its more of a CSUtil.Commons thing that should be public for other assemblies to use freely.
But I don't mind leaving it as is, just thought that you have particular reasons maybe.

**Pull request merged**
