### PR TITLE
Parking AI confused in large parking lots

### LINKED ISSUE #352: Parking AI broken after Campus Update
### Description
Cars no longer look for parking spots on Parking Lot Roads and Parking Garages (such as the recently released University Parking Garage by KingLeno). Cars still park on regular roadside parking as usual. This started to occur after the Campus update. When loading a pre-Campus save with existing parked cars using the Parking AI, updating the parking spots in any form (such as moving the height on MoveIt with Page Up) will cause all the cars to disappear without a trace. Roadside parking updates as normal. There also seems to be an issue where cars disappear one by one even without any actions. Of course, Parking AI is enabled in the TM:PE settings; global configuration has been reset multiple times with no effect. There is a video that shows the effects of this bug.

### Reproduction Steps
1. Load a pre-Campus save with existing cars parked in Parking Lot Roads/Parking Garages.
2. Update the parked cars by moving/adjusting a nearby node using MoveIt.
3. Cars disappear without a trace.

### Mod List
- TM:PE 10.20
- 81 Tiles (Fixed for C:S 1.2+)
- Achieve It!
- Adaptive Prop Visibility Distance
- Additive Shader
- Advanced Stop Selection
- Advanced Vehicle Options
- AnimUV Params
- Automatic Bulldozer
- Building Anarchy
- Building Eyedropper Tool
- Building Panel Already Exists
- Camera Positions Utility
- Cargo Hold Fix
- CSL Map View
- Custom Animation Loader
- Daylight Classic
- Decal Prop Fix
- Dynamic Resolution
- Environment Changer
- Extra Landscaping Tools
- Extra Train Station Tracks
- Farther Zoom
- Find It! 1.5.4
- Fine Road Anarchy 1.3.5
- Fine Road Tool 1.3.7
- Hide It!
- Improved Public Transport 2 [r4.3.1]
- Klyte Commons
- Less Steam 
- Loading Screen Mod
- LOD Toggler
- More Advanced Toolbar
- Move It 2.4.1
- Network Extensions 2
- No Problem Notifications
- No Radioactive Desert and More!
- NotSoUniqueBuildings
- Parallel Road Tool 1.3.0
- Plop the Growables
- Ploppable Asphalt
- Ploppable RICO
- PollutionRemoverMod
- Precision Enginnering
- Prop & Tree Anarchy
- Prop It Up! 1.4.4
- Prop Line Tool
- Prop Precision 1.0.1
- Prop Snapping
- PropRotatingParams
- Quay Anarchy
- Real Time
- Segment Slope Smoother
- Sharp Textures
- Smart Intersection Builder
- Stop Hider
- Theme Decals
- Theme Mixer
- Touch This! Tool 2.0.2
- Tram Station Track
- Transparency LOD Fix + Cloud Assets Enabler
- Tree Fire Control
- Tree LOD Fix
- Tree Snapping
- UK Roads
- Ultimate Level of Detail
- Unlimited Money
- Unlimited Oil and Ore
- Unlimited Soil
- Unlock All
- Vanilla Trees Remover
- WG Citizen Lifecycle Reblance v2.6

### Output Log
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3244472/output_log.txt)

### Savegame (Optional)
https://steamcommunity.com/sharedfiles/filedetails/?id=1758698168

### Video (Optional)
https://www.youtube.com/watch?v=w6cPFHWxTn8

### LINKED ISSUE #423: Possible parking issue with "Parking Roads" assets
### Details

Using ~~LABS 10.21.1~~ STABLE 10.20 <-- that's the problem

> **leaderofthemonkeys** (Paradox):  
> i've been having problems recently w parking, cars just won't park in parking spaces, no matter what i do they won't use them
> on street-parking is a-ok
> but my parking lots remaiuin empty (yes, parking ai is on)
> it's super late, about to go to sleep, so not sure what you want to analyze this

Later:

> i investigated a bit more, seems like it's only badi_dea's parking spaces  
> https://steamcommunity.com/sharedfiles/filedetails/?id=1293869603

### Logs

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375209/output_log.20.txt) 239,000+ lines!!! by far biggest log file I've ever seen

[TMPE.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375212/TMPE.1.log)

### Save game

[QuickSave20190709233553843.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3375240/QuickSave20190709233553843.zip)

Note: Looking at the log file, lotm has 64GB RAM, so I suspect you'll need massive page file to load that savegame. There are truly insane numbers of workshop assets.

### Mods

Bold lines are potentially broken / outdated mods (unlikely to be cause of the issue above, but flagging them up anyway).

Note: Roads United Core+ breaks toll booths; there are some mods that require it (highlighted bold) which should be disabled or removed.

* UnlimitedMoney
* UnlimitedOilAndOre
* UnlimitedSoil
* UnlockAll
* **DaylightClassic (locally installed for some reason)**
* **MoveIt (locally installed for some reason)**
* **PropUnlimitor (locally installed for some reason; also I suspect this is a broken mod)**
* 812125426 - NExt2
* 724382534 - One way train tracks
* 1530376523 - Railway replacer
* 1552053911 - TrailerVariation Loader
* 1546357276 - Industries Vehicle Converter
* 1386697922 - Garbage Bin Controller
* 814498849 - Improved Content Manager
* 1637106958 - Lock Forestry
* 1603398633 - Flag Params
* 820157360 - Spawn Points Fix
* 633547552 - Roads United Core 2.0
* **1586027591 - TinySegments 2.0 (can break traffic lights etc)**
* 1585691173 - HDRI Haven Cubemap Pack
* 1536223783 - Hide Selectors
* 1540147921 - Grid be Gone
* **837112310 - Roads United: Europe (requires Road United Core+ mod)**
* 685719710 - More Shortcuts
* 954067599 - PropRotating Params
* 1369729955 - Customize It!
* 769744928 - Pollution, Death, Garbage and Crime Remover Mod
* **1147015481 - No Crosswalks - Remove Crosswalks/Crossings - Including Road Assets (issues reported with Industries DLC)**
* 1117087491 - Remove Road Props
* 1412844620 - Realistic Walking Speed
* 1394468624 - Advanced Stop Selection (ex MTSE)
* 1388613752 - Tree Movement Control
* 780720853 - Vehicle Effects 1.8.1
* 1349895184 - Tree LOD Fix
* 1324539315 - Land Ships
* 531738447 - CSL Show More Limits
* **553501635 - Sub-Buildings Enabler (DEPRECATED)**
* 734025380 - Configure Outside Connections' Limits
* 785528371 - Cinematic Camera Extended
* 952542692 - Airport Road Light Remover
* 949504539 - SingleTrainTrackAI
* 932490392 - Track My Time
* 595017353 - More Flags ( + flags replacer )
* **932192868 - Road Options (Road Colors Changer ++) (possible conflict with No Crosswalks mod)**
* 775021554 - Theme Mixer
* 922939393 - Transparency LODs Fix
* 911295408 - Prop Scaling 0.3 \[Experimental ALPHA]
* 917543381 - No Problem Notifications
* 910440715 - Plant Scaling
* 903347963 - Transparent Selectors
* 883332136 - Any Road Outside Connections
* 881291183 - Ploppable Asphalt +
* 895061550 - Theme Decals
* 794268416 - Steamy - More Steam controls
* 427258853 - Crossings
* 497033453 - Unlimited Outside Connections (Beta)
* 445589127 - Precision Engineering
* 572888650 - Remove Need For Power Lines
* 576997275 - Remove Need For Pipes
* **821539759 - Disable Zone Check (unmaintained)**
* 406102887 - Super Demand
* 552324460 - No Fires
* 621002682 - No Questions Asked
* 515489008 - Extra Train Station Tracks ( ETST )
* **541673195 - Resident Travel Rebalance v1.1 (not compatible with WG Citizen Lifecycle Rebalance mod below...)**
* 654707599 - Citizen Lifecycle Rebalance v2.6
* 512314255 - More Network Stuff
* 426163185 - Realistic Population and Consumption Mod v8.4.0
* 409069482 - Fill The Houses
* 781767563 - Extended InfoPanel
* 793346248 - Decal Hover Area
* 438449058 - Building Eyedropper Tool
* 768213484 - Subtle Bulldozing, Dragging and More
* **442167376 - Advanced Vehicle Options (AVO) (old version, doesn't properly categorise Industries vehicles)**
* **472128528 - Larger Footprints (Snowfall) (marked as game breaking in workshop)**
* 611254368 - Environment Changer (+ Improved Theme Selection )
* 707497031 - Tram Station Track
* 465127441 - Airport Roads
* 774449380 - Catenary Replacer
* 1094334744 - Procedural Objects
* 1591584836 - HDRI 2K Cubemap Pack
* 1721492498 - Cargo Hold Fix
* 1747800340 - Building Theme: University City Districts
* 928128676 - Improved Public Transport 2
* 934994075 - Service Vehicle Selector 2
* 576327847 - 81 Tiles (Fixed for 1.2+)
* 412149127 - Font Selector
* 1591417160 - Hide It!
* **583429740 - Traffic Manager: President Edition \[STABLE]**
    * v10.20 doesn't include any of the parking fixes
* 1789133988 - Route Shields for PO
* 586012417 - Ploppable RICO
* 815103125 - Extra Vehicle Effects (Plugin for Vehicle Effects Mod)
* 455403039 - Unlimited Trees Mod v1.12
* 912484109 - Flood Damage Control \[BETA]
* **763684437 - Roads United: North America PLUS (requires Roads United Core+ mod)**
* **848896702 - Roads United: US Edition - Reworked (requires Roads United Core+ mod)**
* 973512634 - Sort Mod Settings
* 1776052533 - Stops & Stations
* 1758376843 - Network Skins 2 (Beta)
* **1565201461 - Roads United: US Reworked 2018 (requires Roads United Core+ mod)**
* 1771841274 - HDRI Haven Cubemap Pack 2
* 812713438 - Dynamic Resolution (Fixed for 1.9!)
* 552309905 - No Abandonment
* 412146081 - PostProcessFX v1.9.0
* 1680642819 - Ultimate Level Of Detail (ULOD)
* 1372431101 - Painter
* 1183931915 - Cubemap Replacer
* 458519223 - Unlock All + Wonders & Landmarks
* 924884948 - Plop the Growables
* 878991312 - Prop it Up! 1.4.4
* 793176674 - Sharp Textures
* 791221322 - Prop Precision
* 787611845 - Prop Snapping
* 694512541 - Prop Line Tool [PLT] (vAlpha)
* 650436109 - Quay Anarchy
* 465318661 - Toggleable Whiteness
* 689937287 - Surface Painter
* 1562650024 - Rebalanced Industries
* 1274199764 - Network Tiling
* 1209581656 - Relight
* 812107110 - Less Steam
* 762520291 - Shadow Strength Adjuster
* 672248733 - Ultimate Eyecandy v1.5.2
* 593588108 - Prop & Tree Anarchy
* 564141599 - No Seagulls
* 530771650 - Prefab Hook (Mod Dependency)
* 406354745 - Speed Slider \[v2]
* 1658679290 - Forest Brush v1.2.5
* 1645781000 - Elektrix's Road Tools 2.0
* 898480258 - Camera Positions Utility
* 837734529 - Find It!
* 802066100 - Fine Road Anarchy
* 767233815 - Decal Prop Fix
* 651322972 - Fine Road Tool
* 523824395 - Clouds & Fog Toggler
* 502750307 - Extra Landscaping Tools
* 833779378 - Loading Screen Mod \[Test]
* **1597852915 - More Advanced Toolbar (bit buggy & laggy)**
    * Suggest: Resize It! mod by Keallu instead
* 845665815 - CSL Map View
* 450877484 - Mod Tools

Will update lotm about issue then close ticket.

### LINKED ISSUE #924: Parking AI gets very confused in large parking lots
### Describe the problem
Using the "Big Parking Lots" road assets (https://steamcommunity.com/sharedfiles/filedetails/?id=2115188517), the parking AI will sometimes get extremely confused, and drive in circles causing huge gridlock - even while there are plenty of spots available.
(I've also noticed the AI seems to try to always park in a certain area of the lot - perhaps circling many times - even though there are plenty of open spaces, overall)

### Steps to reproduce

1. Subscribe to BPL assets (https://steamcommunity.com/sharedfiles/filedetails/?id=2115188517)
2. Enable TMPE Parking AI
3. Set up a parking lot near something that will have lots of traffic (Metro/Rail depot, for example)

### Log files

Not sure which types of logs you'd like, as this wasn't really an "error", but just seems to be an issue with how the simulation runs.

### Savegame?

I can get you a saved game if you want, but this happens in all sorts of situations for me.  It's pretty straightforward to set up a large parking lot near an asset that has high parking demand.

### Screenshots?

https://i.imgur.com/U1xbjxB.jpg

### Notes or questions?
I have briefly corresponded w/ the BPL author, but I don't think there's anything he can do to influence how the Parking AI behaves, but if there is, I can relay that to him (I will also send him the link to this GitHub Issue)

### LINKED ISSUE #1394: Possible issue with 'Dark Asphalt' Big Parking Lot assets
### Describe the problem

A user on Steam has reported that the `Dark Asphalt` versions of Big Parking Lots aren't being used.

image

I'm already using the normal BPL assets so I'll do some testing tomorrow to see if I can reproduce the issue.

EDIT: Link to assets in workshop https://steamcommunity.com/sharedfiles/filedetails/?id=2132447662

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #924, fixes #423, fixes #352, fixes #1394

Proposed change should result in better detection of end PathPosition which vehicle should reach before starts flying to parking spot. It's not perfect solution but user reports say that change in behavior is significant and parking location decisions are much better compared to current public version.

I'm not entirely sure if we should completely remove `endPos` argument or only for specific cases like e.g.: residents calculating parking spot in advance to mimic the case: _"I live in that city long time, I know best parking spots"_

---

Update (4th Aug/22): 
- cherry-picked @DaEgi01 impl. of CW spiral,
- fixed issue of preliminary loop exit of first loop finds parking spot in first iteration of the loop - first hit might be quite inaccurate due to how segment grid search works in general, 
- applied randomized spiral detection for parking/path position search where makes sense,
- pass parking building position to increase accuracy of `PathPosition` search (new end position before car switch to "drifting mode")

---

Build [zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=parkingAI-starts-parking-too-early)

### CODE REVIEW

**Comment by krzychu124** [comment]
No more _low-hanging fruits_. Ready for review.

**Review by DaEgi01 — APPROVED** [review]

**Review by kianzarrin — APPROVED** [review]

**Review by kvakvs — APPROVED** [review]
Code looks fine, but how do I test the parking? They parked before, they park now, how do I know it works?

**Comment by krzychu124** [comment]
> Code looks fine, but how do I test the parking? They parked before, they park now, how do I know it works?

Probably the easiest way is to observe parking spots that have two potential entrances, one banned for cars and much closer then other one not restricted but objectively requires longer path. Before the fix they were more likely to stop moving before entering restricted segment and fly the remaining distance to the parking spot. Now they should take longer, more realistic route and also fly only if necessary (e.g. only within the segment width/length).

Example scenario where I actually noticed the problem and tested it multiple times: cim going from blue building. Parking spaces are only available at the top. Red path is possible with old version (8/10 attempts), green is when using this version. Notice car ban.
 
image

**Review by chameleon-tbn — APPROVED** [review]
👍

**Pull request merged**
