### PR TITLE
On Screen Display with Help and Keyboard Hints

### LINKED ISSUE #410: On-screen display mod
I've been pondering this for over a year, but a comment from @kvakvs just prompted me to post the idea...

> **kvakvs:** One problem. I need some GUI space (a tooltip or a floating window?) to display hints, keyboard shortcuts and current help. A tooltip would be great, maybe.

Have you ever played [Railway Empire](https://store.steampowered.com/app/503940/Railway_Empire/)? It's an ok game if you like trains, it's trying to be like [Sid Myers Railroads](https://store.steampowered.com/app/7600/Sid_Meiers_Railroads/) but lacks the gamification. Anyway, one thing that it does excel at is it's small on-screen overlay at bottom of screen that shows context-sensitive info such as keyboard shortcuts and mouse clicks:

image

(That was screen-grabbed from youtube video, so apologies for low quality. If you look close at the mouse buttons you will notice the applicable button is highlighted yellow; it's much clearer in game).

Anyway, I think we need something like that for TM:PE. Considering the keybind stuff and new UI rendering stuff, I think we can easily achieve that now.

What I would suggest, however, is that it's implemented as separate mod if that's possible, as I believe this sort of thing would benefit LOTS of other mods. They could communicate with the OSD mod via a game object or something.

The OSD could be used to display context-sensitive help, keyboard / mice interactions, progress bars, all sorts of stuff. As a separate mod it could just grow over time to facilitate extra features.

It should be optional though; some users will not want OSD.

Another game to check out for its exemplary UI is [Rise of Industry](https://store.steampowered.com/app/671440/Rise_of_Industry/) - I think this is some of the best - clearest, crispest - UI I've seen in any video game I've played.

### PR DESCRIPTION
**Pull request by kvakvs**
- [x] ~A panel attached to the Main Menu Panel~
  - [x] ~Repositions itself when the main menu is moved~
- [x] Tools can set the tooltip and keyboard shortcuts to show, or clear them
- [x] Clears when the tools are deselected
- [x] Can be dragged around
- [x] Means to close and show again
  - [ ] Add branding (small logo or a "TM:PE" label)
- [ ] Support longer strings and word wrapping
- [ ] Add support for tools
  - [x] Lane connector
  - [ ] Lane arrows
  - [ ] Junction restrictions
  - [ ] Speed limits
  - [ ] Car/train restrictions
  - [ ] Parking restrictions
- [x] Add the way to show/hide
- [x] Translations

image

Closes #410

### CODE REVIEW

**Comment by aubergine10** [comment]
Not keen on it being locked to menu panel.

IMO it would be better to put it bottom of screen above the vanilla UI bars, but allow dragging with right-click.

**Comment by kvakvs** [comment]
There is a catch, some users have so many mods that i have no idea where the bottom UI bars end.

**Comment by kvakvs** [comment]
OSD panel is now free floating, can be dragged, can be hidden using the small ? button on the TM:PE panel. The ? button has a tooltip. Saves the position and visibility, also uses translations.

**Comment by aubergine10** [comment]
Can this PR be closed as the OSD is being implemented via #819

**Pull request closed without merging**
