### PR TITLE
pedestrian zone roads have lower priority.

### PR DESCRIPTION
**Pull request by kianzarrin**
image
in the image above setting high priority road on the junction makes the pedestrian zone road high priority.
it should be the other way around.

### CODE REVIEW

**Comment by kianzarrin** [comment]
I didn't find the old cold all that useful. I think the new code is much better. there are 5 class levels which corresponds to the road goes under (technically is determined by UICategory but it corresponds to class level).
image

**Comment by krzychu124** [comment]
Honestly I don't know how to reliably detect "level" of road e.g.: to figure out which should have higher priority etc.
Such thing could help with auto ttl, auto priority rules and probably a lot more things. There was a suggestion about either auto priorities or auto traffic lights but I can't find (maybe I just have no luck in search keyword 😄 )

**Comment by kianzarrin** [comment]
> @krzychu124   Such thing could help with auto ttl, auto priority rules and probably a lot more things. There was a suggestion about either auto priorities or auto traffic lights but I can't find (maybe I just have no luck in search keyword 😄 )

Just look at my code. I use class level.

**Review by chameleon-tbn — APPROVED** [review]
code lgtm

**Review by kvakvs — APPROVED** [review]
Nice

**Pull request merged**
