### PR TITLE
Dragging/sizing main menu pushes it back into screen rect

### LINKED ISSUE #848: Further enhancements to menu bar
From https://github.com/CitiesSkylinesMods/TMPE/pull/819#issuecomment-615261693

> A few peaky issues that I don't consider to be a blocker:
>  
> 1. Its possible to do this: 
>    Screenshot (850)
>    I made the panel small -> moved it to button of screen -> made it big.
> 2. Dragging can only happen if you drag the label:
>    Screenshot (849)

### LINKED ISSUE #857: Sliders should update tooltip when dragged
> Note: This will be fixed by #849 - this issue is just for clarity in tracking / changelog.

In mod options, sliders don't update their tooltip when dragged, making it difficult to know what current value is without first moving mouse away and then re-hovering.

### PR DESCRIPTION
**Pull request by kvakvs**
Fixes #848
Fixes #857

Minor modification addressing comment in #819 by @kianzarrin 
Removed commented code which will never be used.

## CHECKLIST

- [ ] Update tooltip for remaining sliders (one?)

### CODE REVIEW

**Comment by aubergine10** [comment]
Linked #848

**Comment by kvakvs** [comment]
Somehow the actual main menu never goes offscreen, even though i react on draghandle.
I suspect its the dragging code in CO.UI which limits the window into the screen rect.

**Comment by aubergine10** [comment]
Making it go off-screen:

1. Set scaling factor small
2. Drag window to edge of screen
3. Increase scaling factor - top-left of menu stays in same place, but now it's bigger so some of it is off-screen

So maybe recheck bounds when scaling is changed?

Also, (_I haven't tried this yet_) what happens if menu is dragged towards bottom right of screen, then the screen resolution is reduced? Will it be completely off-screen?

**Comment by kvakvs** [comment]
If you drag to bottom right (i tried that), the main menu remains in GUI coordinate grid, which is always 1920x1080, so it does not move from the corner and is fully in screen.
And yes, i apply the clamp code to the main menu when UI scale changes.

**Comment by kianzarrin** [comment]
> If you drag to bottom right (i tried that), the main menu remains in GUI coordinate grid,

Yes. I you want to push the GUI outside of screen you have to hack your way into it as aubergine explained. 

>  And yes, i apply the clamp code to the main menu when UI scale changes. 

Then why does it go outside of screen? maybe call refresh or invalidate or something. do you refresh absolute position?

**Comment by kianzarrin** [comment]
Can you call `RefreshTooltip()` on the sliders in the Options so that as the user moves the slider, the tooltip value gets updated.:
```c#
protected override void OnValueChanged() {
	base.OnValueChanged();
	tooltip = value.ToString();
	RefreshTooltip();
}
```

**Comment by kvakvs** [comment]
@kianzarrin addressed your list of forgotten commented fragments, they are removed
Also: Adding update tooltips and considering how to make this into every slider that we have. This works amazing good!

**Comment by kvakvs** [comment]
The push logic only forces the label (and drag handle) to return back to the screen, not entire window.

**Comment by aubergine10** [comment]
Loving the sliders updating their tooltips!

However, I was able to make the TMPE menu disappear in a non-recoverable fashion, although I'm not sure how many users will encounter this:

image

With the menu dragged to bottom right corner of screen, I changed from 16:9 2560x1440 resolution down to 4:3 640x480 resolution. Somewhat extreme (just to test), and obviously this isn't going to happen very often IRL. I didn't tested yet for less extreme aspect ratio and resolution changes.

However, some users with low spec systems often run on very low graphics most of the time, but then jump up to higher resolutions to take nice screenshots, so the issue described here it's not completely impossible to happen in the wild.

My suggestion is this - rather than trying to fix this extreme case, why not build a little "recovery mode" in to the main TMPE button?

Specifically:

_Double click the 'crown button' to reset the toolbar position to 0, 0._

This way if we ever get users saying their toolbar disappeared, we can just reply "double click the tmpe button" (as that is usually still on screen based on past reports of missing toolbar).

**Comment by kvakvs** [comment]
Need to double check the assumption again: whether the GUI remains 1920x1080 units internally even when you change the aspect. In the code I assumed that it does. The facts might be telling otherwise.

**Comment by kianzarrin** [comment]
@kvakvs a bit outside of the scope of this review but there is only one slider left without the tooltip refresh and then we can close #857 that's the "dynamic lane selection" in `GamePlay`  Tab

**Comment by kianzarrin** [comment]
Sorry I got a bit lost in the long conversations above. @kvakvs are you planning to push the whole window back into screen when the size gets larger. I have tracked the code and I can see you have observers that should push the window back into screen. but for some reason they don't. maybe put some breakpoints to see if the code is actually being executed?

**Comment by kvakvs** [comment]
The code is pushing the window back so that the handle becomes fully visible. Just what's necessary to drag the window. Does it actually work? I am not sure, all my screen resolutions had same aspect ratio and always 1920x1080 GUI resolution.

**Comment by aubergine10** [comment]
I think this only needs that slider tooltip refresh doing (DLS slider in gameplay tab iirc) then it is good to merge.

**Comment by kianzarrin** [comment]
Screenshot (951)
updated algorithm to handle special case like urban highway connection above. even if the road does not have pedestrian raids pedestrian can cross.:

```c#
//psudo code

segment.SortedLanes[0] is pedestrian => segment has pedestrian lane on the right (going toward the junction).
segment.SortedLanes[count-1] is pedestrian => segment has pedestrian lane on the left(going toward the junction).
bool HasPedestiransOnRight = segment has pedestrian lane on the right OR segment.RightSegment has pedestrian on the left
bool HasPedestiransOnLeft = segment has pedestrian lane on the left OR segment.RightSegment has pedestrian on the right


IsPedestrianCrossingAllowedConfigurable = HasPedestiransOnRight and HasPedestiransOnLeft
GetDefaultPedestrianCrossingAllowed = 2+ pedestrian lanes
```
So the highway-urban junction above pedestrian crossing is configurable but is banned by default.

---
Screenshot (955)

I also would like to avoid ugly wierd junction transitions like above:

```c#
if node has two segments:
	GetDefaultPedestrianCrossingAllowed &= segment.size < otherSegment.size // pedestrian corssing is allowed on the smaller segment only.
	for equal segments only the first one gets pedestrian crossings by default.
```
With this code (and the hide crossings mod) the zebra crossings will look like this by default but both are configurable:
Screenshot (952)

**Comment by kianzarrin** [comment]
@aubergine10  Regarding https://github.com/CitiesSkylinesMods/TMPE/pull/849#issuecomment-621924258 why do you think?
should we ban crossings across highway-urban junction by default?
in a node with two segments, should we remove crossing on the bigger segment by default?

**Comment by aubergine10** [comment]
@kianzarrin What does that stuff above have to do with toolbar? Did you comment on the wrong PR?

**Pull request merged**
