### PR TITLE
hollow floating wire

### LINKED ISSUE #1485: Lane Connection tool does not give UI feedback when lane is connected.
When I making a new lane connection, the bezier snaps to lane. When I click there is no visual difference in the bezier. I wouldn't know if connection was successfully made unless if I move the mouse away which is annoying.

image
making a connection does thicken the line a little bit if you know where to look. but as you can see from picture above its too subtle.

Possible solutions:
- don't snap to lanes
- create a dashed line when removing connection
- change mouse cursor to  `+`/`x` when adding/removing connections respectively
- the line thickness could be visibly different.
- differentiate by using filled or hallow lane connection overlay.
- EDIT: differentiate by using white color #670
- EDIT: reduce opacity of the floating lane beizer
- a combination of above

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #1485 : make it easy to distinguish between adding/removing connection

Visual changes :
- floating wire is white and hollow. 
- when connection is made the underneath connection is visible.
- +/- cursors help to distinguish adding/removing lane connection

- cursor code:
     - Added CursorUtil to create/release cursors
     - Added OverrideCursor to subtools.
     - OverrideCursor also handles the nope_cursor (code moved to lane connection tool).

[TMPE.zip](https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=1485-hollow-floating-wire)

### CODE REVIEW

**Comment by kianzarrin** [comment]
Cities_A62gmvBCHl
Cities_BtYOCOGYnE

**Review by kvakvs — APPROVED** [review]
Minus cursor looks very similar to ⛔ road sign, maybe change color to darker red or black
But this is nice

**Comment by aubergine10** [comment]
what about TMPE logo blue background for the `-` icon?

**Comment by kianzarrin** [comment]
which TMPE logo?

**Comment by aubergine10** [comment]
> which TMPE logo?

the mod logo from workshop page; the darker blue with white `-` sign might work:

image

**Comment by krzychu124** [comment]
Why without a pointer? Also... now when I think of it, why not without circle, just pointer + sign ➕(green), ➖(dark blue)?

**Comment by kianzarrin** [comment]
@chameleon-tbn Can you please address the sprite ideas?

**Comment by kianzarrin** [comment]
meanwhile cham plays with sprites can we do the rest of the code review?

**Review by krzychu124 — APPROVED** [review]

**Review by aubergine10 — APPROVED** [review]
👍

**Comment by kianzarrin** [comment]
thanks. should I wait for cham to come up with better icon or should I just merge and come up with sprite later?
merging will unblock future progress and reduce chance of conflict.

**Comment by aubergine10** [comment]
I think merge and we can start testing stuff and come up with better icon later if desired. I'm really liking the way this is working already in this PR.

**Comment by chameleon-tbn** [comment]
> Why without a pointer? Also... now when I think of it, why not without circle, just pointer + sign ➕(green), ➖(dark blue)?

What's the need of a pointer there? why not center the + / - into the connector circle? ... would clearly show what it does...

blue_minus_31
green_plus_31

> @chameleon-tbn Can you please address the sprite ideas?

cursor_remove_lane_connector_blue_31
cursor_add_lane_connector_31

anything else?

**Comment by kvakvs** [comment]
"Pointer" + "something to the current edit mode" is a good idea, i like

**Comment by kianzarrin** [comment]
Ill create a issue for such improvements

**Comment by krzychu124** [comment]
> > Why without a pointer? Also... now when I think of it, why not without circle, just pointer + sign ➕(green), ➖(dark blue)?
> 
> What's the need of a pointer there? why not center the + / - into the connector circle? ... would clearly show what it does...
> 
> blue_minus_31 green_plus_31
> 
> > @chameleon-tbn Can you please address the sprite ideas?
> 
> cursor_remove_lane_connector_blue_31 cursor_add_lane_connector_31
> 
> anything else?

Because we already use "pointer" + "thing" to do initial selection? It's just to make UX more or less consistent, also similar to how game handles user interactions where it shows cursor

**Pull request merged**
