### PR TITLE
Created missing despawn buttons

### LINKED ISSUE #759: Despawn buttons missing from Vehicle and Cim info panels
In v11.1.1 the `(x)` despawn buttons are no longer appearing on the info panels of vehicles and cims.

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #759 

- created missing sprites,
- changed magic position numbers :)

image
image

New size:
image
image
image

### CODE REVIEW

**Comment by aubergine10** [comment]
Maybe shrink them down a bit? - they look a bit too heavy compared to other UI on those info panels.

**Comment by aubergine10** [comment]
After testing in-game, found a minor glitch when despawning cims - the info panel is not removed: 

image

Same for both tourists and residents.

**Comment by krzychu124** [comment]
> After testing in-game, found a minor glitch when despawning cims - the info panel is not removed:
> 
> image
> 
> Same for both tourists and residents.
Yeah, noticed that, but I don't know why it behaves like that :/

**Comment by aubergine10** [comment]
I think maybe we create issue for that minor glitch (info panel remains) so we can merge this PR and publish hotfix?

**Comment by krzychu124** [comment]
> I think maybe we create issue for that minor glitch (info panel remains) so we can merge this PR and publish hotfix?

Testing fix :)

**Comment by krzychu124** [comment]
@aubergine10 auto-close didn't work on `STABLE 11.1.0` also

**Comment by aubergine10** [comment]
> Fixes minor issue with closing panel after releasing citizen

Panel still not closing, at leasts for tourists. Going to do a fresh build just and test again just in case.

**Comment by aubergine10** [comment]
Tested again, it's specifically tourists now that the info panel does not dissapear. It disappers for residents just fine.

**Pull request merged**
